### ISSUE TITLE
got errors on Mesh builds

### ISSUE THREAD

**Issue by fine77** [WhiteCoreSim/WhiteCore-Dev#101]
tried to rezz a Mesh and got mass of error messages:

SCENEPACKETHANDLER: could not find prim #........ in SelectPrim, Killing prim.

**Comment by fly-man-** [comment]
[Issue Checker] Is this still an issue that needs to be active looked at ?

**Comment by fly-man-** [comment]
[Issue Checker] Issue has been closed due to no response from initial reporter
