### ISSUE TITLE
[Feature request]: Please let me set the PhysicsActorType

### ISSUE THREAD

**Issue by fine77** [WhiteCoreSim/WhiteCore-Dev#112]
within \Framework\Physics\PhysicsActor.cs, there is a abstract int PhysicsActorType.

is there any reason why i can't set the ActorType ?

**Comment by greythane** [comment]
I have been upgrading the Bulletsim code and I think I understand what this request relates to now.

The 'setter' for the ActorType appears to have been removed as it is basically redundant and normally set by the appropriate BulletSim code for the type of actor it is handling.  i.e. BSPrim => Prim, or BSCharacter => Agent.  Other than these two options the type for the Physics actor is never set, hence the reasoning for removing the setter (I believe)

If any other types of Physics Actors are applicable and would be set to override the basic type then re-establishing the setter would not be an issue.

**Comment by greythane** [comment]
Closing this until being able to set the Physics actor to other than the inherited type become a requirement.

**Comment by fine77** [comment]
i think this is a requirement for BulletSim 2.82. much features aren't implemented in the old version.
think about the stuff we're discussed last year but you're right much features needs to be implemented first.

**Comment by greythane** [comment]
Hi Fine,
Nice to hear from you again 😀
I have nearly finished updating the BulletSim code and the PhysicsActor is only defined in two places. The BsCharacter, Avatar, and BsPrim, Prim.   I did initially re-add the setter but it was never used anywhere else in the code.
The only thing I have to do now is to get region crossings and infinite option running.

I will check the Bullet options to see if there are any other instances of the PhysicsActor that might be needed.

**Comment by fine77** [comment]
i was in trouble here. i think it was at the BSActorHover or in the Motor section in general. there was a procedure to update the physicsactortype to the scene and this was nessessary to get the scene updates stable and clean and i thought its important to change the PhysicsActorType on the fly through the physics engine.

**Comment by fine77** [comment]
i saw, that you've changed couple of things at the PrimMesher in this build. 
i'll try to integrate bulletsim 2.82 again with the current code if you want.
let me know

but first i need to know whats new. i've browsed the commit list and there are much new changes since then.
cheers

**Comment by greythane** [comment]
Ah, scene changes/border crossing... That's where the current state is at present.
I will push through the updates as they appear to be working correctly and smoothly within the region. 
Another set of eyes and help would be greatly appreciated.  :)

There have been many changes, mostly cleanups and optimisations to the code and I will go through the past commits and do some more details ' this has changed...' stuff.

**Comment by fly-man-** [comment]
And make sure to check out the Bullet branch as well. Some work has been done in there as well. I think it might also be easier to merge those changes in when possible (if they are helpful)

**Comment by greythane** [comment]
This and other parameters have been incorporated in the current Dev version.
  (BulletSim is working but still a work in progress)
