### ISSUE TITLE
MySQL errors, Terrain errors, Script Save States Broken

### ISSUE THREAD

**Issue by SargeMisfit** [WhiteCoreSim/WhiteCore-Dev#125]
Downloaded December Snapshot (released Jan 14), unpacked and dropped bin folder into place. Upon startup got errors relating to MySQL, scripts, terrain. FireStrom unable to login with "Despite best efforts ..." error message.Log file to large to include, link below

Sim: 8,192m x 8,192, offline, StandAlone Mode

System:
CPU: AMD A8-3820 APU with Radeon(tm) HD Graphics (2495.51 MHz)
Memory: 6101 MB
OS Version: Microsoft Windows 7 64-bit Service Pack 1 (Build 7601)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: GeForce 9500 GT/PCIe/SSE2

All drivers and OS up to date.

Log: https://docs.google.com/document/d/1xT67bfq2yUufzuHcQBtz7GFp3Q67QDZ-Q17Lbv79kxM/edit?usp=sharing

**Comment by TommyFDNY** [comment]
Dittio

**Comment by greythane** [comment]
Hmmm, I have not been able to check yet but it appears that we have had some messing with the database tables??
The verification of mysql tables at startup is throwing errors :(

**Comment by SargeMisfit** [comment]
Well, I'm not familiar enough with MySQL to be able to do anything with it. Its remains unchanged since you first setup WoaS, other than anything incorporated in the coding after that.

**Comment by TommyFDNY** [comment]
That funny, I just entered my first week of Data Systems, and am learning MYSQL... Ill let you know what I pick up. I ned to hekp you guys, or @greythane is going to get mad at me.

**Comment by SargeMisfit** [comment]
No worries, Tommy. I am actually able to use databases in general and am quite familiar with Micro$oft's Access. But it seems that I got some sort of mental "glitch" when it comes to MySQL. So, I just leave it alone. 

My point with the previous comment was to let Grey/Rowan know that I didn't introduce anything that might be the source of the problem.

**Comment by TommyFDNY** [comment]
See I should have just used my inside voice.

**Comment by fly-man-** [comment]
WhiteCore 0.9.3 Dev (2014-12-05.75eacf9) looks to be an older version to me, or did you paste the whole logfile from previous loads as well ?

**Comment by SargeMisfit** [comment]
Its not the whole log, I am still using a previous version. The last two or three snapshots have had errors so I stuck with that. Those may be due to the way I've updated. All I've done is drop the bin folder into place to update.

One thing, I don't run GridMode. I also didn't know about the renaming of database tables.

**Comment by fly-man-** [comment]
Well, I renamed a lot of tables in December to make it more obvious what they were used for. Those tables names that are in your log files are exactly the ones I renamed.

**Comment by SargeMisfit** [comment]
Okay, I'll check the docs, etc,

**Comment by SargeMisfit** [comment]
The Updater addon module does NOT have a build.am file :-(

**Comment by SargeMisfit** [comment]
What update script?

**Comment by fly-man-** [comment]
There is a update script in the most recent bin folder now, when you run WhiteCore at least 3 times it will go through all the conversions that should have been done since November.

When that doesn't work, please make a snapshot of your database and send either me or @greythane a link through email

**Comment by SargeMisfit** [comment]
" ...when you run WhiteCore at least 3 times...

Its not running once. What is the name of the thing so I can copy it to the old version that does run

and how do I take a snapshot of a MySQL database? Especially since I've never been able to run MySQL in the first place?

**Comment by SargeMisfit** [comment]
This instance is working fine

Jan 17 11:20:33 -  ====================================================================
Jan 17 11:20:33 -  ==================== STARTING WhiteCore (x64) ======================
Jan 17 11:20:33 -  ====================================================================
Jan 17 11:20:33 -  [WhiteCoreStartup]: Version: WhiteCore 0.9.3 Dev (2014-12-05.75eacf9)

Jan 17 11:20:33 -  [Network]: Network IP address has been set to 127.0.0.1
Jan 17 11:20:33 -  [BASE HTTP SERVER]: Starting HTTP server on port 9000
Jan 17 11:20:35 -  [BASE HTTP SERVER]: Starting HTTP server on port 8005
Jan 17 11:20:36 -  Creating system real estate user 'Governor Ruth'
Jan 17 11:20:36 -  [USER ACCOUNT SERVICE]: A user with the name Governor Ruth already exists!
Jan 17 11:20:36 -   Unable to create user : A user with the same name already exists
Jan 17 11:20:37 -  [LIBRARY INVENTORY]: Found previously loaded iar file DefaultInventory/DefaultInventory.iar, ignoring.
Jan 17 11:20:37 -  Looking for previous sims in: ../Data/Region
Jan 17 11:20:37 -  Found: Excelsior Station
Jan 17 11:20:37 -  Found: WorkShop
Jan 17 11:20:37 -  [FileBasedSimulationData]: Restoring sim backup for region Excelsior Station...
Jan 17 11:20:51 -  [FileBasedSimulationData]: Restoring sim backup for region WorkShop...
Jan 17 11:20:53 -  [SceneManager]: Starting region "Excelsior Station" at @ 1000,1000
Jan 17 11:21:09 -  [BackupModule]: Loading objects for Excelsior Station from FileBasedDatabase
Jan 17 11:21:11 -  [BackupModule]: Loaded 4597 object(s) in Excelsior Station
Jan 17 11:21:18 -  [BackupModule]: Starting scripts in Excelsior Station
Jan 17 11:21:20 -  [SceneManager]: Startup Complete. This took 0m 49.219s
Jan 17 11:21:20 -  [SceneManager]: Starting region "WorkShop" at @ 2000,2000
Jan 17 11:21:21 -  [BackupModule]: Loading objects for WorkShop from FileBasedDatabase
Jan 17 11:21:21 -  [BackupModule]: Loaded 475 object(s) in WorkShop
Jan 17 11:21:21 -  [BackupModule]: Starting scripts in WorkShop
Jan 17 11:21:21 -  [SceneManager]: Startup Complete. This took 0m 49.827s

I cannot find any updating script or anything that I can decipher as begin related to updating except for the option addon. And that does not have a build.am file so I cannot compile and add it on.

This is a StandAlone. I went to into bin and started WhiteCoreGridServer and it crashed with errors relating to framework. I can't find any log for that.

Excelsior Station is still offline, I'm working from my backup copy of December 20th.

**Comment by fly-man-** [comment]
Ahh, okay. Then indeed, this needs to be handled differently as I was under the impression that you ran it in a Grid mode.

* Do you use SQLite or MySQL to run the instance ?
* Are there any other messages that you get, INI error messages ?

Last snapshot that worked for you was the 5th of December, so it looks that after that something has changed that works with Grid mode but not Standalone mode

**Comment by SargeMisfit** [comment]
I'm using MySQL. If there were ini errors, they'd be in that log I posted
to google docs. Thaht log I just posted is the usual startup for that copy

**Comment by fly-man-** [comment]
Okay, I have slept over this issue and I think it's wise to make a MySQL dump so we're able to see what exactly goes wrong.

Not sure if you use phpMyAdmin or the standard MySQL client so I will describe both ways:

phpMyAdmin:

* Open your browser, connect to "http://localhost/phpmyadmin"
* Click on the left side on the database "Whitecore"
* Click in the top tab set on Export
* Make sure the correct database is selected and then press Start to make the backup file
* Select the place you want to have it saved

MySQL native client:

* Open a command window "cmd"
* Go to the folder where you have your MySQL installed and issue the following command
mysqldump -u [uname] -p[pass] whitecore > db_backup.sql

After you have either the MySQL dump file or the phpMyAdmin file, send either me or @greythane a message on G+ so we can see what exact goes wrong with your DB

**Comment by SargeMisfit** [comment]
Bear with me, RL is interfering

**Comment by TommyFDNY** [comment]
Awwww, no problem. Keep your chin up.

**Comment by fly-man-** [comment]
No rush, I'm looking at what makes my standalone version break each time I start it.

**Comment by SargeMisfit** [comment]
Okay, found out I am not using PHP

Gotta try to go native ...

**Comment by SargeMisfit** [comment]
" 'mysqldump' is not recognized as an internal or external command "

I do have HeidiSQL, can that be used to get the file you need?

**Comment by fly-man-** [comment]
According to this page http://www.heidisql.com/screenshots.php?which=export_sql it can export SQL

What you need to do: 
* Open HeidiSQL
* Connect to the MySQL server
* Find the WhiteCore database on the left side
* Right click on the database and select "Export database as SQL"
* A new window pops up
* Select from the pulldown menu behind Output: "ZIP Compressed .sql file"
* Click on the little disk icon to select the place where you want to save the file
* The Export button will become usable
* Press the Export Button to export the database to file

**Comment by fly-man-** [comment]
@SargeMisfit Just a question as this issue has been open for 3 months:

Are you still experimenting with WhiteCore or have you gone back to Opensim ?

**Comment by SargeMisfit** [comment]
I've left the metaverse

**Comment by TommyFDNY** [comment]
I'm sorry, back and forth between OS, and WC. 

Been swamped with School :-(.

**Comment by fly-man-** [comment]
@SargeMisfit Okay, sorry to hear so. Hope that you are doing well :+1:

**Comment by BogusCurry** [comment]
@SargeMisfit I wish you all best ;D Is sadly that you gone ..

Sorry for the OT ;D
