### ISSUE TITLE
Console for some users close when teleporting to 8192x8192 region

### ISSUE THREAD

**Issue by TommyFDNY** [WhiteCoreSim/WhiteCore-Dev#126]
Callback never came for teleporting agent 5
6bd4297-1cc6-4cfe-b178-21091a0bfd41. Resetting.

Full Log:

Jan 20 09:38:19 - [BASE HTTP SERVER]: Slow handling of GET /MapService/map-6-102
4-1056-objects.jpg took 6162ms
Jan 20 09:38:29 - [BASE HTTP SERVER]: Slow handling of GET /MapService/map-5-104
0-1072-objects.jpg took 3994ms
Jan 20 09:38:29 - [BASE HTTP SERVER]: Slow handling of GET /MapService/map-5-105
6-1072-objects.jpg took 4072ms
Jan 20 09:38:30 - [BASE HTTP SERVER]: Slow handling of GET /MapService/map-6-105
6-1056-objects.jpg took 16131ms
Jan 20 09:38:33 - [BASE HTTP SERVER]: Slow handling of GET /MapService/map-5-104
0-1056-objects.jpg took 29702ms
Jan 20 09:38:33 - [BASE HTTP SERVER]: Slow handling of GET /MapService/map-5-104
0-1056-objects.jpg took 9313ms
Jan 20 09:38:33 - [BASE HTTP SERVER]: Slow handling of GET /MapService/map-5-105
6-1056-objects.jpg took 9126ms
Jan 20 09:38:39 - [AgentProcessing]: Starting to inform client about neighbor Pu
laras
Jan 20 09:38:39 - [AgentProcessing]: Completed inform client about neighbor Pula
ras
Jan 20 09:38:44 - [CapsHandlers]: Handling Seed Cap request at http://8.38.77.92
:8003/CAPS/45fc53cd-ee36-4641-b34f-4169426262870000/
Jan 20 09:38:56 - [AgentProcessing]: Closing 1 child agents around Pularas Immig
ration Island
Jan 20 09:38:56 - [AgentProcessing]: Closing child agent in Pularas Immigration
Island
Jan 20 09:47:23 - [LLOGIN SERVICE]: Login request for tommy arkright from 64.20.
151.100 with user agent Firestorm-Releasex64 4.6.9.42974 starting in last
Jan 20 09:47:24 - [LLOGIN SERVICE]: All clear. Sending login response to client
to login to region Pularas, tried to login to last at <1031.945, 1057.517, 33.79
448>.
Jan 20 09:47:31 - [CapsHandlers]: Handling Seed Cap request at http://8.38.77.92
:8003/CAPS/6f01102c-d3c8-4136-9a43-052e74fde33f0000/
Jan 20 09:47:37 - [BASE HTTP SERVER]: Slow handling of POST /CAPS/FetchInventory
Descendents/4e6739b9-d618-47d8-8091-1d8197ef3fac/ took 4025ms
Jan 20 09:47:39 - [BASE HTTP SERVER]: Slow handling of POST /CAPS/FetchInventory
Descendents/4e6739b9-d618-47d8-8091-1d8197ef3fac/ took 3900ms
Jan 20 09:48:46 - [AgentProcessing]: Starting to inform client about neighbor Pu
laras Immigration Island
Jan 20 09:48:46 - [AgentProcessing]: Completed inform client about neighbor Pula
ras Immigration Island
Jan 20 09:48:46 - [CapsHandlers]: Handling Seed Cap request at http://8.38.77.92
:8003/CAPS/a74c6790-95b2-4a4a-bef7-d79bba26786c0000/
Jan 20 09:48:47 - [CapsHandlers]: Handling Seed Cap request at http://8.38.77.92
:8003/CAPS/a74c6790-95b2-4a4a-bef7-d79bba26786c0000/
Jan 20 09:48:54 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/38c4
f427-5899-4e20-965e-63d7eefa3815//?texture_id=1d139331-ad30-4dfb-8826-e957846bd0
c3 took 3120ms
Jan 20 09:48:56 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/38c4
f427-5899-4e20-965e-63d7eefa3815//?texture_id=36c4ae02-22b7-490b-ab5d-3344bccb25
9c took 4649ms
Jan 20 09:48:57 - [AgentProcessing]: Closing 1 child agents around Pularas
Jan 20 09:48:57 - [AgentProcessing]: Closing child agent in Pularas
Jan 20 09:48:57 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/38c4
f427-5899-4e20-965e-63d7eefa3815//?texture_id=e30e9d8a-adad-4d1e-b600-a14a3a9d37
d7 took 4196ms
Jan 20 09:48:58 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/38c4
f427-5899-4e20-965e-63d7eefa3815//?texture_id=f4294487-a8c2-44ca-80ae-f52794f7f6
9a took 3494ms
Jan 20 09:49:28 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/38c4
f427-5899-4e20-965e-63d7eefa3815//?texture_id=1c0fffe0-b586-4f44-96bb-84195bb61e
b5 took 3932ms
Jan 20 09:49:31 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/38c4
f427-5899-4e20-965e-63d7eefa3815//?texture_id=a0b3835c-a06f-4155-9b08-2001d6f42d
fc took 4071ms
Jan 20 10:16:12 - [BASE HTTP SERVER]: Slow handling of GET /javascripts/jquery-1
.11.1.js took 5741ms
Jan 20 10:16:25 - [BASE HTTP SERVER]: Slow handling of GET /javascripts/jquery-1
.11.1.js took 11263ms
Jan 20 10:16:26 - [BASE HTTP SERVER]: Slow handling of GET /images/screenshots/w
elcome10.jpg took 11544ms
Jan 21 02:07:02 - [LLOGIN SERVICE]: Login request for Tommy Arkright from 64.20.
151.100 with user agent Singularity Release 64 1.8.6.6156 starting in last
Jan 21 02:07:02 - [LLOGIN SERVICE]: All clear. Sending login response to client
to login to region Pularas Immigration Island, tried to login to last at <140.75
2, 134.7218, 38.07274>.
Jan 21 02:07:03 - [CapsHandlers]: Handling Seed Cap request at http://8.38.77.92
:8003/CAPS/0ee44456-e28b-4d89-8e7d-fdb8ec60f12a0000/
Jan 21 02:07:16 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/b76f
2d72-358e-4f49-b798-ae51beff15b8//?texture_id=e30e9d8a-adad-4d1e-b600-a14a3a9d37
d7 took 3416ms
Jan 21 02:07:17 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/b76f
2d72-358e-4f49-b798-ae51beff15b8//?texture_id=1d139331-ad30-4dfb-8826-e957846bd0
c3 took 7005ms
Jan 21 02:07:18 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/b76f
2d72-358e-4f49-b798-ae51beff15b8//?texture_id=36c4ae02-22b7-490b-ab5d-3344bccb25
9c took 6599ms
Jan 21 02:07:21 - [LocalAssetDatabase] GetAsset(1e506d0c-4811-bdf3-5ec7-d624284c
9040) - Asset UUID(w) was not found.
Jan 21 02:08:31 - [AgentProcessing]: Starting to inform client about neighbor Pu
laras
Jan 21 02:08:32 - [AgentProcessing]: Completed inform client about neighbor Pula
ras
Jan 21 02:08:35 - [CapsHandlers]: Handling Seed Cap request at http://8.38.77.92
:8003/CAPS/a02d4c22-e775-4a6b-a915-aa3f47dd028b0000/
Jan 21 02:08:45 - [AgentProcessing]: Closing 1 child agents around Pularas Immig
ration Island
Jan 21 02:08:45 - [AgentProcessing]: Closing child agent in Pularas Immigration
Island
Jan 21 02:20:51 - [BASE HTTP SERVER]: Slow handling of GET /javascripts/jquery-1
.11.1.js took 4555ms
Jan 21 02:21:06 - [LLOGIN SERVICE]: Login request for Rafael Constructor from 18
9.60.129.178 with user agent Firestorm-Releasex64 4.6.9.42974 starting in last
Jan 21 02:21:06 - [LLOGIN SERVICE]: All clear. Sending login response to client
to login to region Pularas Immigration Island, tried to login to last at <144.57
, 131.7446, 38.0724>.
Jan 21 02:21:12 - [CapsHandlers]: Handling Seed Cap request at http://8.38.77.92
:8003/CAPS/893b9c32-9ba2-447c-a1f2-961adf2b892b0000/
Jan 21 02:21:49 - [BASE HTTP SERVER]: Slow handling of POST /CAPS/FetchInventory
Descendents/4aacf78c-8bb8-42d6-9bc8-4d557c6cab9d/ took 3307ms
Jan 21 02:21:50 - [BASE HTTP SERVER]: Slow handling of POST /CAPS/FetchInventory
Descendents/4aacf78c-8bb8-42d6-9bc8-4d557c6cab9d/ took 3916ms
Jan 21 02:21:51 - [BASE HTTP SERVER]: Slow handling of POST /CAPS/FetchInventory
Descendents/4aacf78c-8bb8-42d6-9bc8-4d557c6cab9d/ took 3900ms
Jan 21 02:21:53 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/fc98
9aaf-ec8f-426d-a35b-6d682b9d7c38//?texture_id=e3970b43-7e33-49ba-be76-f3a312b7c8
fc took 7753ms
Jan 21 02:21:55 - [BASE HTTP SERVER]: Slow handling of POST /CAPS/FetchInventory
Descendents/4aacf78c-8bb8-42d6-9bc8-4d557c6cab9d/ took 6193ms
Jan 21 02:21:57 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetMesh/53543a2
b-9197-4f53-b385-6a5085eb11aa//?mesh_id=337a9af9-4183-45d4-98d1-26629130ed94 too
k 3105ms
Jan 21 02:21:58 - [BASE HTTP SERVER]: Slow handling of POST /CAPS/FetchInventory
Descendents/4aacf78c-8bb8-42d6-9bc8-4d557c6cab9d/ took 4852ms
Jan 21 02:22:01 - [BASE HTTP SERVER]: Slow handling of POST /CAPS/FetchInventory
Descendents/4aacf78c-8bb8-42d6-9bc8-4d557c6cab9d/ took 5694ms
Jan 21 02:22:01 - [BASE HTTP SERVER]: Slow handling of POST /CAPS/FetchInventory
Descendents/4aacf78c-8bb8-42d6-9bc8-4d557c6cab9d/ took 5553ms
Jan 21 02:22:02 - [BASE HTTP SERVER]: Slow handling of POST /CAPS/FetchInventory
Descendents/4aacf78c-8bb8-42d6-9bc8-4d557c6cab9d/ took 6209ms
Jan 21 02:22:09 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/fc98
9aaf-ec8f-426d-a35b-6d682b9d7c38//?texture_id=f4294487-a8c2-44ca-80ae-f52794f7f6
9a took 7410ms
Jan 21 02:22:10 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/fc98
9aaf-ec8f-426d-a35b-6d682b9d7c38//?texture_id=e30e9d8a-adad-4d1e-b600-a14a3a9d37
d7 took 9111ms
Jan 21 02:22:11 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/fc98
9aaf-ec8f-426d-a35b-6d682b9d7c38//?texture_id=1d139331-ad30-4dfb-8826-e957846bd0
c3 took 8096ms
Jan 21 02:22:15 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/fc98
9aaf-ec8f-426d-a35b-6d682b9d7c38//?texture_id=36c4ae02-22b7-490b-ab5d-3344bccb25
9c took 8908ms
Jan 21 02:22:19 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/fc98
9aaf-ec8f-426d-a35b-6d682b9d7c38//?texture_id=b4f72db2-06f5-41b8-8bb4-ba287c6608
12 took 3916ms
Jan 21 02:22:20 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/fc98
9aaf-ec8f-426d-a35b-6d682b9d7c38//?texture_id=d8936fb4-bb5d-4856-9657-2fd654871f
02 took 7815ms
Jan 21 02:22:23 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/fc98
9aaf-ec8f-426d-a35b-6d682b9d7c38//?texture_id=a0b3835c-a06f-4155-9b08-2001d6f42d
fc took 8096ms
Jan 21 02:22:24 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/fc98
9aaf-ec8f-426d-a35b-6d682b9d7c38//?texture_id=1c648424-0f79-4c2a-80c8-c45ac2aa51
b0 took 8127ms
Jan 21 02:22:24 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/fc98
9aaf-ec8f-426d-a35b-6d682b9d7c38//?texture_id=12b01871-0f42-4e8d-a817-ec89efdacb
80 took 5460ms
Jan 21 02:22:26 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/fc98
9aaf-ec8f-426d-a35b-6d682b9d7c38//?texture_id=35d6de2b-0bd9-47c9-b110-ad67abd165
e1 took 9188ms
Jan 21 02:22:27 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/fc98
9aaf-ec8f-426d-a35b-6d682b9d7c38//?texture_id=c4523deb-b4b3-4926-b6ad-8c4cc3f835
f8 took 7504ms
Jan 21 02:22:29 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/fc98
9aaf-ec8f-426d-a35b-6d682b9d7c38//?texture_id=dcffa923-42a7-4039-a8a4-81f1761a17
7f took 4228ms
Jan 21 02:22:29 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/fc98
9aaf-ec8f-426d-a35b-6d682b9d7c38//?texture_id=b04e2eb4-751b-45f1-a8a2-b653eb225a
dd took 8268ms
Jan 21 02:22:29 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/fc98
9aaf-ec8f-426d-a35b-6d682b9d7c38//?texture_id=9048f85c-0141-4227-ab3a-8611c07bbc
5f took 10639ms
Jan 21 02:22:30 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/fc98
9aaf-ec8f-426d-a35b-6d682b9d7c38//?texture_id=7a46d0c2-aa82-4dbe-89ca-a489b89d89
cc took 8299ms
Jan 21 02:22:40 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/fc98
9aaf-ec8f-426d-a35b-6d682b9d7c38//?texture_id=1c0fffe0-b586-4f44-96bb-84195bb61e
b5 took 8268ms
Jan 21 02:22:42 - [AgentProcessing]: Starting to inform client about neighbor Pu
laras
Jan 21 02:22:42 - [AgentProcessing]: Completed inform client about neighbor Pula
ras
Jan 21 02:22:58 - [AgentProcessing]: Callback never came for teleporting agent 5
6bd4297-1cc6-4cfe-b178-21091a0bfd41. Resetting.
Jan 21 02:24:40 - [AgentProcessing]: Starting to inform client about neighbor Pu
laras Immigration Island
Jan 21 02:24:41 - [AgentProcessing]: Completed inform client about neighbor Pula
ras Immigration Island
Jan 21 02:24:41 - [CapsHandlers]: Handling Seed Cap request at http://8.38.77.92
:8003/CAPS/a8d3e0f9-3cfe-48d5-bd45-3267675db2590000/
Jan 21 02:24:52 - [AgentProcessing]: Closing 1 child agents around Pularas
Jan 21 02:24:52 - [AgentProcessing]: Closing child agent in Pularas
Jan 21 02:26:45 - [BASE HTTP SERVER]: Slow handling of GET /javascripts/jquery-1
.11.1.js took 5804ms
Jan 21 02:26:56 - [BASE HTTP SERVER]: Slow handling of GET /javascripts/jquery-1
.11.1.js took 5990ms
Jan 21 02:27:11 - [LLOGIN SERVICE]: Login request for Rafael Constructor from 18
9.60.129.178 with user agent Firestorm-Releasex64 4.6.9.42974 starting in last
Jan 21 02:27:11 - [LLOGIN SERVICE]: Login failed for user Rafael Constructor, re
ason: Incorrect password
Jan 21 02:27:18 - [BASE HTTP SERVER]: Slow handling of GET /javascripts/jquery-1
.11.1.js took 5928ms
Jan 21 02:27:26 - [BASE HTTP SERVER]: Slow handling of GET /javascripts/jquery-1
.11.1.js took 5803ms
Jan 21 02:27:34 - [LLOGIN SERVICE]: Login request for Rafael Constructor from 18
9.60.129.178 with user agent Firestorm-Releasex64 4.6.9.42974 starting in last
Jan 21 02:27:34 - [LLOGIN SERVICE]: All clear. Sending login response to client
to login to region Pularas Immigration Island, tried to login to last at <152.01
42, 124.7536, 38.08388>.
Jan 21 02:27:41 - [CapsHandlers]: Handling Seed Cap request at http://8.38.77.92
:8003/CAPS/8584296e-2420-4de0-ad0b-51342d5a74670000/
Jan 21 02:28:02 - [BASE HTTP SERVER]: Slow handling of POST /CAPS/FetchInventory
Descendents/4aa958fb-f187-41ab-98d4-5c40833e8eb3/ took 3229ms
Jan 21 02:28:02 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/bca8
f660-cb78-43b7-ac23-b8029cd83c98//?texture_id=12b01871-0f42-4e8d-a817-ec89efdacb
80 took 4493ms
Jan 21 02:28:05 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/bca8
f660-cb78-43b7-ac23-b8029cd83c98//?texture_id=dcffa923-42a7-4039-a8a4-81f1761a17
7f took 4509ms
Jan 21 02:28:05 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/bca8
f660-cb78-43b7-ac23-b8029cd83c98//?texture_id=1c648424-0f79-4c2a-80c8-c45ac2aa51
b0 took 7582ms
Jan 21 02:28:05 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/bca8
f660-cb78-43b7-ac23-b8029cd83c98//?texture_id=e3970b43-7e33-49ba-be76-f3a312b7c8
fc took 7940ms
Jan 21 02:28:05 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/bca8
f660-cb78-43b7-ac23-b8029cd83c98//?texture_id=f4294487-a8c2-44ca-80ae-f52794f7f6
9a took 8143ms
Jan 21 02:28:06 - [BASE HTTP SERVER]: Slow handling of POST /CAPS/FetchInventory
Descendents/4aa958fb-f187-41ab-98d4-5c40833e8eb3/ took 7534ms
Jan 21 02:28:06 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/bca8
f660-cb78-43b7-ac23-b8029cd83c98//?texture_id=d8936fb4-bb5d-4856-9657-2fd654871f
02 took 9157ms
Jan 21 02:28:08 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/bca8
f660-cb78-43b7-ac23-b8029cd83c98//?texture_id=7a46d0c2-aa82-4dbe-89ca-a489b89d89
cc took 9579ms
Jan 21 02:28:09 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/bca8
f660-cb78-43b7-ac23-b8029cd83c98//?texture_id=b4f72db2-06f5-41b8-8bb4-ba287c6608
12 took 4477ms
Jan 21 02:28:11 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/bca8
f660-cb78-43b7-ac23-b8029cd83c98//?texture_id=e30e9d8a-adad-4d1e-b600-a14a3a9d37
d7 took 9001ms
Jan 21 02:28:11 - [BASE HTTP SERVER]: Slow handling of POST /CAPS/FetchInventory
Descendents/4aa958fb-f187-41ab-98d4-5c40833e8eb3/ took 7004ms
Jan 21 02:28:12 - [BASE HTTP SERVER]: Slow handling of POST /CAPS/FetchInventory
Descendents/4aa958fb-f187-41ab-98d4-5c40833e8eb3/ took 5460ms
Jan 21 02:28:14 - [BASE HTTP SERVER]: Slow handling of POST /CAPS/FetchInventory
Descendents/4aa958fb-f187-41ab-98d4-5c40833e8eb3/ took 5943ms
Jan 21 02:28:15 - [BASE HTTP SERVER]: Slow handling of POST /CAPS/FetchInventory
Descendents/4aa958fb-f187-41ab-98d4-5c40833e8eb3/ took 7239ms
Jan 21 02:28:15 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/bca8
f660-cb78-43b7-ac23-b8029cd83c98//?texture_id=a0b3835c-a06f-4155-9b08-2001d6f42d
fc took 8970ms
Jan 21 02:28:17 - [BASE HTTP SERVER]: Slow handling of POST /CAPS/FetchInventory
Descendents/4aa958fb-f187-41ab-98d4-5c40833e8eb3/ took 7488ms
Jan 21 02:28:19 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/bca8
f660-cb78-43b7-ac23-b8029cd83c98//?texture_id=1d139331-ad30-4dfb-8826-e957846bd0
c3 took 7925ms
Jan 21 02:28:19 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/bca8
f660-cb78-43b7-ac23-b8029cd83c98//?texture_id=36c4ae02-22b7-490b-ab5d-3344bccb25
9c took 8330ms
Jan 21 02:28:20 - [BASE HTTP SERVER]: Slow handling of POST /CAPS/FetchInventory
Descendents/4aa958fb-f187-41ab-98d4-5c40833e8eb3/ took 8455ms
Jan 21 02:28:22 - [BASE HTTP SERVER]: Slow handling of POST /CAPS/FetchInventory
Descendents/4aa958fb-f187-41ab-98d4-5c40833e8eb3/ took 9376ms
Jan 21 02:28:24 - [BASE HTTP SERVER]: Slow handling of POST /CAPS/FetchInventory
Descendents/4aa958fb-f187-41ab-98d4-5c40833e8eb3/ took 11840ms
Jan 21 02:28:34 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/bca8
f660-cb78-43b7-ac23-b8029cd83c98//?texture_id=b8e09c5b-4a1b-4c8e-952d-ac0906b049
a0 took 3198ms
Jan 21 02:28:36 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/bca8
f660-cb78-43b7-ac23-b8029cd83c98//?texture_id=c4523deb-b4b3-4926-b6ad-8c4cc3f835
f8 took 7847ms
Jan 21 02:28:37 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/bca8
f660-cb78-43b7-ac23-b8029cd83c98//?texture_id=b04e2eb4-751b-45f1-a8a2-b653eb225a
dd took 8237ms
Jan 21 02:28:39 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/bca8
f660-cb78-43b7-ac23-b8029cd83c98//?texture_id=9048f85c-0141-4227-ab3a-8611c07bbc
5f took 12386ms
Jan 21 02:28:39 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/bca8
f660-cb78-43b7-ac23-b8029cd83c98//?texture_id=35d6de2b-0bd9-47c9-b110-ad67abd165
e1 took 7894ms
Jan 21 02:29:03 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/bca8
f660-cb78-43b7-ac23-b8029cd83c98//?texture_id=c93fc251-bcec-4eeb-9fe7-8d58aca5db
d6 took 7894ms
Jan 21 02:30:34 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/bca8
f660-cb78-43b7-ac23-b8029cd83c98//?texture_id=1c0fffe0-b586-4f44-96bb-84195bb61e
b5 took 7286ms
Jan 21 02:32:59 - [BASE HTTP SERVER]: Slow handling of POST /CAPS/NewFileAgentIn
ventory/78fda048-4640-480d-8339-d86210ca703e/ took 7566ms
Jan 21 02:33:41 - [BASE HTTP SERVER]: Slow handling of POST /CAPS/Upload/8c688b2
b-d4dc-4aae-a61e-6213b64dacd4/ took 7956ms
Jan 21 02:36:29 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/bca8
f660-cb78-43b7-ac23-b8029cd83c98//?texture_id=9da97527-62f4-4798-9e93-cabb22dcd6
a0 took 5475ms
Jan 21 02:36:30 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/bca8
f660-cb78-43b7-ac23-b8029cd83c98//?texture_id=3333612a-2043-4269-9803-beccb8ae53
da took 10156ms
Jan 21 02:36:30 - [BASE HTTP SERVER]: Slow handling of GET /CAPS/GetTexture/bca8
f660-cb78-43b7-ac23-b8029cd83c98//?texture_id=9d18febb-e448-455a-b6fb-86ea6abfbc
91 took 7426ms
WhiteCore.Server #

**Comment by fly-man-** [comment]
I am not sure what to say other then that 8192 x 8192 regions have a lot of issues. Both with keeping them alive but also with generating terrain for them.

Safe are anything between 16x16 and 4096x4096

**Comment by TommyFDNY** [comment]
I hope we can fix this; this I feel has a huge impact on the value, and platform of WhiteCore sim. Especially to us Flight developers.

**Comment by TommyFDNY** [comment]
BTW: I canlog in no problem from my desktop. 8core AMD, 32 gig, Win 7, all up to date.

**Comment by fly-man-** [comment]
The problem with large regions like the 8192x8192 is that viewer and server need to communicate less which might cause the viewer to miss packets that the server sends or viceversa.

And I think a 4096x4096 might be the limit for regions without things going boom

**Comment by fly-man-** [comment]
Closing this issue as we have decided that 4096x4096 is the largest possible supported region size.
