### ISSUE TITLE
ODE physics issue......

### ISSUE THREAD

**Issue by Almo-Skytower** [WhiteCoreSim/WhiteCore-Dev#128]
The ODE is causing problems.......lots of red writing resulting in no avatar physics so not being able to move. I can just about make out the words "physics scene near" etc. What does this mean and how can I fix it?
 Are there any plans to include BulletSim, is there a link to BulletSim download for WhiteCore physics you have already prepared? 
What is the most stable release of the overall WC project now?
Nice to see all the WhiteCore folk again..

**Comment by fly-man-** [comment]
* ODE has had a little upgrade so it's odd that there's red lines

* BulletSim is already in WC, all you need to do is enable it

* The latest release is 0.9.2 which you can find under the Releases tab on Gothub

**Comment by Almo-Skytower** [comment]
Thanks for reply.
I re-installed Bin and Framework and its ODE red lines have gone. I have played with WC a little last year whilst I lived in Spain and managed to get grid mode working. Now Im back in my home country of UK and just been unpacking my computers and looking to get my old grid back loaded.
I am using the windows install directly from your WC homepage.
