### ISSUE TITLE
After BIN update Region major crash occurs upon start up

### ISSUE THREAD

**Issue by TommyFDNY** [WhiteCoreSim/WhiteCore-Dev#131]
System.TypeLoadException: Could not load type 'ComponentAce.Compression.Libs.zli
b.ZOutputStream' from assembly 'zlib.net, Version=1.0.3.0, Culture=neutral, Publ
icKeyToken=47d7877cb3620160'.
   at OpenMetaverse.Helpers.ZDecompressOSD(Byte[] data)
   at OpenMetaverse.Assets.AssetMesh.Decode()
2808 [STP SmartThreadPool Thread #3] ERROR - Failed to decode mesh asset
System.TypeLoadException: Could not load type 'ComponentAce.Compression.Libs.zli
b.ZOutputStream' from assembly 'zlib.net, Version=1.0.3.0, Culture=neutral, Publ
icKeyToken=47d7877cb3620160'.
   at OpenMetaverse.Helpers.ZDecompressOSD(Byte[] data)
   at OpenMetaverse.Assets.AssetMesh.Decode()
2808 [STP SmartThreadPool Thread #3] ERROR - Failed to decode mesh asset
System.TypeLoadException: Could not load type 'ComponentAce.Compression.Libs.zli
b.ZOutputStream' from assembly 'zlib.net, Version=1.0.3.0, Culture=neutral, Publ
icKeyToken=47d7877cb3620160'.
   at OpenMetaverse.Helpers.ZDecompressOSD(Byte[] data)
   at OpenMetaverse.Assets.AssetMesh.Decode()
2808 [STP SmartThreadPool Thread #3] ERROR - Failed to decode mesh asset
System.TypeLoadException: Could not load type 'ComponentAce.Compression.Libs.zli
b.ZOutputStream' from assembly 'zlib.net, Version=1.0.3.0, Culture=neutral, Publ
icKeyToken=47d7877cb3620160'.
   at OpenMetaverse.Helpers.ZDecompressOSD(Byte[] data)
   at OpenMetaverse.Assets.AssetMesh.Decode()
2823 [STP SmartThreadPool Thread #3] ERROR - Failed to decode mesh asset
System.TypeLoadException: Could not load type 'ComponentAce.Compression.Libs.zli
b.ZOutputStream' from assembly 'zlib.net, Version=1.0.3.0, Culture=neutral, Publ
icKeyToken=47d7877cb3620160'.
   at OpenMetaverse.Helpers.ZDecompressOSD(Byte[] data)
   at OpenMetaverse.Assets.AssetMesh.Decode()
2823 [STP SmartThreadPool Thread #3] ERROR - Failed to decode mesh asset
System.TypeLoadException: Could not load type 'ComponentAce.Compression.Libs.zli
b.ZOutputStream' from assembly 'zlib.net, Version=1.0.3.0, Culture=neutral, Publ
icKeyToken=47d7877cb3620160'.
   at OpenMetaverse.Helpers.ZDecompressOSD(Byte[] data)
   at OpenMetaverse.Assets.AssetMesh.Decode()
2823 [STP SmartThreadPool Thread #3] ERROR - Failed to decode mesh asset
System.TypeLoadException: Could not load type 'ComponentAce.Compression.Libs.zli
b.ZOutputStream' from assembly 'zlib.net, Version=1.0.3.0, Culture=neutral, Publ
icKeyToken=47d7877cb3620160'.
   at OpenMetaverse.Helpers.ZDecompressOSD(Byte[] data)
   at OpenMetaverse.Assets.AssetMesh.Decode()
2823 [STP SmartThreadPool Thread #3] ERROR - Failed to decode mesh asset
System.TypeLoadException: Could not load type 'ComponentAce.Compression.Libs.zli
b.ZOutputStream' from assembly 'zlib.net, Version=1.0.3.0, Culture=neutral, Publ
icKeyToken=47d7877cb3620160'.
   at OpenMetaverse.Helpers.ZDecompressOSD(Byte[] data)
   at OpenMetaverse.Assets.AssetMesh.Decode()
2839 [STP SmartThreadPool Thread #3] ERROR - Failed to decode mesh asset
System.TypeLoadException: Could not load type 'ComponentAce.Compression.Libs.zli
b.ZOutputStream' from assembly 'zlib.net, Version=1.0.3.0, Culture=neutral, Publ
icKeyToken=47d7877cb3620160'.
   at OpenMetaverse.Helpers.ZDecompressOSD(Byte[] data)
   at OpenMetaverse.Assets.AssetMesh.Decode()
2839 [STP SmartThreadPool Thread #3] ERROR - Failed to decode mesh asset
System.TypeLoadException: Could not load type 'ComponentAce.Compression.Libs.zli
b.ZOutputStream' from assembly 'zlib.net, Version=1.0.3.0, Culture=neutral, Publ
icKeyToken=47d7877cb3620160'.
   at OpenMetaverse.Helpers.ZDecompressOSD(Byte[] data)
   at OpenMetaverse.Assets.AssetMesh.Decode()
2839 [STP SmartThreadPool Thread #3] ERROR - Failed to decode mesh asset
System.TypeLoadException: Could not load type 'ComponentAce.Compression.Libs.zli
b.ZOutputStream' from assembly 'zlib.net, Version=1.0.3.0, Culture=neutral, Publ
icKeyToken=47d7877cb3620160'.
   at OpenMetaverse.Helpers.ZDecompressOSD(Byte[] data)
   at OpenMetaverse.Assets.AssetMesh.Decode()
2839 [STP SmartThreadPool Thread #3] ERROR - Failed to decode mesh asset
System.TypeLoadException: Could not load type 'ComponentAce.Compression.Libs.zli
b.ZOutputStream' from assembly 'zlib.net, Version=1.0.3.0, Culture=neutral, Publ
icKeyToken=47d7877cb3620160'.
   at OpenMetaverse.Helpers.ZDecompressOSD(Byte[] data)
   at OpenMetaverse.Assets.AssetMesh.Decode()
Apr 10 05:32:55 - [MapTileGenerator]: Generating Maptile for Pularas Immigration
 Island, using WarpTileRenderer, took 5819 ms 'ComponentAce.Compression.Libs.zli
Apr 10 05:32:55 - [Warp3D]: Exception in the map generation, System.OutOfMemoryE
xception: Exception of type 'System.OutOfMemoryException' was thrown.
   at WhiteCore.Modules.WorldMap.WarpTileRenderer.CreateTerrain(Warp3D renderer,
 Boolean textureTerrain)ts.AssetMesh.Decode()
   at WhiteCore.Modules.WorldMap.WarpTileRenderer.TerrainBitmap(Viewport viewpor
t, Boolean threeD)eption: Could not load type 'ComponentAce.Compression.Libs.zli
Apr 10 05:32:59 - [MapTileGenerator]: Generating Maptile for Pularas, using Warp
TileRenderer, took 9001 ms0'.
root: # enMetaverse.Helpers.ZDecompressOSD(Byte[] data)

**Comment by fly-man-** [comment]
Where is this from, Snapshot or current master ??

**Comment by greythane** [comment]
This is an issue opening some mesh gestures with the current zlib library.  It appears that a different version of zlib has been used when compiling the Openmetaverse libraries.

The Out of Memory problem is also known and relates to limited memory availability (Windows limiting, not physical) when running in x86 mode (32 bit) on Windows.  This is being investigated currently.

**Comment by TommyFDNY** [comment]
Snapshot

**Comment by fly-man-** [comment]
Ahh, okay, Seems @greythane already explained what might be it. Strange that I have no issues running Whitecore Snapshot on both Linux and Windows x86/x64.

**Comment by TommyFDNY** [comment]
I must be bad luck. Is their a fix? :-(

**Comment by fly-man-** [comment]
@TommyFDNY You could try and compile OpenMetaVerse and then grab the zlib file to see if that fixes it for you

**Comment by fly-man-** [comment]
@TommyFDNY I just updated the zLib to a newer version, can you see if this fixed your bug.

zLib is 1.1.0 now, not the most recent version yet but I want to hear if this fixes your issue

**Comment by TommyFDNY** [comment]
I'll be doing this in the next hour; how do I do this correctly?

**Comment by fly-man-** [comment]
@TommyFDNY Just replace your bin folder with a clean compiled one. Then load up your region instance and see if you get more error messages or less. I hope less because this should fix up the incompatibility between the one that LibOMV uses and the one we now use.

**Comment by TommyFDNY** [comment]
will do today, had dinner and guests last night.

**Comment by fly-man-** [comment]
@TommyFDNY No problem, take your time. Currently working on the new ScriptEngine implementation

**Comment by TommyFDNY** [comment]
Any idea when HG will be enabled ? :-)

**Comment by fly-man-** [comment]
No, because at this moment there's a lot of other things that take our attention. This issue of yours for instance :D

**Comment by fly-man-** [comment]
[ Closed ]

No response and new zLib has been placed
