### ISSUE TITLE
Error messages by build from last git - source 

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#132]
I have update my local whitecore sims server and becomes after build a error messages
http://paste.md-5.net/webakuqiwa.vbs

Is that a new feature ?

**Comment by greythane** [comment]
The 'OpenSimUDPBAse' file was renamed to 'UDPBase' a couple of days ago.
What you should do is rebuild the project files by running 'runprebuild.sh'  This will then include the correct filenames.

**Comment by TommyFDNY** [comment]
I'm on it! Thannnnnnnkkkk yoooooyuuuuuu

**Comment by BogusCurry** [comment]
thank you for fast answer ;D

**Comment by fly-man-** [comment]
Yes, there have been some changes in the Master. Cleaning out some of the "old" Opensim references
