### ISSUE TITLE
Console error after login in webinterface

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#133]
I have seen in the console this error message, after login in my webinterface
http://paste.md-5.net/jicohibuno.avrasm

Install have my WhiteCore local, so run this with sqlite and is the last git version from the this night

**Comment by greythane** [comment]
Hi Bogus,
Are you using a translation other than English as this appears to be what the error relates to?
If not, can you tell me which page you were accessing? ...  Or was this just login and crash?
There had been some work on adding some more details to the region info very recently.

**Comment by BogusCurry** [comment]
Hi Greythane ;D
I have using the german translation in the webinterface. The region is a 512x512, I am not owner from the region, only normal user

**Comment by fly-man-** [comment]
@BogusCurry Almost looks like the German translation file isn't up to date for some strange reason.

I cleaned up the German and other language files, please check if this has fixed it

**Comment by BogusCurry** [comment]
yes that have I seen it ;D I will update my local whitecore  ..

**Comment by BogusCurry** [comment]
ok bug is fixed ;D 

thanks for the fast support ;D

**Comment by fly-man-** [comment]
[ Fixed ]
