### ISSUE TITLE
AForge.Math.dll not found

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#134]
I compile the addons modules and I see that the dll is for the WhiteCore.Addon.FlexibleWind. How I can fix that ?

Compile with the actual whitecoresim git version

**Comment by greythane** [comment]
Yes, small problem with copying the full correctly.
Check in the FlexibleWind folder and you will see AForge.Math.dll.include.  This has been incorrectly named. Remove the 'include' and you have the dll.  
You will probably need to copy this dll to the WhiteCoreSim/bin folder as well.
I'll redo this and correct things tomorrow.

**Comment by BogusCurry** [comment]
Ok Thanks Greythane

**Comment by fly-man-** [comment]
[ Fixed ]
