### ISSUE TITLE
I can't rezz meshes under SQlite

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#136]
When I upload meshes comes this http://paste.md-5.net/yarokufexe.coffee

Must I the upload option enable in the configs or is this a bug ?

**Comment by fly-man-** [comment]
Mesh should upload normally, can you tell me which version you are using at the moment ?

**Comment by BogusCurry** [comment]
I use the actualy git version from 11.06

**Comment by fly-man-** [comment]
I'm in the IRC now. If you have time, hop on in which makes it easier to talk :)

**Comment by BogusCurry** [comment]
I am now in the IRC ;D Have time enough to talk ..

**Comment by fly-man-** [comment]
Well, don't see you in the IRC at the moment. Might be an idea to tell which channel and name you're using ;)

**Comment by BogusCurry** [comment]
I use the whitecore-support .... I have update to the last git version and now when I start whitecore becomes I this messages
http://paste.md-5.net/cepafepaxu.coffee

**Comment by emperorstarfinder** [comment]
Hi bogus.  Put log4net.dll back in the bin and run.  The reason is Logger.css in libOMV requires log4net per one of its using references.

**Comment by BogusCurry** [comment]
HI emporstarfinder ;D Thanks for the tip, but where I can find the log4net.dll ?

**Comment by emperorstarfinder** [comment]
you can find it in an opensim repository or i can email you a copy of the dll if you like

**Comment by fly-man-** [comment]
So log4net was indeed still being used for something, latest master has it restored.

**Comment by emperorstarfinder** [comment]
Yes its used by Logger.cs in libOMV.  If Logger.cs is rewritten so that it doesn't need that method for logging and were to use something similar to MainConsole.Instance in the ConsoleFramework then you could remove the need for log4net

**Comment by fly-man-** [comment]
But that still doesn't explain why meshes aren't rendering properly for @BogusCurry

**Comment by emperorstarfinder** [comment]
Agreed That would only fix the log4net.  I haven't noticed the mesh piece myself yet. But then again I have been playing around with terrain code lately myself.

**Comment by fly-man-** [comment]
Hmm, and 1 other thing I just noticed is that we have an older version of Log4Net it seems. Might have a see that the latest version holds

**Comment by emperorstarfinder** [comment]
What version is the most current for log4net? and I would assume that still holds true for log4net due to Logger.cs in libOMV I just pulled a latest copy of WhiteCore-Dev I assume Bogus is on linux and will see if i can reproduce the issue with mesh.

**Comment by fly-man-** [comment]
The latest version is 1.2.13 but I just noticed that since .11 they added .Net 4 support. Might indeed be worth compiling a new version indeed

**Comment by emperorstarfinder** [comment]
Okay.  looking at what Opensim's is at.  I just jumped in to #whitecore-support easier to chat that way so I dont go messing up all my windows LOL

**Comment by fly-man-** [comment]
@BogusCurry Can you give us a complete detail on what version of Mono you are using:

Mono JIT compiler version 4.0.1 (tarball Thu May 28 09:08:28 UTC 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen

**Comment by BogusCurry** [comment]
Ok .. with mono 4.0.1 and the last git version have the same problem, I can't rezz on my region

Mono JIT compiler version 4.0.1 (tarball Thu May 28 09:08:28 UTC 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen

**Comment by fly-man-** [comment]
@BogusCurry Can you send me that mesh you're trying to upload. I kinda want to make sure it's not the mesh you made that's breaking it. I'm in IRC till 12 PM today

**Comment by fly-man-** [comment]
After some tests it looks that the mesh itself isn't the issue but the storage method (SQlite) that breaks the chain and crashing the instance.

**Comment by fly-man-** [comment]
At the moment I don't think that SQlite is a sustainable database for grid mode so my suggestion would be to retest this using MySQL. 

If this error still persists with MySQL as well, please open a new issue about it
