### ISSUE TITLE
[Issue] WarpTile Render renders objects as black

### ISSUE THREAD

**Issue by fly-man-** [WhiteCoreSim/WhiteCore-Dev#156]
Since the latest master (03ef99c678aafc106db39d01d803acec5def97a0) the WarpTile render renders most of the objects as black instead of the indicated color. There has been work done on the WarpTile renderer but it seems that now most of the images are showing black.

**Comment by fly-man-** [comment]
Partially fixed, ini files on the servers had a double UseAsyncMapTileCreation

But it seems like the WarpTileRender does not go through all the prims and gets their textures, making it look like things are black

**Comment by greythane** [comment]
Corrected in commit 15fef81
Resolution of objects down to 2meters will be shown as textured on the map tile

Generation also set to Asynchronous to assist blocking problems

**Comment by fly-man-** [comment]
The only problem with the WTR now is that I am getting error messages due to the fact we're using a different version of Log4Net then LibOMV uses. 

Easy fix is to place back the original Log4Net that comes from LibOMV but I'd rather find out why this "bugs out"

**Comment by fly-man-** [comment]
Commit d69561435417865ff72d671cd4b2bb6c1906e531 reverts the Log4Net back to the one that's originally in the LibOMV. I have a feeling it has to do with not being signed properly but to quickfix this issues, replaced the Log4Net
