### ISSUE TITLE
Duplicate of avatar remains in location after teleport if other avatars are present.

### ISSUE THREAD

**Issue by stormsonweathers** [WhiteCoreSim/WhiteCore-Dev#157]
Hello again,
There's seems to be a duplicate glitch that involves an avatar that teleports (like returning home, etc) if another avatar is present, but a copy of the avatar remains and replicates the movements of the recently teleported one.

This is on the current build as of 09/13/15.

**Comment by greythane** [comment]
Hi Storm,  Could you provide some more details on this error?
i.e. How are you checking on the copy avatar etc.?
   I assume you have multiple avatars logged in to multiple regions?
   The error occurs when you teleport from region A to B?
   Which viewer are you using?  (Probably not a problem but worth checking)
  System.. Windows, linux, Mac, setup : grid/standalone :  Dtatbase (MySql/SqLite)

And anything else that may be useful to reproduce the problem
G

**Comment by stormsonweathers** [comment]
Hello,
I was checking with multiple Windows machines running the latest Firestorm Viewer on the same network with different avatars. I've also had some friends log in and they to have noticed similar events using different viewers such as Singularity.

On the technical side for the server: The database is set for Mysql/MariaDB on OpenSUSE with 8gb in a VM setting while WhiteCore - the latest as of today - is running on Windows 7 Professional also on a VM with 16GB in standalone mode. (Both VMs are running on top of Hyper-V using Windows Server with 64GB of total RAM and two 3Ghz 4-Core Xeon Processors)

The error occurs either on multiple regions or the same one (there is one megaregion and several 256x256 standard regions; same result)

**Comment by fly-man-** [comment]
At the moment, can't replicate this issue. However placing this on the top of the 0.9.4 issue list

**Comment by emperorstarfinder** [comment]
I haven't seen this issue reproduce as of yet.  I am guessing this might have either resolved itself or has been fixed in updates to date.
