### ISSUE TITLE
unable to enable bulletsim

### ISSUE THREAD

**Issue by stormsonweathers** [WhiteCoreSim/WhiteCore-Dev#158]
This may be more of a user error, if so please forgive me, but every build of WC I've tried i cannot compile the Bulletsim plugins even with MS Studio even with a clean slate. I'm getting 8 errors and all are related to compiling Bulletsim, but everything else compiles fine.

**Comment by fly-man-** [comment]
Can you make a pastebin of the build log, I'd like to see which errors you are getting as 1 of my workers is upgrading Bullet using the Opensim based version

**Comment by stormsonweathers** [comment]
I've looked everywhere for the build log and cannot seem to locate it, where in the directory structure is it normally located?

**Comment by fly-man-** [comment]
It usually comes from Visual Studio, I am curious which errors you exactly get while compiling. I know there's some warnings about things not matching in VS but those are mere warnings and not errors

**Comment by stormsonweathers** [comment]
Here is a copy of the errorlog from VS 2013. It's not huge so I decided to paste it directly here:

Warning	1	The field 'WhiteCore.Region.Physics.BulletSPlugin.BSActorAvatarMove.m_walkingUpStairs' is assigned but its value is never used	C:\srv\WhiteCore-Dev\WhiteCore\Physics\BulletSPlugin\BSActorAvatarMove.cs	40	21	WhiteCore.Physics.BulletSPlugin
Warning	2	The field 'WhiteCore.Region.Physics.BulletSPlugin.BSActorAvatarMove.m_lastStepUp' is never used	C:\srv\WhiteCore-Dev\WhiteCore\Physics\BulletSPlugin\BSActorAvatarMove.cs	41	23	WhiteCore.Physics.BulletSPlugin
Warning	3	The field 'WhiteCore.Region.Physics.BulletSPlugin.BSActorAvatarMove.m_jumpframes' is assigned but its value is never used	C:\srv\WhiteCore-Dev\WhiteCore\Physics\BulletSPlugin\BSActorAvatarMove.cs	42	21	WhiteCore.Physics.BulletSPlugin
Warning	4	The field 'WhiteCore.Region.Physics.BulletSPlugin.BSActorAvatarMove.m_jumpVelocity' is assigned but its value is never used	C:\srv\WhiteCore-Dev\WhiteCore\Physics\BulletSPlugin\BSActorAvatarMove.cs	43	23	WhiteCore.Physics.BulletSPlugin
Warning	5	The field 'WhiteCore.Region.Physics.BulletSPlugin.BSPrim._grabbed' is never used	C:\srv\WhiteCore-Dev\WhiteCore\Physics\BulletSPlugin\BSPrim.cs	45	22	WhiteCore.Physics.BulletSPlugin
Warning	6	The field 'WhiteCore.Region.Physics.BulletSPlugin.BSPrim._physicsActorType' is assigned but its value is never used	C:\srv\WhiteCore-Dev\WhiteCore\Physics\BulletSPlugin\BSPrim.cs	55	21	WhiteCore.Physics.BulletSPlugin
Warning	7	The field 'WhiteCore.Region.Physics.BulletSPlugin.BSPrim._kinematic' is never used	C:\srv\WhiteCore-Dev\WhiteCore\Physics\BulletSPlugin\BSPrim.cs	64	22	WhiteCore.Physics.BulletSPlugin
Warning	8	Field 'WhiteCore.Modules.Web.WebInterface.webPages' is never assigned to, and will always have its default value null	C:\srv\WhiteCore-Dev\WhiteCore\Modules\Web\WebInterface.cs	67	27	WhiteCore.Modules

**Comment by emperorstarfinder** [comment]
These are warnings that have been around with WhiteCore for a good while.  In general warnings will not break or prevent the build from successfully completing.  It is safe not to worry about those warnings during your build process.  In some cases depending on whether your building on windows, Linux or Mac OS X you probably will have a different number of warnings but it will still build.  Only an error will prevent the build from successfully completing.  Hopefully once Bullet Physics is upgraded those warnings will disappear..

**Comment by stormsonweathers** [comment]
I understand it's a warning  but as mentioned, I did change the physics.ini setting to bulletsim from SL-ODE Physics as well and the sim crashes every time. I am certain it's user error so I'm mostly looking for context on what I'm doing wrong since others are able to use bulletsim.

**Comment by emperorstarfinder** [comment]
Okay when the sim crashes what errors are being thrown in the console?  This might tell us if theres something funny going on with the region or if theres something wrong with the configuration.

**Comment by stormsonweathers** [comment]
OK, here's the log at the time of the crash (This was after another rebuild using Visual Studio and the regular runprebuild.bat -- Same result.:

Sep 14 02:59:07 -  [Physics]: Couldn't find physics engine: BulletSim
Sep 14 02:59:07 -  [APPLICATION]: 
APPLICATION EXCEPTION DETECTED

Exception: System.ArgumentException: couldn't find physics engine: BulletSim
   at WhiteCore.Modules.Startup.PhysicsPluginManager.GetPhysicsScene(String physEngineName, String meshEngineName, IConfigSource config, IScene scene) in c:\srv\WhiteCore-Dev\WhiteCore\Modules\World\Startup\PhysicsPluginManager.cs:line 92
   at WhiteCore.Modules.Startup.PhysicsInitializer.Initialise(IScene scene, IConfigSource source, ISimulationBase simBase) in c:\srv\WhiteCore-Dev\WhiteCore\Modules\World\Startup\PhysicsInitializer.cs:line 73
   at WhiteCore.Region.SceneManager.StartModules(IScene scene) in c:\srv\WhiteCore-Dev\WhiteCore\Region\SceneManager.cs:line 462
   at WhiteCore.Region.SceneManager.StartRegion(ISimulationDataStore simData, RegionInfo regionInfo) in c:\srv\WhiteCore-Dev\WhiteCore\Region\SceneManager.cs:line 283
   at WhiteCore.Region.SceneManager.StartRegions(Boolean& newRegion) in c:\srv\WhiteCore-Dev\WhiteCore\Region\SceneManager.cs:line 258
   at WhiteCore.Region.SceneManager.PostStart() in c:\srv\WhiteCore-Dev\WhiteCore\Region\SceneManager.cs:line 171
   at WhiteCore.Simulation.Base.SimulationBase.StartModules() in c:\srv\WhiteCore-Dev\WhiteCore\Simulation\Base\SimulationBase.cs:line 372
   at WhiteCore.Simulation.Base.SimulationBase.Startup() in c:\srv\WhiteCore-Dev\WhiteCore\Simulation\Base\SimulationBase.cs:line 247
   at WhiteCore.Simulation.Base.BaseApplication.Startup(IConfigSource originalConfigSource, IConfigSource configSource, ISimulationBase simBase, String[] cmdParameters) in c:\srv\WhiteCore-Dev\WhiteCore\Simulation\Base\BaseApplication.cs:line 598

Application is terminating: False

**Comment by greythane** [comment]
This appears to be something missing as far as enabling BulletSim in the configuration.
If you can send me a copy of your Config directory I'll have a look at it...

**Comment by emperorstarfinder** [comment]
I would agree it appears something is missing.  Also be sure you have BulletSim enabled in Meshing.ini as well that may be a piece to this as well.

**Comment by stormsonweathers** [comment]
@greythane How do that through github (seems to only prefer images) is email preferred? 
@emperorstarfinder I'll give it a look-see, thanks!

**Comment by fly-man-** [comment]
@stormsonweathers @emperorstarfinder @greythane There's nothing missing. There's a special way to put the Bullet dll files in the correct folders. I'd have to experiment to find the exact thing again but the dll's need to be in a different place then they are now

**Comment by greythane** [comment]
I have had a look at BulletSim and basically the current implementation is broken because the updates that were done appear to be either incomplete or actually missing some details.

I have corrected the major problems and have got a partially working engine but anything using mesh is still unusable.  Collisions with the mesh objects are not being fired so all mesh is treated as 'phantom', which for a mesh terrain, means you end up under water after falling through the 'ground'

I will continue to look at this but the short term solution may be to revert to the older implementation that did appear to work better than the current code.

Note: Plans are in place to do a complete upgrade of the Bullet code.

**Comment by stormsonweathers** [comment]
Oh, I see. Thanks for the replies everyone. I thought I might have been doing something wrong since I wasn't able to get BulletSim to work at all and seeing that others were able to use it.

**Comment by greythane** [comment]
Storm, Could you email me at gmail re the Bulletsim stuff.
I have been working on updates for the last week and you would probably be a good testing candidate.
 greythane

**Comment by stormsonweathers** [comment]
I can do that.

**Comment by stormsonweathers** [comment]
@greythane the updates seem to be working and in some cases it feels a tad faster than ODE. Will keep the testserver running for a few weeks to try out.
