### ISSUE TITLE
Issue 84 - Governor can't edit Land / Parcel anymore

### ISSUE THREAD

**Issue by rjstechnet** [WhiteCoreSim/WhiteCore-Dev#167]
https://github.com/WhiteCoreSim/WhiteCore-Dev/issues/84

The above is happening and what is described is evident in the latest 0.9.3 trunk.
Why others are not posting what is needed? Maybe time for a mantis install?

**Comment by greythane** [comment]
Issue #84 refers to ..' the Governor White can't edit the Land/Parcel anymore.'

The 'Governor' account should not be used for land sales as this account does not (should not) own land.
The 'Real Estate' user is the account that owns Mainland regions with all other 'normal' regions being owned by the associated user account.

Please provide some further details as to what is being done here.

**Comment by greythane** [comment]
Land ownership has been modify slightly to the following.

Mainland regions, owned by the 'Governor' except for parcels sold to users for building etc. If a user abandons the parcel it will revert back to the 'Governor'

Estates, normally owned by users but can be owned by the 'Real Estate Manager' if no user Estate exists (temporarily parked region) If a parcels sold to another user are owned by that user unless abandoned and then they will revert back to the Estate owner.

Nothing further has been heard on this issue.
