### ISSUE TITLE
Question: How I can move a region to a another position ?

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#168]
Hello ;D

My question is how I can move a region to a another position ? Have no commands found, that I can move a region to another position.

Greetings

Bogus

**Comment by fly-man-** [comment]
I think there's not a command for it yet. Normally you could do it inworld with the Estate Controls

However, out of experience I know it doesn't work "properly"

Best we'd implement a command to move region

**Comment by BogusCurry** [comment]
Ok. which inworld Estate Controls mean you ?

I make at time tutorials in german, so comes I to the problem with the move region. OK I will see inworld after the controls ;D

**Comment by fly-man-** [comment]
I'm in the IRC channels now, come on in so I can show you which ones I mean

**Comment by BogusCurry** [comment]
OK I am on the way ;D

**Comment by emperorstarfinder** [comment]
Hi guys

The command your looking for in the console @BogusCurry would be update region info

This command will ask you the same series of questions as when you create the region.  Once you have done this you will however need to restart the region for the changes to take effect.  Hope that helps just a little bit.

**Comment by BogusCurry** [comment]
Thanks @emperorstarfinder  I will test this ;D

**Comment by BogusCurry** [comment]
Ok, I make the command in the console, but now have this .. 

http://www.pic-upload.de/view-28916240/Bildschirmfoto_2015-11-21_20-25-17.png.html

lol

**Comment by fly-man-** [comment]
Yes, remember that the Grid keeps the "old" image as well. So when you request the map and haven't cleared your cache, the region will still show up but when you click on it, it won't allow you to teleport to it

**Comment by BogusCurry** [comment]
ahh yes you are right ;D

**Comment by greythane** [comment]
Hi Bogus,
You can change the region settings for your (region) console  as follows...

Change to the region you are modifying >  change region my_region
Update the settings for the region  > update region info

This will prompt you for the region settings, assuming the current, where you can change the location, size etc.

If you do change location or size, it is a good idea to restart your sim.
Other settings like, infinite, capacity etc do not require a restart.

**Comment by BogusCurry** [comment]
thanks for your answer greythane ;D

**Comment by fly-man-** [comment]
I think this is 1 of those things that we "could" handle within WebUI 2.0 for region owners.

Thanks for pointing this one out, I've placed it onto the "To think about" list for WebUI 2.0

**Comment by fly-man-** [comment]
Just adding a small detail: I just managed to move a region in the viewer by using the God Tools.

The only problems that I did see: 

* There's no confirmation prompt that it has done it, only when rebooting the region server the change is being shown. 

* When clicking the Refresh button, the old data are still being shown (even when the new data is entered)

**Comment by fly-man-** [comment]
Commits ed586aea3aa42d68247add15615121844848dc33 and d3eca2a2a20f556dcb329b3c0a861f4d91d917df should clarify what the God Tools exactly do when you press the Apply button.
