### ISSUE TITLE
Mesh objects physics remain after object is removed

### ISSUE THREAD

**Issue by stormsonweathers** [WhiteCoreSim/WhiteCore-Dev#169]
Hello again, 
Got another ODE physics error that came up after the last update. Whenever an object either mesh or prim is removed from the region  the physics still remain and the following error is presented:

Nov 24 11:19:22 - [PHYSICS]:  ode Collide failed: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at WhiteCore.Physics.OpenDynamicsEngine.d.CollidePtr(IntPtr o1, IntPtr o2, Int32 flags, IntPtr contactgeom array, Int32 skip) at WhiteCore.Physics.OpenDynamicsEngine.ODEPhysicsScene.IsNearBody(IntPtr gspace, IntPtr g1, IntPtr g2) in c:\srv\WhiteCore-Dev\WhiteCore\Physics\OpenDynamicsEngine\ODEPhysicsScene.cs:line 500

Tried also on a test server running Bullet, but the error isn't present there.
My current system specs is 64bit VM running 64bit windows 7 and 16gb of RAM. The server is running in standalone mode.

**Comment by stormsonweathers** [comment]
OK, when I reverted back to build 3a17e39 and t fixed the problem. I just have to play with it between the this version and the ODE updates to see where the break is.

**Comment by greythane** [comment]
This commit is the one immediately prior to the the major BulletSim 2.8 update.
There were changes to the meshing process and I suspect it has something to do with caching of  mesh objects.  Cacheing was the default prior to the update with the update adding a 'should cache' flag during the creation process to provide for forced creation of an object without re-using a previously cached duplicate object.
The ODE code only had minor updates to add the 'shouldcache' flag to WODEPrim and is set as 'true' i.e. same as previously used.

**Comment by fly-man-** [comment]
I haven't seen this issue reproduce as of yet. I am guessing this might have either resolved itself.

Please open a new issue report when this is still happening after the release of 0.9.4
