### ISSUE TITLE
[Question] Are the instructions in the Whitecore Sim / Whitecore Docs folder / up to date?

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#170]
Good morning ;D
Little Question, are the instructions in the Whitecore Sim / Whitecore Docs folder / up to date for the 0.9.3 ?

Greetings
Bogus

**Comment by fly-man-** [comment]
I haven't checked since the last time but I thought that all the docs in the folders are outdated since 0.9.2 

However, we do have a WhiteCore Documentation Repository which I am generally pushing changes to documentation to when I make changes in the future

https://github.com/WhiteCoreSim/Whitecore-Documentation

Perhaps an idea to use that for further documentation and remove the Docs folders from this repository ??

**Comment by BogusCurry** [comment]
Hmm .. remove yes, but then a wiki here on the github as Documentation. I think is not the best way a project without a good documentation. Please not the same fault as the OpenSim project with the wiki-site, the no more is up to date. ;D

**Comment by fly-man-** [comment]
I've created the Documentation Repo, mainly because I don't want to make the same mistake as Opensim ;)

But we have a Wiki here, it's just not filled with any other details then sketches of the new WebUI and some basic things.

**Comment by BogusCurry** [comment]
I will helping the project, but I think my englisch is not so good for a englisch wiki site. But I can help make the translation for the german users ;D

**Comment by emperorstarfinder** [comment]
The key here is not whether a wiki for another project is kept up to date or not but whether you have enough venues of documentation for your users that is up to date.  

Opensim's wiki while some of the documentation is out of date, is actually maintained not just by their core developers but also by their users.  This means as long as your a registered user on their wiki you could also help maintain the documentation that is on their wiki.  In theory with their recent changes in who can commit to their repository it is now conceivable that anyone can help maintain the documentation in their repository.

That being said as I felt I should weigh in, I will be updating the documentation for networking in the next day or two as when I wrote the documentation for Windows I did not include Windows 10 users.  I will also have a look at the rest of the documentation as well to see if I can find anything needing updates.

**Comment by BogusCurry** [comment]
Hello ;D
I see that greythane the docu has make up to date, thanks for that ;D
