### ISSUE TITLE
the stipend command is very buggy 

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#173]
Hello ;D
The stipend command is very buggy, but see you this screenshot
http://bogus.as4u.de/privat/bilder/wcs/Bildschirmfoto_2015-12-09_23-01-09.png

Actualy is stipend no important for me, but is a nice option for the future ;D

**Comment by greythane** [comment]
Actual stipend processing is fine, this is a problem with the console interactive prompting when enabling stipend payments from the console.

Revised interactive structure and added additional trapping - corrected in commit # e2cfc3a...

**Comment by BogusCurry** [comment]
Ok thanks greythane ;D - The problem is fixed .. can close here ;D
