### ISSUE TITLE
[Question] How I can remove a estate ?

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#174]
Hello ,D

How I can remove Estate ?

**Comment by greythane** [comment]
Good question  :)
It appears that there is no way to remove an estate once it is created.
I will implement a 'delete estate' command with the associated checks etc.

**Comment by BogusCurry** [comment]
hey thanks for that ;D

**Comment by greythane** [comment]
'delete estate' command and a couple of cleanups of the 'estate link/unlink region' commands now available in the latest dev master (commit # 907794...)
