### ISSUE TITLE
Region Map (not mini-map) shows diagonal terrain on regions greater than 1024x1024

### ISSUE THREAD

**Issue by stormsonweathers** [WhiteCoreSim/WhiteCore-Dev#177]
Hello again,
Using the current version of WC (as of the date of the post), I'm still stress testing it and ran into a mapping problem with regions greater than 1024x1024, I've inclosed an image with two 2048x2048 regions (at the top) and three 1024x1024 regions below them (the white space is an empty area).

![screen shot 2015-12-25 at 1 23 36 pm](https://cloud.githubusercontent.com/assets/7484424/12019595/42c1e0c0-ad2f-11e5-9ff0-93adb94140e2.png)

 If you look at the the two top regions the one on the top left was intentionally left empty (no visible terrain - water only) and the one next to it was a small cluster of land surrounded by water, but the mapper seems to remove the water at the lower left corner while the upper left is how it should appear. The 1024x1024 regions are showing correctly. I have tried different viewers and even different OSes (both VM and on metal) and clean installs and getting the same results. 

I forgot to note that the mini-map shows the regions correctly as well as being rendered correctly in-sim.

**Comment by emperorstarfinder** [comment]
This may actually be viewer related and not server-side.  I am not so sure if the viewers can fully handle the bigger region sizes on the world map itself.  The viewer may have a hard time handling rendering a tile on the world map that is representing a region bigger then 1024x1024.  Also if you zoom out and then back in this may also help render the tiles fully.

I think he intended this to be reported as a bug but not really sure.

**Comment by influxWishdream** [comment]
Checking. This may be a bug within the Warp3D map renderer. Since most of the time the viewer only loads images of a tile and not rendering the map itself.

**Comment by greythane** [comment]
Sorted in the latest commit # aea8de... of 10th feb 2016

This is possibly due to a problem in the Warp3D library relating to 'Planes' which will be investigated when possible.

**Comment by greythane** [comment]
Closing this as not further received.
Some images.   The small region bottom LHS is a 256x256 region with 4 1024x1024 and 2 2048x2048

![large_regions_viewer](https://cloud.githubusercontent.com/assets/4934735/13127330/e37ab8f4-d622-11e5-9db9-c754f4cf4b9b.png)
![large_regions_web](https://cloud.githubusercontent.com/assets/4934735/13127335/e940da3e-d622-11e5-82fd-d36baea3c484.png)
