### ISSUE TITLE
llSetPos and llSetRot, same with it's llSetPrimitiveParams counterpart doesn't work on HUD Attachments.

### ISSUE THREAD

**Issue by influxWishdream** [WhiteCoreSim/WhiteCore-Dev#178]
I'm not so sure if it's only me but when I tried rigorous testing on the llSetPos, llSetRot as well as it's llSetPrimitiveParams counterpart just doesn't work on HUDs.
I tried every workaround I know and it's all a no go, it just wouldn't update or move sadly.

I programmed a simple move script on the HUD, it's function is to hide the HUD. A toggle if you will, like an on and off button. Sadly, it doesn't work if llSetPos and llSetRot wouldn't execute right.

While I want to try and fix this myself and contribute the fix here in Git, I want to see if you guys can fix it first from my hefty schedule or can confirm and reproduce the problem.

Tested on Windows 10 64-bit, Windows 7 64-bit and Ubuntu 64-bit machines.
Used the current master directly from git and compiled it myself for each of the platforms.
Compiled with VS2015 on 10 and VS2013 on 7. On Ubuntu, I just used what was provided.

**Comment by greythane** [comment]
If you can provide your simple script to use as an example, I'll check it out.

**Comment by fly-man-** [comment]
Part of this might be because we haven't implement the update that OpenSim has for those functions. I remember that I commited parts of it but not the complete set.

**Comment by influxWishdream** [comment]
It might possibly be. @fly-man- 
Here's a simple script for it.

`//Move the object up 0.1m when someone touches it.
default {
     touch_start(integer i) {
          llSetPos(llGetPos() + <0,0,0.1>);
     }
}`

**Comment by greythane** [comment]
Verified these functions are operating correctly.. using supplied script
(Other updates had previously been incorporated in the setPos functionality so this may have corrected this problem)
