### ISSUE TITLE
Mesh

### ISSUE THREAD

**Issue by LifeGold** [WhiteCoreSim/WhiteCore-Dev#181]
Good day. When you try to load the mesh once you've selected a file, the client immediately gives this error what is the problem tell me? Error of request of transfer of the mesh

**Comment by greythane** [comment]
Hi,
A little vague in description here  :)  
I assume you are trying to upload a mesh from the client.  Which One?  Firestorm, Singularity etc
In the mesh upload dialog, the mesh is selected.  Is this where you are getting the error?
Maybe the error is reported when you start the upload?

**Comment by emperorstarfinder** [comment]
The other thing to do here to is see if there is an error showing up on the consoles when this happens.  If there is an error showing up on the console (i.e. WhiteCore.exe), this would be helpful as well in determining where the issue, if it is not with that particular mesh object would be.

**Comment by LifeGold** [comment]
Он вообще после попытки загрузки ничего не выдает http://prntscr.com/a62m9v http://prntscr.com/a62mux
Here is a screen of the server, no action occurs. You have on the server also could not download the file.
http://prntscr.com/a62n22

**Comment by emperorstarfinder** [comment]
If you are trying to upload the mesh then you are getting the error regarding the asset not found because those textures wont have the same asset UUID as the original UUID from the grid you downloaded from.  You would need to upload those textures as well and then apply them in-world.

**Comment by greythane** [comment]
Uploading mesh is a multi stage process...

Once the file is loaded (and displayed in the preview) you need to set you parameters etc.
Note: The file load only loads the mesh into the viewer, not the sim server.
When you are ready to upload to the server you need to select the 'Calculate Weights & Fees' button.
![screen shot 2016-02-22 at 9 27 14 am](https://cloud.githubusercontent.com/assets/4934735/13205901/fd52a814-d946-11e5-9843-8d45a1522f27.png)

This may take a few seconds but when completed this button will be renamed to 'Upload' (with a corresponding fee depending upon setup etc)
![screen shot 2016-02-22 at 9 27 57 am](https://cloud.githubusercontent.com/assets/4934735/13205906/199556d4-d947-11e5-8387-85489a3105c3.png)

Selecting the 'Upload' button will commence uploading the mesh object to the server.   Once complete this dialog will be closed and (normally but viewer dependant) you Inventory will be displayed containing the uploaded mesh object.

**Comment by LifeGold** [comment]
Thank you to sort out all works
