### ISSUE TITLE
Port

### ISSUE THREAD

**Issue by LifeGold** [WhiteCoreSim/WhiteCore-Dev#184]
Good day. How to make a website http://mysite.com not like now http://mysite.com:8002
The server settings \ Config\Grid\WebServerConfiguration\WebInterface.ini activated the field Port (Port: 80 ) did not help.

**Comment by emperorstarfinder** [comment]
The builtin webUI will automatically default to port 8002 to change the port to 80 you also need would need to probably change the port the grid service (if running in grid mode) to port 80 along with port 80 in WebInterface.ini.  keep in mind this may or may not necessarily work for the built in webUI.  Alternatively you could use the standalone webUI here: https://github.com/WhiteCoreSim/WhiteCore-Webui  however it might or might not work based on updates that have happened over the last few months.

**Comment by greythane** [comment]
Changing the grid server port is not a great idea unless you want to access the grid at that address as well.
I will check this and investigate why it is being overridden.

**Comment by emperorstarfinder** [comment]
I think this is because the builtin webUI is directly reliant on the grid service and the http service.  But you are correct changing the grid port is not recommended unless you want to have the grid pointing to that port

**Comment by greythane** [comment]
Setting the builtin Web UI to port 80 is possible 'as is' but there are a few 'gotchas'
Port 80 is a restricted port and the program using this port needs to run with elevate priviledges.

On *nix based systems you will need to run the sim exe (standalone/grid) with the 'sudo' command, assuming that there is no program currently using port 80.. 
eg sudo mono WhiteCore.exe or sudo mono WhiteCore.Server.exe

For windows systems there may already be a service running that is listening on port 80..  something similar to "World Wide Web Publishing Services".
If this is the case... find service "W3SVC" and disable it, or set it to "manual". Alternatively from and admin console enter "sc stop W3SVC"  (no quotes)
If there is no program using port 80 then it will be available if set as WhiteCore always runs with Administrator privileges  

For all systems the relevant file is 'WebInterface.ini"
Standalone :  Config/Sim/Standalone/WebInterface.ini
Grid            :  Config/Grid/ServerConfiguration/Modules/WebInterface.ini

NOTE:  
The WebServerConfiguration folder in Config/Grid is only used for the individual servers configuration as per the examples in Config/Grid  i.e. WhiteCore.WebServer.ini.example.   These examples are NOT included by default and are just templates for configuring WhiteCore with individual servers.

As this is confusing (inherited configuration) I will modify the structure of the Grid configuration slightly to make this clearer and less confusing.

**Comment by LifeGold** [comment]
Thank you . Happened . Only with W3SVC on Windows and did not understand ( ( (

**Comment by WhiteCoreWebUI** [comment]
i need to make some little changes to the webui which will happen in a few days then it should be compatible to the current state of WhiteCore again currently all works except the detail pages for Profiles and Regions i will fix that

**Comment by greythane** [comment]
This relates to configuration which has been clarified and to additional services not under WhiteCore control.
