### ISSUE TITLE
WebUI Register

### ISSUE THREAD

**Issue by LifeGold** [WhiteCoreSim/WhiteCore-Dev#185]
Good day. Wanted to ask maybe someone knows. When registering you have the choice of the avatar "Avatar Selection" How to add skins avatar.

**Comment by greythane** [comment]
You can include avatar selections in the WebUI by saving avatar appearance archives.
Note:  Te avatar selection in the latest V3 viewers is not yet implemented.

I will  do a tutorial on this as even though it not terribly complex, there are some steps that require some additional info for correct display. (Description of 'how to' is in the WhiteCoreDocs folder > Avatar Archive Setup.txt)

**Comment by WhiteCoreWebUI** [comment]
Mentioning a bug here, avatar archives are indeed not showing up anymore, aswell as they save in the ./bin folder instead of the Data/AvatarArchives
