### ISSUE TITLE
[question] Which file is important for information log in the world ?

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#186]
Hello ;D
I have a little quick question, which file is important for the information log in the world ? I mean the Info by name from my grid or welcomemessage, short the gridinfoservice. My problem is, I have editied the file myworld.ini where stand the gridinfoservice etc., but when I log in, then comes the old default message.
I hope you understand, what I mean ;D
Greetings
Bogus | Have a nice Day

**Comment by emperorstarfinder** [comment]
Myworld.ini is more of an example file.  The files you want to edit would be:

Grid = Config/Grid/ServerConfiguration/GridInfoService.ini
SIm (Standalone) = Config/Sim/Standalone/StandaloneCommon.ini

Those files will change the welcome message and grid name.  Also if you do the run configurator command it will edit the necessary files after asking you some questions as well about your configuration.

**Comment by greythane** [comment]
The MyWorld.ini is a quick configuration point if you are running in Standalone mode only. It contains the basic settings only and this will override anything set in WhiteCore.ini.

It is ignored if grid mode is selected, in which case, as above, the WhiteCore.Server.ini and Grid/ServerConfiguration files are used (GridService.ini)

**Comment by BogusCurry** [comment]
Thanks your both ;D
