### ISSUE TITLE
Where I found the log file from the console ?

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#187]
Hi there ;D
I am little confused, I can no more found the log file from the console messanges. Where I can found this ?

Have a nice day ;D
Bogus

**Comment by greythane** [comment]
The log files should be saved on the Data folder either as Whitecore.log, Whitecore.server.log or mono.sgen.log if you are using *nix.

**Comment by BogusCurry** [comment]
yes I use Linux, but when I deleted the log file, comes a new log file after a restart from the grid. 
Is it wanted like that ?

**Comment by emperorstarfinder** [comment]
yes when you delete the log file the server will automatically create a fresh new log file.

**Comment by BogusCurry** [comment]
Ok, only when I restart the server ...

**Comment by emperorstarfinder** [comment]
The log is always there as the server writes activity happening on the server to the log.  Thus it is always needed when the server is running.  So if you delete the log file for the WhiteCore.Server.exe or WhiteCore.exe it will create a new log file.

**Comment by BogusCurry** [comment]
The server was running, as I delete the log file .. So I think must the log file new created or ?

**Comment by emperorstarfinder** [comment]
yes if the server doesnt find the log file it will create it for you essentially the console is writing everything you see on the console in the log file makes for easier to read later when your trying to track down the cause to a problem.

**Comment by BogusCurry** [comment]
Ok, but I think is better, when I delete, that whithout restart from server a new file created. 
I know that is easy to the read the messages, that stand in the log file. But when the file is very big, so is no more easy to see what is the error or so what. I hope you understand, what I mean ;D

**Comment by greythane** [comment]
Good point...
I will look at setting up some sort of log rotation processing so that each day a new log is created, probably in a 'Logs' folder as well.  At least that way the log for each day should stay a manageable size.

**Comment by emperorstarfinder** [comment]
that is actually a very valid point perhaps have the date added to the name of the log for each day?

**Comment by BogusCurry** [comment]
I think the idea from greythane great, that is good way ;D

**Comment by BogusCurry** [comment]
That is why I love the WhiteCore-Sim, here I can talk direkt with the developer ;D And your say not we can't, you say .. maybe we can make better ;D

Thanks for that and this great Project ;D

**Comment by emperorstarfinder** [comment]
A thought I had this morning.....

Might it be less confusing for people to put the name of the server creating the log file in the name of the log file on nix to be similar to the log file names given on windows?  Example GridServer-mono.sgen.log

**Comment by greythane** [comment]
I have updated the logging as per the suggestions.  Available in current master, commit # 22fa85f4...
- Save logs in their own 'logs' folder in the 'Data' folder
- Rotate logs daily
- Name logs independently of the OS process, now correct for *nix based systems
