### ISSUE TITLE
Meshuploadflag by upload from mesh

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#188]
I would upload a mesh on my region, viewer Singularity, BS Linux x64, Ubuntu 14.04 Server. But I become the message "could not get region capbililty Meshuploadflag"

What must I doing ?

WCS is actualy gitversion

**Comment by greythane** [comment]
Is this uploading via the browser?
This message appears to indicate that the viewer is expecting a capability and it is not being found.
I have checked mesh uploading with a couple of new version viewers but not recently with Singularity.
I'll install the latest and recheck.

**Comment by emperorstarfinder** [comment]
Singularity Viewer has been out of date for a while so depending if he was using an alpha build or not the message might possibly mean that the capability it expects is either a) not supported in WCS any longer, or b) Singularity does not support the current capabilities.

Note: As of June 16, 2016 Singularity Viewer has a new release.  So might want to check with the very latest release version.

**Comment by fly-man-** [comment]
The latest version of Singularity allows uploads of Mesh items without physics. 

If you want to upload mesh with physics, use either Firestorm or another v3 viewer
