### ISSUE TITLE
[question] run WhiteCore-Sim under .Net Core ?

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#190]
Hi there ;D
Microsoft has bring a .Net version for Linux, the name is .Net Core. Now my question run WhiteCoreSim under .NetCore maybe better as under Mono ? 
http://dotnet.github.io/

**Comment by emperorstarfinder** [comment]
the .Net Framework has been open sourced by Microsoft for a little bit now.  They have partnered with Xaramin (creators of monodevelop) to make the .Net Framework hence .Net Core work on all platforms.  Mono essentially is the linux version of the .Net Framework which the mono-project is probably also involved in doing the porting as well.

**Comment by greythane** [comment]
This appears to be supported by Microsoft and very new.  Documentation is almost non-existent.
Certainly worth keeping an eye on and when time permits, I'll fire up a VM and see how it works.
