### ISSUE TITLE
[question] What mean  Load and Save with salted passwords ?

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#192]
Hello ;D
Sorry for my stupid question, but what mean with  Load and Save with salted passwords ? Salted in german is "gesalzen" so I understand salted eggs, but what is salted passwords ?

Greetings

Bogus

**Comment by emperorstarfinder** [comment]
A salted password means it has been hashed and encrypted to protect users from easily being hacked and their passwords changed on them.  AN example of this is with MD5, SHA256, SHA512 etc.
