### ISSUE TITLE
[question] What mean Refactor NodeGraph ?

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#198]
Hello ;D
I have seen, that in wcs a botmanager embeded, is this the projekt what in wcs included ?
https://github.com/lightsinthesky/react-node-graph

Greetings

Bogus

**Comment by fly-man-** [comment]
Bogus, the BotManager is a project that has been in WC for some time now and has nothing to do with the project you linked. BotManager handles the ability to manage the NPC Bots and start/stop them
