### ISSUE TITLE
run_gridmode Script is broken - solved

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#202]
I can't no more run the script run_gridmod.sh, when I start the script comes this

Starting WhiteCore GridServer...
./run_gridmode.sh: line 12: screen: command not found
Starting WhiteCore Region Simulator...
./run_gridmode.sh: line 15: screen: command not found
./run_gridmode.sh: line 17: screen: command not found

Pls fix this .. thanks ;D

Greetings

Bogus

**Comment by greythane** [comment]
This indicates that your system does not have the 'screen' program installed.
This is valid for *nix /OS X systems.
For Ubuntu or Debian based systems ( Mint, Xbuntu, Kbuntu, Wheezy etc) install using
**sudo apt-get install screen**

**Comment by BogusCurry** [comment]
ahh yes, you are right ;D
