### ISSUE TITLE
Issues by change from new estates name

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#208]
Hello ;D
I would my region change from the default estate to my own. I use the actualy version from WCS and Mono is 4.4.1 on a server under Ubuntu 14.04.4. As I make the commands comes this issues messages on the white-core-server console 

http://paste.md-5.net/xobokuruyu.avrasm 

Greetings
Bogus

**Comment by greythane** [comment]
Hi Bogus, 
Just to confirm the process...
Your region is currently 'parked' with the RealEstate owner.
You have created an estate for your user.
Change region <my region>
Change estate...  Enter user name ( and possibly estate if you have more than one)

This causes the error?

**Comment by BogusCurry** [comment]
yes so is ..

**Comment by BogusCurry** [comment]
But I will test it with a new region ...

**Comment by BogusCurry** [comment]
Ok, I have test with my local grid. They have I create a new estate with my me as owner and have change region to this new estate. And .. I have no changes. This all after a new git pull to the new version from WCS .. I am confused. 

I will test this on my server wcs grid ...
