### ISSUE TITLE
error server

### ISSUE THREAD

**Issue by LifeGold** [WhiteCoreSim/WhiteCore-Dev#210]
### Steps to reproduce

1. It happens sometimes the server itself is turned off. http://prnt.sc/bxlzh6

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Server configuration

**Operating system**: Ubuntu 14

**WhiteCore version:** 0.9.4

**Comment by greythane** [comment]
Hi LifeGold,
The error appears to be related to the ODE physics engine crashing, possibly after an asset is updated or maybe deleted?

Does this only happen when you are shutting down the server?
I notice the previous messages appear to be updating some attachment assets... would these be for an avatar and are they animated in some way?

greythane

**Comment by LifeGold** [comment]
He gives this error on and off. Writes emergency stop of the server.

**Comment by emperorstarfinder** [comment]
When this happens is the avatar logging on or off? or is the avatar teleporting from one region to another?  Because the message before the stack trace is indicating the update of avatar attachments this is likely happening when an avatar is logging on or off or during a teleport.

**Comment by LifeGold** [comment]
Happens every time in different ways. Happens when just building in the region. In the teleportation case, because of entry and exit also noticed, I can't say

**Comment by emperorstarfinder** [comment]
Other then the stack trace error, does the console provide any other errors relating to this.  (also it might help to do the set log level debug command in the console as this can help provide debugging messages not otherwise shown when the console log level is set to info).  ALso can you provide a copy of the log so we can see what is happening when the errors occur?

**Comment by LifeGold** [comment]
Yes you are right when you log a new user knocks the server

**Comment by emperorstarfinder** [comment]
When the server crashes what error is it giving?

**Comment by greythane** [comment]
Closing this as not further details have been received.
Also, this behaviour has not been reported elsewhere.
