### ISSUE TITLE
Table assets

### ISSUE THREAD

**Issue by LifeGold** [WhiteCoreSim/WhiteCore-Dev#211]
### Steps to reproduce

1. I have not watched, and then decided to go to the assets table, and saw that it was empty, very strange given the fact that the server is now about 15 regions, 140 users, and a bunch of stuff from them, as it should be? http://prntscr.com/byuy6t

### Server configuration

**Operating system**: Ubuntu 14

**WhiteCore version:** 0.9.4

**Comment by emperorstarfinder** [comment]
Assets are stored in files so this should actually not cause any issues.  By default FIleBasedAssetStorage is used to store the assets to help with quicker scene rezzing in-world.

**Comment by greythane** [comment]
Question answered
