### ISSUE TITLE
MapTiles aren't being generated for normal regions

### ISSUE THREAD

**Issue by fly-man-** [WhiteCoreSim/WhiteCore-Dev#212]
Maptiles aren't being generated the correct way, it doesn't crash the instance but the maptile isn't there and can also not be pulled by the Grid server

### Steps to reproduce

1. Use the latest version of WhiteCore
2. Setup the Grid and Region Server
3. Start the region server, error message will appear

### Expected behaviour

Maptile should be generated and should also display when the API call is done

### Actual behaviour

Error appears on the console but instance is still alive

### Server configuration

**Operating system**: Windows 7 x64 / .Net 4.5

**Web server:** None

**Database:** MySQL

**WhiteCore version:** Git Base: WhiteCore 0.9.4 (2016-07-24.a65296f)

### Logs

jul 25 01:07:54 -  [Warp3D]: Exception in the map generation, System.NullReferenceException: De objectverwijzing is niet op een exemplaar van een object ingesteld.
   bij WhiteCore.Services.SQLServices.AssetService.AssetService.Get(String id, Boolean showWarnings) in w:\GitLabHQ\WhiteCoreSim\WhiteCoreDev\WhiteCore\Services\SQLServices\AssetService\AssetService.cs:regel 137
   bij WhiteCore.Modules.WorldMap.Warp3DMap.TerrainSplat.Splat(ITerrainChannel heightmap, UUID[] textureIDs, Single[] startHeights, Single[] heightRanges, Vector3d regionPosition, IAssetService assetService, Boolean textureTerrain) in w:\GitLabHQ\WhiteCoreSim\WhiteCoreDev\WhiteCore\Modules\World\WorldMap\Warp3DMap\TerrainSplat.cs:regel 111
   bij WhiteCore.Modules.WorldMap.WarpTileRenderer.CreateTerrain(Warp3D renderer, Boolean textureTerrain) in w:\GitLabHQ\WhiteCoreSim\WhiteCoreDev\WhiteCore\Modules\World\WorldMap\WarpTileRenderer.cs:regel 397
   bij WhiteCore.Modules.WorldMap.WarpTileRenderer.TerrainBitmap(Viewport viewport, Boolean threeD) in w:\GitLabHQ\WhiteCoreSim\WhiteCoreDev\WhiteCore\Modules\World\WorldMap\WarpTileRenderer.cs:regel 202
jul 25 01:07:54 -  [MapTile generator]: Maptile generation took 718 ms

**Comment by greythane** [comment]
This appears to be a problem when caching is used due to the logic checking for valid cached assets being incorrect.

Corrected in commit #4e63f2a...

**Comment by fly-man-** [comment]
Problem has been fixed, tested and maptiles are being generated correctly again
