### ISSUE TITLE
Question: would it be feasable to port UbOde to WhiteCore?

### ISSUE THREAD

**Issue by stormsonweathers** [WhiteCoreSim/WhiteCore-Dev#224]
Hi there,
Sorry for the lack of bug reports (work got the best of me) I was wondering if there was any thought of porting UbOde to WhiteCore or if it even worth the effort? The reason Im asking is because I would be interested in porting it in my spare time if there is some interest. 

Thanks again for all the great work you've been doing!

**Comment by fly-man-** [comment]
Personal opinion: I would love to see UbODE ported for WhiteCore.

However, UbODE relies a lot on things we don't use in WhiteCore and also calls that we haven't integrated yet. Our main priority is to have a lean/stable system that doesn't eat away memory.

But as I said, feel free to see if UbODE porting is possible, do know that UB is in our IRC channel #whitecore-support regularly if you need any assistence

**Comment by stormsonweathers** [comment]
@fly-man I'll try and thanks for in input.

**Comment by BogusCurry** [comment]
What is UbODE ?

**Comment by stormsonweathers** [comment]
@boguscurry -  its a different physics engine by Avination.  

http://virtualoutworlding.blogspot.com/2015/12/2015-hg-ode-new-ubode-in-opensim-may.html?m=1

**Comment by greythane** [comment]
Storm,
The ode code the UBit has modded for OS actually does not look too different to what I did with the standard 0.13.1 ODE repo a way back. 
If you are interested I'll post that code and you can 'have a play' :)
It was working fine on OSX but I had not yet built it on Linux and the Windows builds were including additional system DLL's that it should not have...   I did not have time to pursue this at the time.

**Comment by stormsonweathers** [comment]
@greythane Thanks. When I looked at UbODEs source, i noticed they credited AuroraSim. Maybe there's hope to getting those changes ported back. Granted I know it won't be cut and dry like the AuroraSim plugins I submitted to you years ago, but a small chance is better than none! :) 👍

**Comment by greythane** [comment]
The UbODE is the ODE in the OS unmanaged libraries?  
Named "OpenDynamicsEngine-0.13.1mod" or am I  on the wrong track here?

**Comment by stormsonweathers** [comment]
@greythane - To be honest, I'm not certain since I haven't looked at the unmanaged libraries.  I was however referring to this:

https://github.com/opensim/opensim/tree/master/OpenSim/Region/PhysicsModules/ubOde

**Comment by stormsonweathers** [comment]
@greythane - Then based on your experience with the code, do you think it's worth pursuing to port UbODE or focus on the .13 code base of ODE?

**Comment by greythane** [comment]
I have just had a quick scan of the differences in the API and there are not all that many.  
The individual ODE files are a different matter as the coding design of OS is vastly different to the Aurora/WhiteCore one.  Many differences are shown but I am thinking that the actual ones may not be all that bad, just that it may take some searching to find the actual placement of a particular function/procedure. 
My approach to this would be to go through the ODE library code initially to see what updates have been made (and there are not many) and then see what impact they have on the wrapper code.

**Comment by stormsonweathers** [comment]
@greythane Will do! Again thanks for your input.

**Comment by Ana-Green** [comment]
Why not trying PhysX in OpenSim?   See https://github.com/M-O-S-E-S

Ana

**Comment by Ana-Green** [comment]
And these links   👍 
https://github.com/M-O-S-E-S/opensim
https://github.com/M-O-S-E-S/physx-wrapper
https://github.com/M-O-S-E-S/atlas

All the  best Ana
