### ISSUE TITLE
llSetParcelMusic issue

### ISSUE THREAD

**Issue by WhiteCoreWebUI** [WhiteCoreSim/WhiteCore-Dev#225]
### Steps to reproduce
1. Create a script that changes the parcel music and use it
   2.
   3.
### Expected behaviour

The music should change directly
### Actual behaviour

You have to stop the music and start it again for the new stream to play
### Server configuration

Debian 8.4

Apache

**Database:**
Mysql
**WhiteCore version:**
0.9.4 RC2
### Logs

Please make sure that WhiteCore has made an log-file and include a link to it here

**Comment by emperorstarfinder** [comment]
Which viewer are you using when this happens?  

The reason for the question is that in some viewers (older viewers such as older versions of Singularity) the actual behavior you describe is in fact normal.  In newer viewers such as the latest Firestorm version the stream will change automatically.

**Comment by WhiteCoreWebUI** [comment]
i use the latest firestorm 64 bit

**Comment by emperorstarfinder** [comment]
Okay, then the likely cause is that we have a situation where the info is in fact updating in about land but the viewer is hiccuping in the process of updating the information it receives.  

Also have you tried this using other viewers such as singularity or alchemy to see if they are producing the same problem?

**Comment by WhiteCoreWebUI** [comment]
i used the ctrlaltstudio viewer, alchemy, and kokua all same issue

**Comment by emperorstarfinder** [comment]
Okay perfect, I'll set up an instance tonight and run some tests to see what I get.  More then likely its just a case of something isn't getting to the viewer right away to tell it there has been a change.

**Comment by emperorstarfinder** [comment]
Okay I am still doing some tests on this particular issue.  Although just as a side note I have had people telling me my stream in Secondlife has been switching with delayed reaction so this could be something going on with the viewers.  I need to look into this one more.

**Comment by greythane** [comment]
The update of the new music url is set and immediatelly pushed back to any avatars (clients) currently over the effected parcel.
This does appear to be related to how and when the viewer chooses to use the new music url and not a problem in the way  the new url is being saved/updated on the servers.

**Comment by greythane** [comment]
Nothing further received regarding this and all tests appears to work correctly.
Closing this for now
