### ISSUE TITLE
Web UI map refers to google maps?

### ISSUE THREAD

**Issue by YouCanDolT** [WhiteCoreSim/WhiteCore-Dev#229]
1. Web UI map loads than writing error referring to google maps
2. Drag an avatar icon on map an it will try to load panoramic picture from google maps.

**Comment by fly-man-** [comment]
Google Maps interface is used as a layering tool for the world. Indeed it's possible to place a pin down and it will show you a Real Life place to explore.

Since the old WorldMap is based on that, I think we never took the time to change that

**Comment by greythane** [comment]
The current world map does use older Google scripting, inherited from the original Aurora codebase.
The updated WebUI, currently under development, will most likely not use any Google related scripting in preference to open source mapping.

**Comment by greythane** [comment]
The updated WebUI does not use the Google maps API and will be released shortly
