### ISSUE TITLE
map in viewer

### ISSUE THREAD

**Issue by YouCanDolT** [WhiteCoreSim/WhiteCore-Dev#231]
Windows 10
9.4 from last code update and earlier
x64 standalone

in standalone mode map in viewer always loads map from secondlife. in grid mode its ok

**Comment by emperorstarfinder** [comment]
Ahhh so this has made a reappearance to then.  You know the drill which viewers and are they the latest? :D

**Comment by YouCanDolT** [comment]
i think its in any viewer, some viewers show minimap correct but world map still from sl or blank

**Comment by fly-man-** [comment]
That means that your Viewer either isn't using the WebMAP url that Whitecore sends or that you don't have that one setup. 

And when you say Standalone mode, it's even more obvious because the MapURL doesn't get send to the viewer.

The issue has appeared in the latest Firestorm as well

**Comment by YouCanDolT** [comment]
looks ok after last update
