### ISSUE TITLE
region debug console in viewer

### ISSUE THREAD

**Issue by YouCanDolT** [WhiteCoreSim/WhiteCore-Dev#232]
When enabled is works but some commands its not possible to complete, for example when it has to have dialog like to write yes or no for change to apply or to input amount or avatar name, these parts not showing in the debug region console of viewer and making not possible to complete the action

**Comment by fly-man-** [comment]
Region Console in the viewer is a non working piece of code at the moment, the commands that are shown are hard coded in the viewer if I am correct.

In 0.9.5 we might look into those commands and if we can implement them
