### ISSUE TITLE
[Request] Ability to use own WebUI through API

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#238]
Hello ;D
Ok, the WebUI from WCS is cool, no question. But I think is the better way, make a WebUI API, so that a grid-owner make his website with Login part etc. pp. With WebUI API mean I Placeholder for the login parts or so. 

I know my englisch is very bad, but I hope you understand what I mean ;D  

Nikolausi

Have a nice Day ;D

**Comment by greythane** [comment]
The API  is now available in the latest master for testing. I will sort out some basic documentation and "how to's" in the next few days.

On the meantime, create an API key for a user with the "api promote user" command. 
Include this key in header of the request
Authorization: <your api key>

**Comment by greythane** [comment]
Additional documentation and testing to be completed but the basic API functionality is now available
