### ISSUE TITLE
How can move a Region ?

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#240]
Hello ;D

How can move a Region ?

Have a nice Day ;D

**Comment by emperorstarfinder** [comment]
you can move a region by using the update region info command.  and when it asks for region coordinates you add the new x and y coordinates after it completes then simply restart the grid and or region server and the region will be updated to its new coordinates

I can't remember if there is an exact command to just update the regions coordinates without updating the rest of the region info or not

**Comment by BogusCurry** [comment]
yes, was the command update region info ;D
