### ISSUE TITLE
Git repo for worldmap on webui from google - link inside

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#241]
Hello ;D
The worldmap on the webui is not realy good working, hier a link to the google map git repo ;D
https://github.com/googlemaps/

Have a nice Day ;D
Bogus

Founder of GridTalk.de

**Comment by fly-man-** [comment]
At the moment we're working on the WebUI so it can indeed be that the WorldMap isn't showing properly

Do remember this when you are using the HEAD / master of the repositories.

**Comment by greythane** [comment]
An updated world map is part of the new webUI that I have almost completed.
*Sorry.. delayed due to recent overseas travel but work will recommence to finish of the loose ends now.

**Comment by greythane** [comment]
Closing this as the updated world map will be released shortly (with the WebUI re-vamp)
