### ISSUE TITLE
Error messages in console from grid server after changes estate for mainland

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#243]
Hello ;D
I have found a bug, here at first the data
Server: Ubuntu Server 16.04 64 Bit, grid modus under sqlite, install since yesterday.
Last git repo version from WhiteCoreSim
One region is online ad mainland, I would make change the estate. So I have give in console change region myregion, change estate, after this ? for more options so I became estate owner, so I give my Name Bogus Curry. In the grid-server comes this error messages
http://paste.md-5.net/fibusalene.avrasm
The estate is not change in the region ..

Have a nice Day ;D

Bogus Curry | Founder of GridTalk.de and MagiCPlace grid

**Comment by emperorstarfinder** [comment]
Just to double check here as the error generally means that something does not exist i.e. nullreference

1. Did you create the estate you wanted to move the region to  Yu need to create the user, and estate before moving the region to that estate.

**Comment by BogusCurry** [comment]
I am not a Rookie, ok I have make a User with Estate .. so that it is not

**Comment by greythane** [comment]
Hi Bogus, 
Thanks for the info. I suspect there is a problem communicating the estate details between a region and the grid server.  This does ring a bell with another comment I recall that involved incorrect details of estates being returned to the region servers.
I am looking into this .

**Comment by BogusCurry** [comment]
Thanks greythane ;D

**Comment by emperorstarfinder** [comment]
Okay not about being a rookie.  It was merely asked as a question which would be asked as part of process of elimination.  Even the oldest hands can forget things.  

@greythane I do seem to remember a comment regarding the communication of estate details in IRC.  If it is the same related issue there then this might have popped back up.  I believe the last time it was when the user tried to change the estate they couldnt including parcel details.  If it is related to that seem a fix was done but I can't remember the fix off the top of my head, I would need to look at my notes.

**Comment by greythane** [comment]
I have pushed through a new update that should correct this problem (It did for my testing)
Please check it out and let me know if you still see this problem.

**Comment by BogusCurry** [comment]
Ok, thanks for the fix ;D And I will test it ;D

**Comment by BogusCurry** [comment]
I have now test in my grid, I have become not errors .. so the bug is fix ;D
