### ISSUE TITLE
[Broken] God Tools - Auto Save won't save OAR file

### ISSUE THREAD

**Issue by fly-man-** [WhiteCoreSim/WhiteCore-Dev#244]
### Steps to reproduce

1. Load a region with a space in it's name
2. Open the God Tools and click on the Auto Save function
3. Look at Region Console

### Expected behaviour

Expect to see a OAR file with autosave in it's name

### Actual behaviour

Region console gives an error that it can't find part of the path

### Server configuration

**Operating system**: Windows 7 / x64

**Web server:** Apache 2

**Database:** MySQL

**WhiteCore version:** master

### Logs

feb 17 10:22:54 - [Client]: Caught exception while processing OpenMetaverse.Packets.StateSavePacket for RealEstate Owner, Can't find part of the path W:\OpenSim-Revisions\WhiteCore\Regions\Welcome-Island\Data\Region\SaveStates\Welcome%20Island.statesave.oar.
   bij System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bij System.IO.FileStream.Init(String path, FileMode mode, FileAccess access,Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bij System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   bij System.IO.FileStream..ctor(String path, FileMode mode)
   bij WhiteCore.Modules.Archivers.ArchiveWriteRequestPreparation..ctor(IScene scene, String savePath, Guid requestId, String checkPermissions) in w:\GitLabHQ\WhiteCoreSim\WhiteCoreDev\WhiteCore\Modules\Archivers\Region\ArchiveWriteRequestPreparation.cs:regel 68
   bij WhiteCore.Modules.Archivers.ArchiverModule.ArchiveRegion(String savePath, Guid requestId, String permissions) in w:\GitLabHQ\WhiteCoreSim\WhiteCoreDev\WhiteCore\Modules\Archivers\Region\ArchiverModule.cs:regel 211
   bij WhiteCore.Modules.Archivers.ArchiverModule.HandleSaveOarConsoleCommand(String[] cmdparams) in w:\GitLabHQ\WhiteCoreSim\WhiteCoreDev\WhiteCore\Modules\Archivers\Region\ArchiverModule.cs:regel 193
   bij WhiteCore.Region.SceneManager.HandleSaveOar(IScene scene, String[] cmdparams) in w:\GitLabHQ\WhiteCoreSim\WhiteCoreDev\WhiteCore\Region\SceneManager.cs:regel 1507
   bij WhiteCore.Framework.ConsoleFramework.Commands.CommandSet.ExecuteCommand(String[] commandPath) in w:\GitLabHQ\WhiteCoreSim\WhiteCoreDev\WhiteCore\Framework\ConsoleFramework\CommandConsole.cs:regel 223
   bij WhiteCore.Framework.ConsoleFramework.Commands.CommandSet.ExecuteCommand(String[] commandPath) in w:\GitLabHQ\WhiteCoreSim\WhiteCoreDev\WhiteCore\Framework\ConsoleFramework\CommandConsole.cs:regel 276
   bij WhiteCore.Framework.ConsoleFramework.Commands.Resolve(String[] cmd) in w:\GitLabHQ\WhiteCoreSim\WhiteCoreDev\WhiteCore\Framework\ConsoleFramework\CommandConsole.cs:regel 92
   bij WhiteCore.Framework.ConsoleFramework.CommandConsole.RunCommand(String cmd) in w:\GitLabHQ\WhiteCoreSim\WhiteCoreDev\WhiteCore\Framework\ConsoleFramework\CommandConsole.cs:regel 604
   bij WhiteCore.Modules.Gods.GodModifiers.GodSaveState(IClientAPI client, UUID agentID) in w:\GitLabHQ\WhiteCoreSim\WhiteCoreDev\WhiteCore\Modules\Avatar\GodModule\GodMode.cs:regel 157
   bij WhiteCore.ClientStack.LLClientView.HandleSaveStatePacket(IClientAPI client, Packet pack) in w:\GitLabHQ\WhiteCoreSim\WhiteCoreDev\WhiteCore\ClientStack\LLClientView.cs:regel 10325
   bij WhiteCore.ClientStack.LLClientView.ProcessSpecificPacketAsync(Object state) in w:\GitLabHQ\WhiteCoreSim\WhiteCoreDev\WhiteCore\ClientStack\LLClientView.cs:regel 741

**Comment by BogusCurry** [comment]
Hello ;D
Little piece for a idea ;D If give paste in service, example https://paste.md-5.net/. So can better paste a long log from errors messages ;D

Have a nice Day ;D
Bogus

Founder from GridTalk.de
