### ISSUE TITLE
[Question] How can I change the owner from a mainland ?

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#246]
Hi there ;D
I have a region, the is a mainland. Now I will change the owner, but I becomes this message:
[Estate]: MagiCPlace is a Mainland region and is automatically part of the 'WhiteCore Mainland' estate

So my question, how can I change the owner from a mainland ?

Have a nice day ;D
Bogus

**Comment by greythane** [comment]
Hi Bogus,
Mainland regions are always owned by the 'Governor' as per SecondLife and part of the 'Mainland Estate' for maintenance purposes.
The reasoning here is that Mainland regions are designated as public access and can only be maintained by the 'Gov'.  They can still be parcelled up and re-sold to other users though in which case the new owner will have authority on their parcels.

If you want to change the mainland owner you will need to set the new name in the configuration ini's.
(Currently not working correctly, but this can also be set via the WebUI.  I am working on correcting this)

Yo can reset the region to be an Estate and then it can be owned as per normal use.

**Comment by BogusCurry** [comment]
Hi greythane ;D
I am now a little bit confused, then in the changelog to the 0.9.4, the stand this
- Mainland is owned by the Real Estate Owner , not the 'Gov'

What is now right and how I can change from mainland to a estate ?

Have a nice Day ;D
Bogus

**Comment by emperorstarfinder** [comment]
Mainland is in fact supposed to be owned by the governor.  The changelog may have just been a typo.  It does happen from time to time.

**Comment by fly-man-** [comment]
Mainland is owned by the Governor, each region that is placed on Mainland becomes property of him.

Estates are always owned by RealEstate Owner until you create a user and estate to place the region on.

**Comment by greythane** [comment]
I'm not sure if this was really answered so...

Mainland regions always belong to the Mainland estate.
If you want a region to be part of a seperate estate, you need to change the region to an 'Estate' or 'Homes'. i.e. not 'Mainland'.
Change to the region and use the 'update region info' command

Once the region is not set as 'Mainland' it can be assigned to a user estate.
