### ISSUE TITLE
[Question] Help with loading an iar

### ISSUE THREAD

**Issue by bwingler52** [WhiteCoreSim/WhiteCore-Dev#250]
I am sure i am doing something wrong, i have used opensim for years and have no problem loading iar file using the command "load iar USER NAME / PASSWORD inventory.iar"

I have put my iar in the bin folder and tried "load iar User Name /bin/file.iar inventory and several other combos like that and it never finds the file.

also tried just load iar and it ask for a user name then i hit return and it says Sorry, no archives are available.

What is the way to load an inventory.iar?

**Comment by emperorstarfinder** [comment]
on the grid server (WhiteCore.Server.sh or exe) you do load iar <First Name> <Last Name> <IAR Name>

NOTE: User password is not needed to load the IAR in WhiteCoreSim

your IAR file itself needs to be in the Data/UserArchives directory and not the bin directory.  

The correct directory is WhiteCoreSim/Data/UserArchives 

NOTE: You may need to create the UserArchives folder within the Data Directory.  Make sure your putting your iar file in the Data/UserArchives directory in the same WhiteCoreSim directory as your WhiteCore.Server.sh or WhiteCore.sh (or exe file) depending on if your in grid or standalone mode.

**Comment by bwingler52** [comment]
Thank you so much for your help it worked perfect
