### ISSUE TITLE
issue with mysql 5.6

### ISSUE THREAD

**Issue by johnfelipe** [WhiteCoreSim/WhiteCore-Dev#254]
I have MySQL-5.6 in ubuntu 14 - 64 bits i configure with robust, create user and create region, but when i try login show me this 

03:21:53 - [LLOGIN SERVICE]: Login request for felipe urrego at last using viewer 4.6.7.42398, channel Firestorm-Release, IP 190.251.131.150, Mac 7f2b6abeeeb8c6da6bf7669d0f93f09d, Id0 00000000000000000000000000000000 
03:21:53 - [PASS AUTH]: got 7e04da88cbb8cc933c7b89fbfe121cca; hashed = 04a4f84ea90ac1939896ce518bee3efb; stored = 04a4f84ea90ac1939896ce518bee3efb 
03:21:53 - Table 'opensimebim.tokens' doesn't existMySql.Data.MySqlClient.MySqlException: Table 'opensimebim.tokens' doesn't exist 
  at MySql.Data.MySqlClient.MySqlStream.ReadPacket () [0x00000]: in <filename unknown>:0 
  at MySql.Data.MySqlClient.NativeDriver.GetResult (System.Int32& affectedRow, System.Int32& insertedId) [0x00000] in <filename unknown>:0 

03:21:53 - Table 'opensimebim.tokens' doesn't existMySql.Data.MySqlClient.MySqlException: Table 'opensimebim.tokens' doesn't exist 
  at MySql.Data.MySqlClient.MySqlStream.ReadPacket () [0x00000]: in <filename unknown>:0 
  at MySql.Data.MySqlClient.NativeDriver.GetResult (System.Int32& affectedRow, System.Int32& insertedId) [0x00000] in <filename unknown>:0 

03:21:53 - [LLOGIN SERVICE]: Login failed for felipe urrego, reason: authentication failed 

How can solve that issue?

**Comment by emperorstarfinder** [comment]
Good morning,

This means the table has not been created in the database.  Is this perhaps a fresh install of WhiteCore-Sim?

If you are just starting a fresh grid the easiest way would be to delete all the tables in the database and start the server fresh.  This should properly add the tables in the database which should resolve the issue.

If this is not a brand new installation the tables can be created manually.  If needed I can provide manual SQL files that you could import into the database for each table that is missing.

Hope this helps

**Comment by johnfelipe** [comment]
Bro can u share cheatsheet for install grid instance with robust instance?

**Comment by emperorstarfinder** [comment]
To run a grid using WhiteCore-Sim you need to first run 

WhiteCore.Server.sh (for Linux/ Mac OS)
WhiteCore.Server.exe (For Windows)

let it do the initial configuration and answer any questions asked.

Upon initial configuration type run configurator in the WhiteCore.Server console

This will ask you a set of questions to answer.  The questions will be pretty self explanatory.  The WhiteCore.Server should use the MySQL database server option in grid mode.  (MariaDB server will also work and is lighter weight in Linux.)

After this is configured creation of users and estates via the console are done in WhiteCore.Server

The same process is followed for the region server (WhiteCore.sh for Linux/ Mac OS or WhiteCore.exe for Windows).  

You need to make sure the grid server url is the same in both the grid server and the region server i.e. 127.0.0.1:8002

You will also find documentation in the WhiteCoreSim/WhiteCoreDocs folder.

I hope this helps a bit.

**Comment by johnfelipe** [comment]
What is comparison with opensim officiall?

**Comment by johnfelipe** [comment]
I need to know if this version is better of official opensim

**Comment by emperorstarfinder** [comment]
"I need to know if this version is better of official opensim"

Allow me to respond to your question using an example.  When purchasing a car or truck would you go to Dealer A and ask "Is your car or truck better then one sold at Dealership B?"  

No of course you wouln't ask that question at a car dealership.  The reason is they are going to be biased and respond "Oh yes our car or truck is better then the ones at Dealer B."  The reason is because they want to sell you a product and that vehicle may not necessarily be the best for what you need.

Likewise it would be the same for your question.  A core developer is likely to be biased in wanting to see you use their software over another and will always say yes our software is better then another software program that does the same thing.  The better question to ask here would be:

"What makes WhiteCore-Sim better for me then Opensim?"

Answering this question is really going to depend on what your needs are and what your looking to do.  Just like a car or truck has their pros and cons, so to does WhiteCore-Sim and Opensim.

**Comment by johnfelipe** [comment]
First support is better with you whitecoresim is first respond, core of
opensim is not responding my questions, but my needs is about show 3d
architecture model with immersive component, your software is good for that?

**Comment by emperorstarfinder** [comment]
I think you will have to elaborate on what you mean by 3D modeling.  If you mean mesh models then yes mesh is supported.  if you mean a virtual reality device, that is more of a viewer side issue.  Remember just like all software programs WhiteCore-Sim will have its limitations.

I don't own WhiteCore-Sim and am not a core developer on their team.  I just help them out sometimes on things when needed.

**Comment by johnfelipe** [comment]
Tnks for u time and answer I appreciate that, yes is for real estate
projects we have two buildings modelling in a software and can export to
dae, obj and other file extensions is possible then?

**Comment by emperorstarfinder** [comment]
That would be correct support for .dae and .obj is supported.  however to import your mesh model in-world its recommended that you use the .dae file format.

**Comment by johnfelipe** [comment]
I will install this software in Ubuntu tomorrow and let u know my progress,
tnks a lot

**Comment by greythane** [comment]
Hi Felipe,
I am currently travelling overseas and am unable to answer your question
fully but I do see that Emperor... Has answered most if your questions at
present.
A quick check of your error message reveals that it looks like you are
trying to use an Opensim instance with (maybe) a WhiteCore database? The
error relates to a missing table referencing opensim tokens used for
authentication.

I will be back in a few days and will be happy to assist getting you setup.

Also,  you can check out http://whitecore-sim.org for information and some
tutorials.

Greythane
