### ISSUE TITLE
cheatsheet for grid and mysql instance

### ISSUE THREAD

**Issue by johnfelipe** [WhiteCoreSim/WhiteCore-Dev#257]
Hi bro this is my cheatsheet but is not currently working

https://gist.github.com/johnfelipe/e718beb9887309db8964e1444bf90020

I dont know when put user, pwd and database in mysql 5.6 instance

Pls help me with this

**Comment by emperorstarfinder** [comment]
When you answer the questions it asks it will insert the username info into the db.

You can set the database instance used manually via the Data.ini files and editing the appropriate ini file for the database type.  

For MySQL (all versions) use edit:

Grid = Config/Grid/ServerConfiguration/Data/Data.ini
Grid = Config/Grid/ServerConfiguration/Data/MySQL.ini

Standalone (sim) = Config/Sim/Data/Data.ini
Standalone (sim) = Config/Sim/Data/MySQL.ini

Additionally you can also set this via the run configurator command in the console for both WhiteCore.Server.exe and WhiteCore.exe  

Just be sure you know the DB_USERNAME; DB_PASSWORD; DB_NAME; for the database along with the url to the database server.

Pretty simple though which is one of the many better benefits of Whitecore over Opensim

**Comment by johnfelipe** [comment]
https://github.com/WhiteCoreSim/WhiteCore-Dev/issues/254#issuecomment-299694155

i dont understand this

"let it do the initial configuration and answer any questions asked.

Upon initial configuration type run configurator in the WhiteCore.Server console"

Pls put me like command line

Tnks

**Comment by emperorstarfinder** [comment]
initial configuration is what allows it to configure the basic configuration settings and run out of the box.

By running the run configurator command you can reconfigure the basic configurations it uses such as whether it will run in grid or standalone mode, what database service to use such as SQLite or MySQL, the name of your grid, the url or ip of your grid or region server, etc. 

By using this command and answering the questions it will configure the necessary files for you to initially get it running in the mode you want.

When it runs out of the box it will ask you basic questions to get you started.  Then when it gives the startup completed message on the console you can run the run configurator command if you want to update the basic configurations it is using.

**Comment by johnfelipe** [comment]
Hi bro then run configurator command is configurator or what is exact
command?

**Comment by emperorstarfinder** [comment]
Good afternoon,

The command to run the configurator is:

run configurator

when you use that command you will be asked if you want to run the configurator.  Just say yes if you wish to run the configurator.

**Comment by johnfelipe** [comment]
git clone --recursive https://github.com/WhiteCoreSim/WhiteCore-Dev.git
	cd WhiteCore-Dev/

	./runprebuild.sh

	x64 architecture found
	Architecture to use? (x86, x64) [x64]: x64
	Configuration? (Release, Debug) [Debug]: Release
	Build immediately? (Yes, No) [No]: Yes

then first time show me this:

	10 Warning(s)
			 0 Error(s)

	Time Elapsed 00:00:50.9437630
	Finished Building WhiteCore
	Thank you for choosing WhiteCore-Sim
	Please report any errors to our Github Issue Tracker https://github.com/WhiteCoreSim/WhiteCore-Dev/issues

Today show me this

			 88 Warning(s)
			 0 Error(s)

	Time Elapsed 00:00:27.7397360
	Finished Building WhiteCore
	Thank you for choosing WhiteCore-Sim
	Please report any errors to our Github Issue Tracker https://github.com/WhiteCoreSim/WhiteCore-Dev/issues
	
That is normal?

then i do this

	nano /home/felipe/WhiteCore-Dev/WhiteCoreSim/Config/Sim/Main.ini
	
comment standalonecommon and comment out gridcommon:
	
	##
	;;If you would like to use WhiteCore in standalone mode , select this file.
	Include-Standalone = Sim/Standalone/StandaloneCommon.ini

	To 

	;;If you would like to use WhiteCore in standalone mode , select this file.
	;Include-Standalone = Sim/Standalone/StandaloneCommon.ini

	Y

	;;If you would like to use WhiteCore in grid mode, select this file.
	;Include-Grid = Sim/Grid/GridCommon.ini

	To

	;;If you would like to use WhiteCore in grid mode, select this file.
	Include-Grid = Sim/Grid/GridCommon.ini
	##

	cd WhiteCoreSim/bin/
	./WhiteCore.Server.sh


	Grid owner user name (? for suggestion) [Spamfast Spamfast]: felipe urrego
	Password: xxxx
	Re-enter Password: xxxxxx
	Email for password recovery. ('none' if unknown) [none]: ingenierofelipeurrego@gmail.com
	Required avatar UUID (optional)) [c819b66b-6e1f-4235-8290-e04ebf60d3f4]: enter
	Estate name [Owner's Estate]: Myestate
	
An show me this error:

	........May 13 01:30:27 - [Application]:
	Application exception detected
	Exception: System.NullReferenceException: Object reference not set to an instance of an object
	  at System.Threading.EventWaitHandle.Reset () [0x00000] in <filename unknown>:0
	  at (wrapper remoting-invoke-with-check) System.Threading.EventWaitHandle:Reset ()
	  at System.Threading.Timer+Scheduler.SchedulerThread () [0x00000] in <filename unknown>:0
	  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0
	Application is terminating: True
	[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
	  at System.Threading.EventWaitHandle.Reset () [0x00000] in <filename unknown>:0
	  at (wrapper remoting-invoke-with-check) System.Threading.EventWaitHandle:Reset ()
	  at System.Threading.Timer+Scheduler.SchedulerThread () [0x00000] in <filename unknown>:0
	  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0

what step i wrong?

**Comment by emperorstarfinder** [comment]
The best thing to do would be as follows:

1. Start with a fresh copy of WhiteCore-Sim (do not edit the configuration files)
2. In WhiteCore.Server.exe you will be asked for the name of the grid owner and the name of the owners estate, provide the names for each of these two questions
3. Upon WhiteCore.Server.exe giving you the message that startup has completed type: run configurator and hit enter.
4. You will be asked if you want to proceed with the configurator, answer yes
5. Answer the questions it will ask you:
   a. Database Service 
   b. DB Name
   c. DB Username
   d. DB User Password
   e. URL to Database Server
   f. Grid name
   g. Grid URL
   h. etc.
6. The configurator will edit the necessary configuration files for you.
7. When it asks you to restart the server type: shutdown
8. It will ask you if you want to shut down, answer yes
9. When shutdown is complete the console will close.  Simply relaunch WhiteCore.Server.exe and it will be configured with the basic settings to get your grid server running.
10. For the region server (WhiteCore.exe) you will do the same as above.  The region server you can leave the default database service and File storage as the region handles the storage for this. As above after you do the run configurator command and answer the questions it will edit the necessary configuration files and ask you to restart the instance.  

This would be the better way to get your configuration started.  It will take care of the basic configurations based on your answers to the questions it asks and will write out the neccessary info into the configuration files.

Once you have this working always keep a backup of the Config directory in case you need it down the road.

Hope that helps a bit.

**Comment by johnfelipe** [comment]
is normal do this 2 times?

> ./WhiteCore.Server.sh


	Grid owner user name (? for suggestion) [Spamfast Spamfast]: felipe urrego
	Password: xxx
	Re-enter Password: xxxx
	Email for password recovery. ('none' if unknown) [none]: ingenierofelipeurrego@gmail.com
	Required avatar UUID (optional)) [c819b66b-6e1f-4235-8290-e04ebf60d3f4]: enter
	Estate name [Owner's Estate]: Myestate

**Comment by emperorstarfinder** [comment]
yes because on initial run your using the built in SQLite Database so when you do the run configurator command and choose MySQL it has to configure it to use MySQL (or MariaDB) and add the user and estate into the database.

**Comment by johnfelipe** [comment]
Done, im trying with user different to root in mysql 5.7, but not working, in priviligies im using all, how can fix that?

**Comment by emperorstarfinder** [comment]
you can use this script on your MySQL Server:

CREATE USER 'whitecore'@'%' IDENTIFIED BY '<insert password here>';
CREATE DATABASE IF NOT EXISTS `whitecore` ;
GRANT ALL PRIVILEGES ON `whitecore` . * TO 'whitecore'@'%';

Replace whitecore with the name of the database and username you assigned to the database and replace <insert password here> with the password for the user.  That should resolve it.  if there are no errors then its sorted something that you missed when creating the user in the DB server itself.  If that doesn't work let me know and ill try to provide more help.

**Comment by johnfelipe** [comment]
i run your script and with phpmyadmin view in this form:
![users](https://cloud.githubusercontent.com/assets/428820/26138760/08a7cb20-3a91-11e7-954a-916b1a406be9.png)

when i run for second time:

>./WhiteCore.Server.sh

![issuemysql](https://cloud.githubusercontent.com/assets/428820/26138779/256f5ac0-3a91-11e7-9f9f-a169ec5569b2.png)

when i edit this with root user:

`/home/felipe/WhiteCore-Dev/WhiteCoreSim/Config/Grid/ServerConfiguration/Data/MySQL.ini`

run perfectly, this is my version:
![phpmyadmin](https://cloud.githubusercontent.com/assets/428820/26138832/8cc31b44-3a91-11e7-8cbc-5934a9350e0b.png)

**Comment by emperorstarfinder** [comment]
In many cases a reboot will fix this.  ALso be sure you have port 3306 open in your firewalls (both machine and in your modem/ router)

**Comment by johnfelipe** [comment]
i reboot 2 times
i check iptables and show me this

	felipe@gtic:~$ sudo iptables -S
	-P INPUT ACCEPT
	-P FORWARD ACCEPT
	-P OUTPUT ACCEPT
	-N syn-flood

i think put only root user of mysql is not a good idea

**Comment by johnfelipe** [comment]
![mysqlissue](https://cloud.githubusercontent.com/assets/428820/26145854/a6f53a8e-3ab3-11e7-931b-18f539faeab0.png)

**Comment by emperorstarfinder** [comment]
Lets first check the status of the mysql server by opening a terminal and doing:

systemctl status mysql.service

If the MySQL server is running we should see something similar to this in the output:

● mysql.service - MySQL Community Server
   Loaded: loaded (/lib/systemd/system/mysql.service; enabled; vendor preset: en
   Active: active (running) since Wed 2016-11-23 21:21:25 UTC; 30min ago
 Main PID: 3754 (mysqld)
    Tasks: 28
   Memory: 142.3M
      CPU: 1.994s
   CGroup: /system.slice/mysql.service
           └─3754 /usr/sbin/mysqld

If we don't see something similar to that then we know that we need to actually start the server with the following command:

sudo systemctl mysql start

As an additional check you can also do:

mysqladmin -p -u root version

If all is good we should see something similar to this in output:

mysqladmin  Ver 8.42 Distrib 5.7.16, for Linux on x86_64
Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Server version      5.7.16-0ubuntu0.16.04.1
Protocol version    10
Connection      Localhost via UNIX socket
UNIX socket     /var/run/mysqld/mysqld.sock
Uptime:         30 min 54 sec

Threads: 1  Questions: 12  Slow queries: 0  Opens: 115  Flush tables: 1  Open tables: 34  Queries per second avg: 0.006

The message may also mean you have not put the right info into the corresponding MySQL.ini file.

**Comment by johnfelipe** [comment]
im using https://github.com/lj2007331/lnmp

	felipe@gtic:~$ sudo service mysqld status
	 * MySQL running (2009)

for second command

	felipe@gtic:~$ mysqladmin -p -u root version
	Enter password:
	mysqladmin  Ver 8.42 Distrib 5.7.18, for linux-glibc2.5 on x86_64
	Copyright (c) 2000, 2017, Oracle and/or its affiliates. All rights reserved.

	Oracle is a registered trademark of Oracle Corporation and/or its
	affiliates. Other names may be trademarks of their respective
	owners.

	Server version          5.7.18-log
	Protocol version        10
	Connection              Localhost via UNIX socket
	UNIX socket             /tmp/mysql.sock
	Uptime:                 35 min 8 sec

	Threads: 1  Questions: 108  Slow queries: 0  Opens: 118  Flush tables: 1  Open tables: 72  Queries per second avg: 0.051

then all is up and running

**Comment by emperorstarfinder** [comment]
Did you run the builtin security script for MySQL?

sudo mysql_secure_installation

**Comment by johnfelipe** [comment]
Yes bro
http://200.122.209.133
phpMyAdmin Is perfectly installed

**Comment by emperorstarfinder** [comment]
Hmmm.

I think it is time I do a video for you that shows how to set up WhiteCore.  Unfortunately I only speak english but I will do that today using a fresh install of Linux.  That might be easier.

**Comment by johnfelipe** [comment]
Pls do it with https://github.com/lj2007331/lnmp, I will appreciate
Tnks

El 17 may. 2017 5:26 a. m., "Emperor Starfinder" <notifications@github.com>
escribió:

Hmmm.

I think it is time I do a video for you that shows how to set up WhiteCore.
Unfortunately I only speak english but I will do that today using a fresh
install of Linux. That might be easier.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/WhiteCoreSim/WhiteCore-Dev/issues/257#issuecomment-302050218>,
or mute the thread

**Comment by emperorstarfinder** [comment]
To run WhiteCore you really don't need that you just need basics like Mono and MySQL (MariaDB) for a grid setup.  WhiteCoreSim has its own builtin web interface.  However setup won't really be that much different with that repo though I have not tested whether there might be a conflict with whats in that Repo.  I will need to do some testing with that.

**Comment by johnfelipe** [comment]
But I have only one server with that lnmp, I install opensim 0.8 and it
works but I see potential in this version, or if u need I can send you
privately credentials of that server. Stay alert.

**Comment by emperorstarfinder** [comment]
@johnfelipe I will have to wait until tonight to finish recording the video.  After which I need to run it through to make sure it all recorded and looks good.  I have not forgotten though.  Should have it done by morning though.

**Comment by johnfelipe** [comment]
@emperorstarfinder do u want or need credential for my ubuntu 14.04/64 bits with lnmp?

**Comment by greythane** [comment]
I'm not sure what the status of your setup is as this conversation has quite a few twists etc but...

WhiteCore will run 'out of the box' when compiled from source.
For a grid setup
Build WhiteCore using the "runprebuild.sh" our "autobuild.sh".  (Warnings are OK, errors are not)  

(Assuming you have MySqlMariaDB up and running)
 - create the database 'whitecore'
 - create the user that will access the white core data 
  (default is white core, whitecorepass but you should change these for better security)
- grant all privileges to your white core user to the white core database

Configuration for grid mode operation (default is setup for standalone)
Edit WhiteCoreSim/Config/Sim/Main.ini 
 - comment standalone includes and uncomment grid includes line

Edit WhiteCoreSim/Config/Grid/ServerConfiguration/Data/Data.ini
 - comment the "Include-SQLite" line
 - uncomment the "Include-MySQL" line

Edit WhiteCoreSim/Config/Grid/ServerConfiguration/Data/MySQL.ini
 - change the datasource, username and password to suit your installation

First run
To initialise the database initially run the grid server only using "grid_console.sh"
Some initial details are requested for the grid owner user account and end at the 'root' prompt

You can now run the region server to create regions and upload OARS etc.

**Comment by johnfelipe** [comment]
Hi with grid_console.sh works with different user, but not finish with root prompt, finish with WhiteCore.Server #

I can `run configurator` for complete configuration?, for set 

	Name of your WhiteCore-Sim server: [WhiteCore-Sim]
	Ebim-Sim
	Enter your 'Welcome Message' that each user will see during login
	  (putting <USERNAME> into the welcome message will insert the user's name)
	Welcome Message: [Welcome to ebim-sim, <USERNAME>!]
	Bienvenido a ebim-sim, <USERNAME>!
	Accounts can be created automatically when users log in for the first time.
	  (This means you don't have to create all accounts manually using the console or web interface)
	Create accounts automatically?: [true]
	true
	Which asset service do you want to use?
	[1] File based
	[2] SQL
	Choose 1 or 2: [1]
	1

or how can do that?

**Comment by emperorstarfinder** [comment]
Pretty simple just run the run configurator command.  It works both in WhiteCore.Server and WhiteCore consoles.  You will see the WhiteCore.Server in the WhiteCore.Server.exe (or .sh) instead of root because it is intended to be the grid server.  The region server in grid mode is WhiteCore.exe (or .sh).

**Comment by greythane** [comment]
There are multiple references to this in other issues so closing to avoid confusion of the current status
