### ISSUE TITLE
world map is not working

### ISSUE THREAD

**Issue by johnfelipe** [WhiteCoreSim/WhiteCore-Dev#258]
http://200.122.209.133:8002/
![worldmap](https://cloud.githubusercontent.com/assets/428820/26028647/b8966aae-37ea-11e7-86ad-7508c5fda299.png)

**Comment by johnfelipe** [comment]
im using nginx and php 7.1

http://200.122.209.133/phpinfo.php

**Comment by fly-man-** [comment]
Currently the WorldMap isn't working anymore as the API that we use from Google has been deprecated. 

There's a new WorldMap in the making but for the time being it's broken,
