### ISSUE TITLE
where and how load iar and oar files

### ISSUE THREAD

**Issue by johnfelipe** [WhiteCoreSim/WhiteCore-Dev#261]
root: # change region ebim1

	ebim1: # load oar balistica.oar

and this error show me

>May 13 03:00:59 - [Error]: The file 'balistica.oar' cannot be found.

and that file is in here

`/home/felipe/WhiteCore-Dev/WhiteCoreSim/bin/balistica.oar`

**Comment by emperorstarfinder** [comment]
If your running in grid mode then on WhiteCore.Server.exe for IARS:

load iar <USERNAME> <IAR NAME> you will be asked if you want to create a new directory or merge.  either choice should work.

for OAR: on WhiteCore.exe:

if you have multiple regions on the instance you need to change to the region you want to load the oar for.  the command would be change region <REGIONNAME>

then:

load oar OARNAME.oar (or .tgz if it is a tar gz file)

If your just running in standalone then the commands would be done on WhiteCore.exe

**Comment by johnfelipe** [comment]
![loadoar](https://cloud.githubusercontent.com/assets/428820/26090558/67080912-39cb-11e7-89a8-cc18f38f1d7a.png)

Is not working

**Comment by emperorstarfinder** [comment]
Good Morning,

You need to put the OAR files in WhiteCoreSim/Data/OARFiles

You need to put the IAR files in WhiteCoreSim/Data/UserArchives (you may need to do the save iar firstname lastname iarname for it to create the folder for you.)

**Comment by johnfelipe** [comment]
![oar](https://cloud.githubusercontent.com/assets/428820/26139559/2ceb8048-3a97-11e7-94b7-58fe173ba38e.png)

run `load oar balistica.oar` and show me this:

![missed](https://cloud.githubusercontent.com/assets/428820/26139566/45be13ce-3a97-11e7-8263-507a8225eeff.png)

i need owner or perms?

**Comment by johnfelipe** [comment]
ohh but i run in 
>./WhiteCore.sh

Sorry my bad..

but show me this error:

	May 17 12:30:56 - [Application]:
	Application exception detected
	Exception: System.NullReferenceException: Object reference not set to an instance of an object
	  at (wrapper unknown) System.Threading.Monitor:FastMonitorEnterV4 (object,bool&)
	  at System.Threading.Timer+Scheduler.SchedulerThread () [0x00000] in <filename unknown>:0
	  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0
	Application is terminating: True
	WhiteCore.Server # [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
	  at (wrapper unknown) System.Threading.Monitor:FastMonitorEnterV4 (object,bool&)
	  at System.Threading.Timer+Scheduler.SchedulerThread () [0x00000] in <filename unknown>:0
	  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0

**Comment by emperorstarfinder** [comment]
That simply could just be because you got the name of the OAR file wrong or it couldnt find the file because it needs to be in the correct folder.
