### ISSUE TITLE
error loading an oar file

### ISSUE THREAD

**Issue by johnfelipe** [WhiteCoreSim/WhiteCore-Dev#262]
ebim1: # load oar /home/felipe/WhiteCore-Dev/WhiteCoreSim/bin/balistica.oar
	May 16 12:06:40 - [Archiver]: Loading archive to region ebim1 from /home/felipe/WhiteCore-Dev/WhiteCoreSim/bin/balistica.oar
	May 16 12:06:40 - [Archiver]: Clearing all existing scene objects
	May 16 12:06:40 - [Archiver]: Cleared all existing scene objects in 0:0
	May 16 12:06:40 - [Archiver]: Commencing load from archive
	May 16 12:06:40 - [Terrain]: File (terrains/balistica.r32) loaded successfully
	.......... [Archiver]: Found 100 scene object groups...
	.......... [Archiver]: Found 200 scene object groups...
	.......... [Archiver]: Found 300 scene object groups...
	.......... [Archiver]: Found 400 scene object groups...
	.......... [Archiver]: Found 500 scene object groups...
	.......... [Archiver]: Found 600 scene object groups...
	.......... [Archiver]: Found 700 scene object groups...
	.......... [Archiver]: Found 800 scene object groups...
	.......... [Archiver]: Found 900 scene object groups...
	.......... [Archiver]: Found 1000 scene object groups...
	.......... [Archiver]: Found 1100 scene object groups...
	.......... [Archiver]: Found 1200 scene object groups...
	.......... [Archiver]: Found 1300 scene object groups...
	.......... [Archiver]: Found 1400 scene object groups...
	.......... [Archiver]: Found 1500 scene object groups...
	.......... [Archiver]: Found 1600 scene object groups...
	.......... [Archiver]: Found 1700 scene object groups...
	.......... [Archiver]: Found 1800 scene object groups...
	.......... [Archiver]: Found 1900 scene object groups...
	.......... [Archiver]: Found 2000 scene object groups...
	.......... [Archiver]: Found 2100 scene object groups...
	.......... [Archiver]: Found 2200 scene object groups...
	.............. [Archiver]: Loaded 100 assets, with 0 failures...
	......Stacktrace:

	Native stacktrace:

	./WhiteCore.sh: line 1: 35229 Segmentation fault      (core dumped) mono --debug WhiteCore.exe

whats wrong?

**Comment by johnfelipe** [comment]
when i want restart all show me:

	May 16 12:10:59 - ====================================================================
	May 16 12:10:59 - ==================== Starting WhiteCore-Sim (x64) ======================
	May 16 12:10:59 - ====================================================================
	May 16 12:10:59 - [WhiteCore-Sim Startup]: Version : WhiteCore 0.9.5 Development
	May 16 12:10:59 - [WhiteCore-Sim Startup]: Git Base: WhiteCore 0.9.5 (2017-04-09.d721032)
	May 16 12:10:59 - [WhiteCore-Sim Startup]: Running on 64 bit architecture
	May 16 12:10:59 - [WhiteCore-Sim Startup]: Allocated RAM 47808512
	May 16 12:10:59 - [WhiteCore-Sim Startup]: Physical RAM (Mbytes): 8157
	May 16 12:10:59 - [Network]: Retrieving the external IP address
	May 16 12:11:05 - [Network]: Network IP address has been set to 200.122.209.133
	May 16 12:11:05 - [Base HTTP server]: Starting HTTP server on port 9000
	May 16 12:11:05 - [Email]: Email enabled for Local only
	May 16 12:11:05 - [Flotsam asset cache]: Cache Directory '../Data/AssetCache/flotsam'
	May 16 12:11:05 - [Filebased asset service]: File based asset service enabled
	May 16 12:11:05 - [Filebased asset service]: Set up Filebased Assets in ../Data/FileAssets.
	May 16 12:11:05 - Retrieving region data from: ../Data/Region
	May 16 12:11:05 - Region archives saved to:    ../Data/RegionBak
	**Region Name (? for suggestion) []:**

**Comment by fly-man-** [comment]
Looks like you didn't have enough memory to load the OAR file. Have you tried enlarging the memory to the process ?

**Comment by johnfelipe** [comment]
>Physical RAM (Mbytes): 8157

How much memory i need?

**Comment by emperorstarfinder** [comment]
your physical RAM is fine.  This is more likely a bug in mono which is causing mono to eat up its memory.  I am setting up a shell script with instructions to add it to your cron jobs in linux which will fix that.  It has happened to my grid and we had to do this to get things going correctly.

**Comment by johnfelipe** [comment]
new error trying load balistica.oar
![balistica](https://cloud.githubusercontent.com/assets/428820/26146303/4e071788-3ab5-11e7-893a-ac022ca8039e.png)



	ebim1: # load oar balistica.oar
	May 17 03:58:05 - [Archiver]: Loading archive to region ebim1 from ../Data/OarFiles/balistica.oar
	May 17 03:58:05 - [Archiver]: Clearing all existing scene objects
	May 17 03:58:05 - [Archiver]: Cleared all existing scene objects in 0:0
	May 17 03:58:05 - [Archiver]: Commencing load from archive
	May 17 03:58:05 - [Terrain]: File (terrains/balistica.r32) loaded successfully
	.......... [Archiver]: Found 100 scene object groups...
	.......... [Archiver]: Found 200 scene object groups...
	.......... [Archiver]: Found 300 scene object groups...
	.......... [Archiver]: Found 400 scene object groups...
	.......... [Archiver]: Found 500 scene object groups...
	.......... [Archiver]: Found 600 scene object groups...
	.......... [Archiver]: Found 700 scene object groups...
	.......... [Archiver]: Found 800 scene object groups...
	.......... [Archiver]: Found 900 scene object groups...
	.......... [Archiver]: Found 1000 scene object groups...
	.......... [Archiver]: Found 1100 scene object groups...
	.......... [Archiver]: Found 1200 scene object groups...
	.......... [Archiver]: Found 1300 scene object groups...
	.......... [Archiver]: Found 1400 scene object groups...
	.......... [Archiver]: Found 1500 scene object groups...
	.......... [Archiver]: Found 1600 scene object groups...
	.......... [Archiver]: Found 1700 scene object groups...
	.......... [Archiver]: Found 1800 scene object groups...
	.......... [Archiver]: Found 1900 scene object groups...
	.......... [Archiver]: Found 2000 scene object groups...
	.......... [Archiver]: Found 2100 scene object groups...
	.......... [Archiver]: Found 2200 scene object groups...
	..........Stacktrace:


	Native stacktrace:

	./WhiteCore.sh: line 1:  3735 Segmentation fault      (core dumped) mono --debug WhiteCore.exe

**Comment by johnfelipe** [comment]
when i try restart all services

>screen -r Sim

![suggestion](https://cloud.githubusercontent.com/assets/428820/26146454/db2ea1a8-3ab5-11e7-946b-3481592beb8b.png)

Put me again for create a new region, how can fix that?
https://github.com/WhiteCoreSim/WhiteCore-Dev/issues/264#issue-229243058

stay alert

**Comment by emperorstarfinder** [comment]
That would mean that its not seeing a region created.  If you look in your WhiteCoreSim/Data/Region folder you likely will see a region was not created.  So therefore just go forward and create the region.  If it claims there is already a region at those coordinates then you will want to check the EstateRegions,  Grid Region tables in your database to see if a region actually exists

**Comment by johnfelipe** [comment]
if i put same information is already there

	Region Name (? for suggestion) []: ebim1
	Region Location X [1000]:
	Region location Y [1000]:
	Region size X [256]:
	Region size Y [256]:
	Region Type (Mainland / Estate / Homes) [Estate]: Homes
	Estate region type?, Options are [Full Region] [Full Region]:
	Terrain Type?, Options are [Flatland, Grassland, Hills, Mountainous, Island, Swamp, Aquatic] [Grassland]:
	May 17 12:35:03 - [SceneManager]: Starting region "ebim1" at @ 1000,1000
	May 17 12:35:04 - [ODE Physics]: Selected engine -> Open Dynamics
	May 17 12:35:04 - [RegisterRegionWithGrid]: Registration of region ebim1 with the grid failed - The region location you specified is already in use. You must move your region.

**Comment by johnfelipe** [comment]
can we share my screen to you via skype or hangout?

**Comment by BogusCurry** [comment]
Hi there ;D
Which mono version use you ? Is there oar save with wcs or in opensim ? And which BS use you ? Linux or Windows

Greetings
Bogus

**Comment by johnfelipe** [comment]
felipe@gtic:~$ mono --version
Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-4ubuntu1.1)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen

Is there oar save with wcs or in opensim? is saved with opensim
which BS use you ? what is BS?
Linux or Windows, ubuntu 14.04

**Comment by greythane** [comment]
Hi,
Unless there has been some recent updates of OpenSim OAR format that I am not aware of, WhiteCore can load OpenSim OARS without problems.

Mono 3.2.8 is rather old now with the current version being 4.2 and V5 just around the corner.
I would suggest you update your mono install and retry this first.

**Comment by johnfelipe** [comment]
Ok bro I will reinstall all with mono 4 and let u know

El 17 may. 2017 17:16, "Rowan Deppeler" <notifications@github.com> escribió:

Hi,
Unless there has been some recent updates of OpenSim OAR format that I am
not aware of, WhiteCore can load OpenSim OARS without problems.

Mono 3.2.8 is rather old now with the current version being 4.2 and V5 just
around the corner.
I would suggest you update your mono install and retry this first.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/WhiteCoreSim/WhiteCore-Dev/issues/262#issuecomment-302246953>,
or mute the thread

**Comment by emperorstarfinder** [comment]
Now that I know your using Ubuntu 14.04 LTS with Mono 3.8 you might want to consider upgrading to Ubuntu 16.04.2 LTS with latest mono.  That way youll have the most current software.

**Comment by johnfelipe** [comment]
now is working and can load my balisitca.oar
https://github.com/WhiteCoreSim/WhiteCore-Dev/issues/257#issuecomment-302253465
