### ISSUE TITLE
configuration questions

### ISSUE THREAD

**Issue by johnfelipe** [WhiteCoreSim/WhiteCore-Dev#265]
hi again i use this https://github.com/WhiteCoreSim/WhiteCore-Dev/issues/257#issuecomment-302253465, and all working now but i have few questions:

- If i not use run configurator is a method for fill other things like

	Name of your WhiteCore-Sim server: [WhiteCore-Sim]
	Ebim-Sim

this to

	Enter your 'Welcome Message' that each user will see during login
	  (putting <USERNAME> into the welcome message will insert the user's name)
	Welcome Message: [Welcome to ebim-sim, <USERNAME>!]
	Bienvenido a ebim-sim, <USERNAME>!

this to

	Accounts can be created automatically when users log in for the first time.
	  (This means you don't have to create all accounts manually using the console or web interface)
	Create accounts automatically?: [true]

this to

	Which asset service do you want to use?
	[1] File based
	[2] SQL
	Choose 1 or 2: [1]

- i need set to Estate name [Owner's Estate]:, where do that all this things

**Comment by emperorstarfinder** [comment]
Owners Estate you create when it asks you for that on the console.

Aside from the basic configurations that the run configurator command will do the only other way to adjust configurations is manually in the files in the Config folder.  However for most users the basic configuration is enough which again this will all depend on your needs.

**Comment by johnfelipe** [comment]
I only need path and name of file for config manually this items in grid instance:

- Name of your WhiteCore-Sim server

- Welcome Message

- Accounts can be created automatically when users log in for the first time

- Which asset service do you want to use?

Tnks

**Comment by greythane** [comment]
Hi johnfelipe,
Assuming you are using a grid setup...  
(All files in Config/Grid/ServerConfiguration )

- Name of the server - GridInfoService.ini >> grid name & gridlock
- Welcome message - Login.ini  >> WelcomeMessage
- Auto create accounts - Login.ini  >> AllowAnomyousLogin
- Asset service - Data/Data.ini >> AssetHandler

**Comment by johnfelipe** [comment]
nano /home/felipe/WhiteCore-Dev/WhiteCoreSim/Config/Grid/ServerConfiguration/GridInfoService.ini
	 
	##
	;; long grid name: the long name of your grid
	gridname = "Nuestro Mundo Virtual E-BIM"
	 
	;; short grid name: the short name of your grid
	gridnick = "EBIMSim"
	 
	##
	 
	nano /home/felipe/WhiteCore-Dev/WhiteCoreSim/Config/Grid/ServerConfiguration/Login.ini
	 
	##
	;; This sets the message when a user logs in.
	;; <USERNAME> adds the user's name into the message.
	 
	WelcomeMessage = "<USERNAME>, Bienvenido a EBIMSim"
	 
	##

restart all and not working
