### ISSUE TITLE
Explications and screenshots

### ISSUE THREAD

**Issue by johnfelipe** [WhiteCoreSim/WhiteCore-Dev#266]
Hi, i need description or explications for this:

Full Region, Homestead, Openspace
Flatland, Grassland, Hills, Mountainous, Island, Swamp, Aquatic
May be with screenshots.

Guest, Resident, Member, Contractor, Charter_Member
What is permissions for each one

Tnks

**Comment by emperorstarfinder** [comment]
Guest, Resident, Member, Contractor, Charter_Member are levels used by the economy module.  In most cases by default all users on your grid will be Resident (normal user).

Flatland, Grassland, Hills, Mountianous, Island, Swamp, Aquatic refer to the types of terrains you can use when creating a new region.  

Full Region, Homestead, Openspace, WhiteCore Homes are region types (similar to what Secondlife uses for their region types).  Each region types has a max amount of MaxObjectCapacity that it can support.  In most cases youll likely use the Full Region.
