### ISSUE TITLE
How to change the region port?

### ISSUE THREAD

**Issue by toweiyg** [WhiteCoreSim/WhiteCore-Dev#267]
when use "create region" command in the sim console in grid mode, the region's port will automatic generated. Then how to change the region port?

**Comment by toweiyg** [comment]
under 0.9.5, it will not ask. @emperorstarfinder

**Comment by emperorstarfinder** [comment]
Steps to change port of a region (when necessary):

1. In region console type: update region info and hit enter
2. Answer the questions.  You will be asked for the port number for the region in the event you want to change the port of the region.  (it is not normally advised to change a region's port as it could create conflicts with other regions you have running.  So you should only change the port a region listens on when absolutely necessary.)
3. Answer any and all other questions it asks and it will then update the region info.  

NOTE: After completing these steps you may need to restart the region for the changes to take affect on your grid.

**Comment by toweiyg** [comment]
Thank you. use update region info ,it works. but when  use create region command, it will not ask you privide region port.

**Comment by emperorstarfinder** [comment]
When creating the region the port is automatically detected based on the ports being used by regions and how many regions each region server instance is using.  The need to change a region's port should only be done when absolutely necessary.  Otherwise the regions will work just fine and will use an available port assigned to it.

**Comment by toweiyg** [comment]
@emperorstarfinder , because i try to load several sims。 when i start the first use http_listener_port 8015,and the regions port automatic use 8015\8016.... then i start the second use http_listener_port 8016, the retions port automatic use 8016\8017..., even if the region port 8016\8017 already in using.

hope to give the choice(the console can provide a default port) for deploy.

thank you!

**Comment by greythane** [comment]
Defaulting and hiding the port selection was done to make region creation more user friendly. Not everyone knows what port they should use for a new region  :)

If you are using multiple instances of region servers then I would suggest that you seperate the region port by a larger number to avoid the crossover possibility.
e.g.
Server 1: 
- create first region (default port will be 9000)
- update region info and reset port to new desired port  eg. 8015
Server 2:
- create first region
- update region info and reset to the second port range e.g.. 8115

New regions added to server 1 will increment from 8015.  New regions for server 2 will increment from 8115 and so on.

**Comment by toweiyg** [comment]
@greythane thank you!

**Comment by emperorstarfinder** [comment]
Also keep in mind by default the region ports will start at 9000 and increment upward as greythane has mentioned.  The best idea would be to use the 9000-9999 port range for your regions to ensure your not conflicting with other ports needed by your grid services.

**Comment by greythane** [comment]
Closing as deemed answered
