### ISSUE TITLE
Which version of OpenSim the WhiteCoreSim compatible with？

### ISSUE THREAD

**Issue by toweiyg** [WhiteCoreSim/WhiteCore-Dev#269]
Which version the WhiteCoreSim Compatible with Opensim? I found a few LSL and so on will not work under WhiteCoreSim but in Opensim.

or,where can we find the list of Scripts or other function of WC?

Thank you, @emperorstarfinder @fly-man- @

**Comment by greythane** [comment]
Most of the scripting is available from Opensim but there are a few functions that have not yet been implemented.

Can you let me know which LSL function call fails and I'll have a look at what is needed to implement it.

**Comment by emperorstarfinder** [comment]
There are bound to be a few LSL and OSSL functions that may not be working in WhiteCoreSim.  But if you let developers know which they are I am confident they will get fixed in short order.

**Comment by toweiyg** [comment]
@greythane @emperorstarfinder ， Will the WhiteCoreSimkeep merge new code and functions from Opensimlator Projiect?

**Comment by emperorstarfinder** [comment]
We do have most (if not all) of the LSL and OSSL functions implemented and supported that Opensimulator has.  However this does not mean that there won't be functions here or there users of WhiteCore-Sim will find arent implemented or need tweaking.  In many cases its hard for developers to keep up with the other projects (though they do try as hard as they can to keep up).  

If in your use of WhiteCore-Sim you find a function that is not working or appears to not be implemented it is always encouraged to open a ticket to let the core developers here know.

**Comment by greythane** [comment]
Closing as missing OSSL and LSL functionality will be added whenever something is found to be missing.
