### ISSUE TITLE
little error or warning in runprebuild.sh with mono 5

### ISSUE THREAD

**Issue by johnfelipe** [WhiteCoreSim/WhiteCore-Dev#271]
![errorrunprebuild](https://cloud.githubusercontent.com/assets/428820/26482472/2f75c3ba-41ad-11e7-9f65-29f7c20906dd.png)

how solve red msg or not important?

**Comment by greythane** [comment]
Interesting.  This looks like something that Mono 5 has introduced
The xbuild tool is the standalone compiler that is normally used in a *nix environment (what I use almost exclusively )

I will have to  check into this and see how this might effect standalone builds.

Building from an IDE still should not be a problem as they will include the correct build environment tools appropriate for the OS

**Comment by johnfelipe** [comment]
Ok, that is a good news i will close, pls reopen when you have a good advance in this issue

**Comment by emperorstarfinder** [comment]
Yes @greythane i noticed that the other day and forgot to mention this.  I assume they will probably be fully removing xbuild with Ubuntu 17.04 LTS (Possibly as that is usually when they seem to be removing depreciated programs).
