### ISSUE TITLE
iar file and path

### ISSUE THREAD

**Issue by johnfelipe** [WhiteCoreSim/WhiteCore-Dev#272]
Hi bro, in this linke https://github.com/WhiteCoreSim/WhiteCore-Dev/issues/261#issuecomment-301723442

"You need to put the IAR files in WhiteCoreSim/Data/UserArchives (you may need to do the save iar firstname lastname iarname for it to create the folder for you.)"

![notview](https://cloud.githubusercontent.com/assets/428820/26486513/07d8b45c-41c1-11e7-8c3a-692ed343b13e.png)

UserArchives folder is not show, how create?

**Comment by emperorstarfinder** [comment]
Simply do the save iar <First Name> <Last Name> <IAR Name> and that will create the folder for you.  You can manually add the folder but its better to let it create the folder for you so it recognizes it.

**Comment by johnfelipe** [comment]
But i need load iar, bro:

	WhiteCore.Server # load iar
	User Name <first last>:  []: felipe urrego
	IAR file to load (? for list):  [felipe_urrego.iar]: /home/felipe/WhiteCore-Dev/WhiteCoreSim/Data/elegantsuitopensim.iar
	Do you want to 'merge' this archive or 'create' a new folder 'IAR Import'? (merge/create) [create]:enter

Where put that iar file for load?

**Comment by emperorstarfinder** [comment]
Once you do the save iar command it will create the UserArchives folder in the Data directory.  All iar files you save and load will go in that folder.

**Comment by johnfelipe** [comment]
But I need command for load iar?

**Comment by emperorstarfinder** [comment]
instead of save iar you use load iar

load iar FirstName LastName IARName

(Replace the FirstName LastName with the user's first and last name and IARName with the name of the iar file.

**Comment by greythane** [comment]
Multiple test with loading IAR files from both WhiteCore and OpenSim have not been found to fail.
Closing
