### ISSUE TITLE
Update process for latest git clone or pull

### ISSUE THREAD

**Issue by johnfelipe** [WhiteCoreSim/WhiteCore-Dev#275]
I see update repository, how can update?

**Comment by BogusCurry** [comment]
- As of January 2017, the LibOMV libraries are included as a submodule of the WhiteCore repo. When cloning, ensure that the submodules are included.

git clone --recursive https://github.com/WhiteCoreSim/WhiteCore-Dev.git

To update an existing repository that does not have the LibOMV submodule

cd <your WhiteCore repository>
git submodule init
git submodule update

**Comment by johnfelipe** [comment]
But how can update latest lib?

**Comment by emperorstarfinder** [comment]
You update it just as @BogusCurry  said.  In your case you need to grab the latest from WhiteCore-Dev when it builds it will pull the libOMV stuff it needs and will build the libraries.

**Comment by johnfelipe** [comment]
Then I need only update and replace?

**Comment by emperorstarfinder** [comment]
That would be correct.  Once you have built the updated solution its as easy as copying the contents of the bin directory to the bin folder in the directory your running WhiteCore from.

**Comment by greythane** [comment]
Closing as answered
