### ISSUE TITLE
Is the WebInterface module finished?

### ISSUE THREAD

**Issue by toweiyg** [WhiteCoreSim/WhiteCore-Dev#276]
From my practice, as if the WebInterface is not 100% implemented. Example:

1、The HomeRegion, if i choose a homeregion to register an avatar, but when i use the avatar to login, the avatar will been teleported to another region. I followed the code of register, I found ,the code try to update the user_info table with the created userid, but at this moment, there is no records of this user ino the user_info. So when I finished register, the user_info tables has no records about the avatar.

2、On the register page , the snap picture of avatar cannot be display. The src url of  the avatar snap like "..:8003/index.php?.....", why php come out?

**Comment by emperorstarfinder** [comment]
Are you attempting to use the builtin WebuUI or the external WhiteCore-WebUI?

**Comment by toweiyg** [comment]
@emperorstarfinder I am tring to use the default webui, which html files stored in bin/html

**Comment by emperorstarfinder** [comment]
Okay,

The builtin webUI is in the process of being upgraded.  Some pages may not necessarily work fully but the registration page does work and a default avi will be created for users when they log in for the first time.  THe easiest way is to leave the default avi option unchecked for the time being until the upgraded webUI is put in place.

**Comment by greythane** [comment]
Work commitments have kept me super busy but have now eased a bit so I will be finishing the updated WebUI as a priority
