### ISSUE TITLE
Moving FileBased assets from NTFS to EXT4

### ISSUE THREAD

**Issue by stormsonweathers** [WhiteCoreSim/WhiteCore-Dev#278]
Hello everyone,
Just a quick question; is there a way to revert back to DB based assets over the filesystem method? When I tried to migrate my Windows 7 install of WhiteCore to OpenSUSE Tumbleweed, in the Linux folders, the .data and .asset files are missing. I even tried to copy the files in a 7z file from within windows and dump it that way and still have the same results.

A secondary test grid I was working on (that was still using the DB assets) migrated fine.

I maybe overlooking something simple, so please bear with me. 
Thank you!

**Comment by emperorstarfinder** [comment]
Good evening,

When you want to transfer data files from one machine to another (this would apply in your case to for file based assets), You would just backup the entire Data directory.  All of your Data and Asset files are stored in this directory (WhiteCoreSim/Data).

To go back to the Database storage (it will be slower then FileBasedStorage) you would simply edit the following in the Data.ini file:

[Handlers]
;; Possible choices for asset services:
;;  AssetService - basic SQL service, slower, but works
;;  RedisAssetService - Redis database, fast, but memory hog
;;  FileBasedAssetService - Uses the file system to store assets, fastest
AssetHandler = FileBasedAssetService
AssetHandlerUseCache = false

Change FileBasedAssetService to AssetService and that should be all there is to it.  This however assumes that you have the assets stored in the Data directory.

Hope this helps a bit.

**Comment by stormsonweathers** [comment]
@emperorstarfinder I did move the WhiteCoreSim/Data directory, but when I ran WC on linux, there were an array of errors saying that the assets were missing and diving into the folders on linux did show that they were not there (I went back to the original windows folders and the assets were there).  I haven't tried to switch back using the Handler, so I'll give that a try tonight. Thanks again!

**Comment by emperorstarfinder** [comment]
Hmmm very interesting.  I am going to go out on a limb here and guess that your not moving the Data directory outside of the WhiteCoreSim directory on the ext4 partition and putting the rest of the WhiteCoreSim directory on the main partition.  

I have moved my local WhiteCoreSim from Windows to nix (Ubuntu) without any residual problems.  However I did keep all the directory structure in tact.  

The easiest way for you to convert everything to DB storage would be to put it all back on a windows machine and change the line I recommended in the Data.ini files (Both grid and region if both levels are desired).  Then run WhiteCoreSim.  That will migrate everything back into the Database.  

Also when redoing operating systems or even changing operating systems it is usually a wise idea to save OARs (for region backups) and IARs (for inventory backups).  The reason you do this will be to ensure you have saved backups that contain all the Inventory Items and Assets.  

It should be noted that there are some things such as textures that do not really get saved in the .sim backup files just the UUID of the textures.  So if you were to try it with just the region backup without the Asset folders etc you likely will just have a whole heap of the green missing image texture everywhere.

**Comment by stormsonweathers** [comment]
@emperorstarfinder I did everything as you suggested:
Even after setting the Grid/Standalone settings back to AssetService, the WC did not initiate the migration script. It simply tried to access the DB as if the assets were already there. I even copied the entire WhiteCoreSim-Dev folder over, recompiled with Mono, and still the results are the same.

I'll just follow your latest suggestion by making an OAR of the region and IAR the user assets.
Again, thank you for your time in trying to help. 

Stormy.

**Comment by emperorstarfinder** [comment]
Your very much welcome.  As I said I didnt have trouble doing it with Ubuntu and Windows but it could very well be just some strange phenomenon with OpenSUSE that just isn't known. 

The Nix operating systems I find work the best so far with WhiteCore are:

Arch/ Monjaro
Debian
Ubuntu

**Comment by stormsonweathers** [comment]
@emperorstarfinder 
Granted, I did had issues with OpenSUSE with WC years ago, but I think it was their interpretation of Mono at the time so I migrated to Windows.  I haven't tried Arch yet and everytime I tried using Ubuntu I ended up returning to SuSE (I guess I got used to it's quirks since the 2.0 days). Like you said, it could be the reason since Im using the Tumbleweed release rather than stable (42.3). 
While Im still creating the OAR/IARs, I'll check Arch out and maybe Debian in the meantime. Thanks for the suggestions!

**Comment by emperorstarfinder** [comment]
If your planning to run WhiteCore in a production environment meaning a public grid I would definately use either:

Arch/ Monjaro
Debian
Ubuntu

Arch/ Monjaro has its own custom version of mon which appears to be far more stable then the mainstream mono at mono-project.

I have had no problems with these three nix operating systems.  The only thing I have found I needed to do with the latest versions of mono (on Ubuntu and Debian) is to create a shell script to clear the sgen memory in mono every hour to prevent it from overflowing and causing the regions to crash.

**Comment by stormsonweathers** [comment]
I was able to sucessfully move a smaller WC install over to SuSE with no problems, so I thought the larger WC install would work, but just snagged at the whole FileSystemAssets thing. Right now I got a OSGrid install running along with the smaller WC install. For WC I just added "ulimit -s 262144" to the script and worked fine... so far. :)

**Comment by emperorstarfinder** [comment]
It might even be that one or more of the data files got corrupted along the way somehow.  That is something that is known to happen especially with Windows 7

**Comment by stormsonweathers** [comment]
Yes, to the "run_standalonemode.sh" script. Should have elaborated on that.

**Comment by emperorstarfinder** [comment]
That is what I thought.  I am curious what memory is like for you with the OSGrid release not to mention which version your running.  But you can email that info to me to so it doesnt get people confused.

**Comment by stormsonweathers** [comment]
@emperorstarfinder Will do, but your profile is missing an email address.  
As for the thread at hand, still having issues moving files, but I think I can try using winrar to copy the asset folder over and dump it onto Linux.

**Comment by emperorstarfinder** [comment]
Yes winrar the entire WhiteCoreSim directory.  You will have to rebuild under nix so make sure you winrar the entire directory including source code and libOMV

the easiest way to send emails to me is via emperor@secondgalaxy.com

**Comment by stormsonweathers** [comment]
@emperorstarfinder Thanks. I'll update with any results. Also email sent.

**Comment by stormsonweathers** [comment]
@emperorstarfinder I figured out the problem: It's case sensitive directories.
For example:
' WhiteCore-Dev/WhiteCoreSim/Data/FileAssets/data/8S/n5/Rr/yq/8Sn5RryqsjwTiNJyJqjxiB2Wrp90aVOQeWAmlcy9AQ73431.data'
is written for the directory in Linux, (Note the '8S' Folder), the assets table is looking for '8s' instead so it's appears that the files never copied when they did. Since windows isn't case sensitive, it works as expected.

**Comment by greythane** [comment]
Thanks Storm, 
this is certainly a trap and needs to be sorted.

**Comment by stormsonweathers** [comment]
@greythane @emperorstarfinder 
I think I found a solution:
Adding "export MONO_IOMAP=all" to the startup script should allow Mono to treat the file system in a case insensitive manner like on Windows. I'm not able to access my server at the moment, but will give you all a head's up when I'm able to.

**Comment by emperorstarfinder** [comment]
While we are at it with sorting out the solution to the mono trap found here it might also be wise to add the "ulimit -s 262144" command to the .sh scripts to ensure that people wont run acrossed the sgen memory issues with mono due to the recent changes in mono memory sizes.

**Comment by stormsonweathers** [comment]
@emperorstarfinder @greythane @fly-man- 
UPDATE:
The use of "export MONO_IOMAP=all" added to the "run_standalonemode.sh" fixed the issue.

**Comment by stormsonweathers** [comment]
UPDATE 3:

WC sigfaulted and upon restart the case sensitive error resumed regardless of the mono_ipmap switch. I may have to move the install to a loop container since I can't seem to migrate back to mariadb by disabling both grid and standalone FileBasedassets switches.
Again, will keep posting updates. :)

**Comment by emperorstarfinder** [comment]
WC is sigfaulting likely because of mono's default memory sizes.  I found the best way to handle that so far is by creating a cronjob which every hour will trigger a shell script which will tell the system to dump the memory cache for mono.  When that was started all the sigfaulting did in fact go away.  

In all likelihood if its just your region console having the problem then that would in fact clear that up.  My team runs this on our region servers for our main grid and it has done the trick.  It is a holiday here in the US so when I get a moment today I will post the steps of what to do as I already have the shell script created etc.

**Comment by stormsonweathers** [comment]
@emperorstarfinder That would be appreciated, thanks Emperor! I've been trying to figure that out for years!

Oh, as for the Filesystem issue; I've noticed that WC created the 'missing' folders
 (ie: making an '8s' folder instead of accessing the '8S' folder that's already there) as lowercase which gave me an idea; I'll remove the new folders and using a script, rename the existing folders to lowercase recursively.

I'm gonna try and see if my hunch is write. Will update as usual! :D

**Comment by emperorstarfinder** [comment]
When I moved between Windows and Nix I noticed the same thing to.  However I just left the folder and it didn't appear that it cared that it was there.  I suspect if you look in the folder the assets are there.  However if your testing on OpenSUSE there may be a difference (albeit a slight difference) compared to Ubuntu, Debian, and Arch Linux.  

Right time for the Barbecue.  Don't want the Mrs. getting upset now do I LOL

**Comment by stormsonweathers** [comment]
@emperorstarfinder  LOL, no worries, enjoy your 4th! I'm in the states as well, but I work every holiday.

**Comment by stormsonweathers** [comment]
FINAL UPDATE (whew!)
I finally solved the problem. It was as simple as doing a case swap on the folder names.

take this line for example:
/srv/sims/testsim/WhiteCore-Dev/WhiteCoreSim/Data/FileAssets/data/Bl/ef/yy/fF/BLefyyfFIsQmUdurq9Lb9KSyEAEZ5aGoceqNDwvMRnY1225.data

The problem was that WC was looking for the "/data/bL" folder and not "/data/Bl" as shown. This was fix by inverting the capitlization for ALL the folders in the "/FileAssets/data" folder. The folders below that were fine. So "0c" became "0C", "E8" to "e8", etc.
 
I used a python script called Tren [https://www.tundraware.com/Software/tren/tren.html] to do a swapcase of all the folders and after running, the missing assets errors are now gone, even after multiple restarts and "export MONO_IOMAP=case" is no longer needed.

**Comment by greythane** [comment]
Hi Storm,
Thanks for all the debugging...
File case is always a problem when moving between case insensitive and case sensitive OS's.

Can you verify something for me please.
On several Ubuntu systems, I have checked the file assets and it appears that all directories and files have been created using lower case.  Is this the same for your system?

Based on what I can see, ensuring that lowercase is always used in the file path/filename would ensure compatibility between OS's
I am reluctant to enforce this lowercase yet if some system create data with the uppercase characters as per what you advised above.

**Comment by stormsonweathers** [comment]
@greythane 

Hello! On the WC install I was having issues with, Windows 7 created the "/FileAsset/"Folder structure in mixed case and when I saved the directory tree, it preserved the case based on what Windows created, though I can't explain why the casing was inverted in just the /FileAssets/data" level and just that level alone. After inverting the casing for that level, OpenSuSE had no further issues after that. the lower directories below that, also had alternating casing had no issues.

On a Clean install of WC on OpenSUSE using EXT4, the "/FileAssets/data/" was also populated with mix-cased directories, but OpenSuSE had no issues with those folders. 

My guessing is based on what @emperorstarfinder  mentioned, it may have been a glitch with Windows 7 inverting that directory level during the original Asset database migration. But why just "FileAssets/data" affected and not the others? I don't know.

**Comment by emperorstarfinder** [comment]
Evening,

I have tested this a little bit this evening as my curiosity was high on this.  I blame @stormsonweathers for that LOL.

Windows has historically been case insensitive where Nix has always been case sensitive.  When transferring a fresh copy of WhiteCore (for this test) from Windows to multiple different versions of Debian and Ubuntu, the system appears to be able to tell the difference and handle the fact that there are capital letters where there in fact should be lowercase letters.  

I have not really played around with OpenSuSe so I cannot say for sure whether it just happens to be a bit more picky about that (which from this issue appears to be the case) or not.

The windows operating system (Windows XP, Windows Vista, and Windows 7) does have a glitch or bug if you will, that happens at random that causes some files (or directories of files) to get inverted.  I have seen this myself and actually a couple times have watched it do it.  I suspect part of it has to do with the way windows handles naming and renaming of files.  

The best recommendation would be to create one naming convention within WC that will support all operating systems by using either all lowercase or uppercase letters for the letters in the file names.  

The sig faults @stormsonweathers was getting are in fact related to the mono memory cache size.  Mono has changed how memory is handled in the latest version so even if you were to set the -u limit command it may or may not work depending on how much is in fact running on the machine.  I will the proper cronjob info and script to @stormsonweathers when i get my first cup of coffee in the morning.  I have it noted on a sticky right on my monitor.  

I'll do some further testing on this as well to see if there is something else that can help as far as transferring WC from a Windows based OS to nix.

**Comment by stormsonweathers** [comment]
@emperorstarfinder @greythane 
Morning,
I'm glad to know I'm not the only one with OCD regarding all this, eh @emperorstarfinder ? LOL ;).
As for the naming conventions, yes, I would have to agree with @emperorstarfinder . If file based assets are to be used (and now default), then a more universal approach to naming the directories are in order. Also, maybe a way to cross import assets (moving between MariaDB, FileBasedAssets, Redis, Systemd, a toaster, pocket universe, etc.) so that someone can find a storage solution to fit their use case.

**Comment by emperorstarfinder** [comment]
@stormsonweathers I have emailed you the shell scripts and instructions for setting up the cronjob to trigger the script.  That should sort the SIG faults issue for mono.  Those Sigs are mostly memory related in mono as I indicated before and it does work for me.  We use it on my grid all the time on all our region servers.

**Comment by stormsonweathers** [comment]
@emperorstarfinder Sorry for the delay, just wanted to say thanks for the scripts. That solved the sigfaults. Thanks! 👍

**Comment by emperorstarfinder** [comment]
I knew it would.  The reason why that works and the -u limit command isn't working is because of a change in how Mono handles its memory cache.  Because of that WhiteCore (and my grid's architecture along with my team's opensource project arm) will easily eat through the size limitations of the mono memory cache within a week and sometimes within a day.  The script and corresponding cronjob take care of that every hour so you wont hit that limit.

**Comment by stormsonweathers** [comment]
Just want to thank everyone for their help if helping me figure this out. I guess it's safe to go ahead and close this. :)
