### ISSUE TITLE
destination not found with "run configurator" method

### ISSUE THREAD

**Issue by johnfelipe** [WhiteCoreSim/WhiteCore-Dev#285]
Jul 05 09:20:08 - [LLLoginService]: User did not have a home, set to (no region found)
	Jul 05 09:20:08 - [LLogin service]: Got Custom Login URI uri:ebim1&128&128&25, can't locate region ebim1. Trying defaults.
	Jul 05 09:20:08 - [LLogin service]: Got Custom Login URI uri:ebim1&128&128&25, Grid does not have any available regions.
	Jul 05 09:20:08 - [LLogin service]: Login failed for user felipe urrego, reason: destination not found

I do this:

	cd WhiteCore-Dev/WhiteCoreSim/bin/
	./WhiteCore.sh

	Estate name [Owner's Estate]: Myestate
	Region Name (? for suggestion) []: ebim1
	Region Location X [1000]: 1000
	Region location Y [1000]: 1000
	Region size X [256]: 256
	Region size Y [256]: 256
	Region Type (Mainland / Estate / Homes) [Estate]: Estate
	Estate region type?, Options are [Full Region] [Full Region]: Full Region
	Terrain Type?, Options are [Flatland, Grassland, Hills, Mountainous, Island, Swamp, Aquatic] [Grassland]: Grassland
	Estate owner name (RealEstate Owner/User Name) [RealEstate Owner]: felipe urrego

	screen -r Grid 

	Estate name [Owner's Estate]: Myestate

![region](https://user-images.githubusercontent.com/428820/27892949-224814b4-61c8-11e7-8ef6-853e008ccc10.png)

and

![regionlist](https://user-images.githubusercontent.com/428820/27892975-503fb8b8-61c8-11e7-86a3-41b0165fc663.png)

How solve it

**Comment by johnfelipe** [comment]
any idea for solve this?

**Comment by greythane** [comment]
The error indicates that there is no region  named 'ebim1'
This is also shown on the graphics.. region count:0 and none listed.

Your text detail seems to be cut off prior to the actual region creation 
- Terrain Type?, Options are [Flatland, Grassland, Hills, Mountainous, Island, Swamp, Aquatic] [Grassland]: Grassland
-Estate owner name (RealEstate Owner/User Name) [RealEstate Owner]: felipe urrego

_There should be more console details here to indicate assignment and creation of the region_

-screen -r Grid

**Comment by emperorstarfinder** [comment]
I must admit I am a bit skeptical this is an actual bug.  WIthout seeing the actual log from the region server it would be hard to see whats going on.  logs can be found in WhiteCoreSim/Data/logs directory.  They will say the name of the server and the date of the log as the file name.

My worry here is that we are chasing down more of the issue in #280 and #287 and #286 If you can provide the txt file for the log that should help us figure out what is actually going on.

**Comment by greythane** [comment]
Closing as no further details have been made available.
Problem has not beed seen in multiple instances
