### ISSUE TITLE
Revert assets back to DB.

### ISSUE THREAD

**Issue by stormsonweathers** [WhiteCoreSim/WhiteCore-Dev#288]
Hello again,
Not really an issue as much as it is a question. Is there a way to move the assets back into MariaDB/MySQL? I did followed @emperorstarfinder suggestions in a previous issue by switching back to "AssetHandler = AssetService"  in the ini files, but to no avail.

I understand that File Based Assets are faster, but I do have a SAS drive that my database sits on and only have one megaregion is so speed really isn't  an issue right now. :)

**Comment by emperorstarfinder** [comment]
Other then taking IARs and OARs and reloading them thats the only way I am aware of to do that.  The DB should populate over time (it may take a few times for it to do so but as long as those assets currently stored via FileBasedAssets are there it should work just fine with new stuff getting inserted into the DB

**Comment by stormsonweathers** [comment]
@emperorstarfinder I guess OAR is what I may have to do. I tried on Windows 10 and Ubuntu Server 16.04 (btw, the inverted filename problem happened there, too, lol) and couldn't get the test grids to save back to MariaDB. Maybe it's something I'm missing as it won't be the first time. I'll give it a couple of more tries before throwing in the towel. Again, thanks for always pushing me in the right direction @emperorstarfinder

**Comment by greythane** [comment]
Storm,
Currently there is no way to migrate from the Filebased systems back to MySql/Sqlite.  The auto migration only goes to the file based systems, I guess because all the original setups used the Sql data storage for assets.
This may be something that I will look at if the need arises

**Comment by emperorstarfinder** [comment]
@stormsonweathers Thanks for the heads up on the inversion issue in Win 10.  Ill try to figure out a work around to to compensate for that for those wanting to move from windows to nix.  Though I believe the better way is a standardized file naming convention that works for all Operating Systems.  I am however a bit surprised to hear that its also in windows 10 as I would have thought Microsoft would have caught on by now.  

At this point this probably should be labeled an enhancement as this would just be an improvement relating to FileBasedStorage and the file naming convention.

**Comment by stormsonweathers** [comment]
@greythane No probs! I thought it would be a bit iffy without work. As long as it is working, I'm grateful :)

@emperorstarfinder  Yea, I think it could be ext4 also since OpenSuSE and Ubuntu both are experiencing the same problems, but that's stretching it without more research. And I did try with clean installs (both Ubuntu and OpenSUSE) and both clean installs worked great. It's just when coming from NTFS is when I'm having troubles unless I revert the casing of the contents of the "/FileAssets/data" folder. Again, the other folders in "/FileAssets" do not exhibit the problem.

**Comment by emperorstarfinder** [comment]
@stormsonweathers That could be but I really see no reason why ext4 should matter.  Give it a go in the normal /home directory and see what happens there.

**Comment by stormsonweathers** [comment]
@emperorstarfinder I know ext4 is rock solid, so there's no need :) I was alluring to the idea that while it is possible, it's like throwing a rock in the ocean in order to make a tidal wave. :)
Since @greythane also chimed in about the topic at hand, I might as well close this thread, too.  

So far, everything's working and no hickups. Again, thanks you @emperorstarfinder and @greythane
