### ISSUE TITLE
Command for save iar folder

### ISSUE THREAD

**Issue by johnfelipe** [WhiteCoreSim/WhiteCore-Dev#289]
Pls tell me how is correct command for save iar this:

![pantallazo-0234](https://user-images.githubusercontent.com/428820/28533597-5922499c-7063-11e7-858b-67c59c434a00.png)

I need save all folder
tnks

**Comment by emperorstarfinder** [comment]
the command:

save iar <username> <archive name.iar>

**Comment by johnfelipe** [comment]
Bro I need save only folder, share me details

**Comment by emperorstarfinder** [comment]
"save iar",
                        "save iar <first> <last> [<IAR path> [<inventory path>]] [--noassets]",
                        "Save user inventory archive (IAR). <first> is the user's first name."
                        "<last> is the user's last name."
                        "<IAR path> is the filesystem path at which to save the IAR."
                        "           If this is not given then the IAR will be saved in "/UserArchives\n"
                        "<inventory path> is the path inside the user's inventory for the folder/item to be saved.\n"
                        "                 (Default is all folders)\n"
                        " --noassets : if present, save withOUT assets.\n"
                        "               This version will NOT load on another grid/standalone other than the current grid/standalone!"
                         "--perm=<permissions> : If present, verify asset permissions before saving.\n"
                         "   <permissions> can include 'C' (Copy), 'M' (Modify, 'T' (Transfer)",

it should be noted that you can also use the help command on the consoles to get information as well.

For example you can do help save which will show you all the possible commands involving the word save supported by WhiteCore.  If you type just help it will show the categories of all commands possible in WhiteCore

**Comment by johnfelipe** [comment]
if i have this:

![pantallazo-0240](https://user-images.githubusercontent.com/428820/28544780-15157202-708a-11e7-9114-e609a5f50389.png)

> save iar felipe urrego ironmanversionwhitecore /IAR Import/ironmanopensim

show me this log

	Jul 24 04:08:08 - [Inventory Archiver]: Saving archive ../Data/UserArchives/ironmanversionwhitecore.iar using inventory path /IAR for felipe urrego
	Jul 24 04:08:08 - [Inventory Archiver]: Aborted save.  Could not find inventory path IAR

**Comment by emperorstarfinder** [comment]
That would be because putting a space in the folder name is not being liked.  That isn't something at fault on your end that is likely due to the operating system on the hardware being fussy.  if you do the load iar command with merge instead of create that will merge the iar archive into the top level inventory and should solve that.

**Comment by fly-man-** [comment]
No response after a year, closing the issue
