### ISSUE TITLE
Max size of collada model for upload into whitecore

### ISSUE THREAD

**Issue by johnfelipe** [WhiteCoreSim/WhiteCore-Dev#291]
I have whitecore in windows standalone and local instance, i need upload collada with 678 mb of size:

What max size supported?
Is any file for edit to view this max?

Stay alert

**Comment by emperorstarfinder** [comment]
As far as I am aware, there is no max limit for the size of a collada file size when uploading mesh content.  However the length of time it will take to do the calculation and upload of the content will depend on the size of the file.  So time will likely vary.

**Comment by johnfelipe** [comment]
Crash automatically viewer

**Comment by emperorstarfinder** [comment]
And I think you know what I am going to say next by now.  What was the message given in the consoles and viewer when the crash occurred?
