### ISSUE TITLE
Regions turn darker after a teleport

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#295]
Hello all ;D
I have a little bit crazy effect in my little standalone region. At first, the standalone run local on LM 18.3  with actual Mono version and I have this today update after 4 month. Now I log in in my world and all good, then I change to the another region, where is a oar from opensim, comes in this region and the darkness comes over me.  
I have no becomes error message or, only is darkness on this region and all the another region too. 

Now the big question, is that a bug or only a new feature from the opensim devs .. lol

Greetings
Bogus

**Comment by fly-man-** [comment]
@BogusCurry What viewer are you using ??

And can you add some snapshots to show what exactly is happening ??

**Comment by emperorstarfinder** [comment]
Also please set console log level to debug and provide us a copy of the log when this happens.  That also could give us a few clues as to what is happening.

**Comment by BogusCurry** [comment]
I use Singu 1.86 snapshots comes the next days ;D

How can set log level to debug in the console ?

**Comment by fly-man-** [comment]
@BogusCurry Can you try and get the most recent Alpha build from Singularity which has some changes to the Windlight. I'd like to make sure it's not WL that's causing this issue

**Comment by emperorstarfinder** [comment]
@BogusCurry in the consoles simply type log level info (will only provide info level items, log level debug (gives debugging information), and log level all (gives you both info and debugging level information).

I suspect this is the same issue greythane and i along with other members of my team were trying to trace down last year with no success as it was being reported on my teams tracker with multiple different viewers.

**Comment by BogusCurry** [comment]
Hi all ;D
Ok, after months I have my little WCS standalone update on the actual code and have test with the Singu 1.86 and .... I have no problems now ;D I can not say, what this was or is now fix .. anyway, is now fix ;D

I can on thing say ... I love WCS ;D

Have a nice Day ;D
Bogus
PS: So now close this thread ... lol
