### ISSUE TITLE
[BUG] Uploading RAW files failing

### ISSUE THREAD

**Issue by fly-man-** [WhiteCoreSim/WhiteCore-Dev#300]
### Steps to reproduce

1. Start Grid and Region Server
2. Login with viewer
3. Try to change the region with use of the Estate Tools by trying to upload the RAW file

### Expected behaviour

Region file is accepted and applied to the region

### Actual behaviour

Error message appears on the console and unable to apply the region file

### Server configuration

**Operating system**:

Windows 7 / x64

**Web server:**

Internal webserver

**Database:**

MariaDB

**WhiteCore version:**

Master

### Logs

Please make sure that WhiteCore has made an log-file and include a link to it here

apr 11 08:52:23 -  [Client]: Caught exception while processing OpenMetaverse.Packets.EstateOwnerMessagePacket for RealEstate Owner, De objectverwijzing is niet op een exemplaar van een object ingesteld.    bij OpenMetaverse.Packets.AlertMessagePacket.get_Length() in W:\GitLabHQ\WhiteCoreSim\WhiteCore-Dev\Whitecore-LibOMV\OpenMetaverse\_Packets_.cs:regel 23750
   bij WhiteCore.ClientStack.LLClientView.OutPacket(Packet packet, ThrottleOutPacketType throttlePacketType) in W:\GitLabHQ\WhiteCoreSim\WhiteCore-Dev\WhiteCore\ClientStack\LLClientView.cs:regel 12630
   bij WhiteCore.ClientStack.LLClientView.SendAlertMessage(String message) in W:\GitLabHQ\WhiteCoreSim\WhiteCore-Dev\WhiteCore\ClientStack\LLClientView.cs:regel 2386
   bij WhiteCore.Modules.Estate.EstateManagementModule.handleUploadTerrain(IClientAPI remote_client, String clientFileName) in W:\GitLabHQ\WhiteCoreSim\WhiteCore-Dev\WhiteCore\Modules\World\Estate\EstateManagementModule.cs:regel 710
   bij WhiteCore.ClientStack.LLClientView.HandleEstateOwnerMessage(IClientAPI sender, Packet pack) in W:\GitLabHQ\WhiteCoreSim\WhiteCore-Dev\WhiteCore\ClientStack\LLClientView.cs:regel 10054
   bij WhiteCore.ClientStack.LLClientView.ProcessSpecificPacketAsync(Object state) in W:\GitLabHQ\WhiteCoreSim\WhiteCore-Dev\WhiteCore\ClientStack\LLClientView.cs:regel 741
apr 11 08:53:06 -  [Estate Manager]: Got Request to Send Terrain in region Raw Terrain Files
apr 11 08:53:06 -  [Estate Manager]: Sending Terrain to RealEstate Owner
apr 11 08:53:06 -  [Xfer]: terrain.raw not found
apr 11 08:53:21 -  [Client]: Caught exception while processing OpenMetaverse.Packets.EstateOwnerMessagePacket for RealEstate Owner, De objectverwijzing is niet op een exemplaar van een object ingesteld.    bij OpenMetaverse.Packets.AlertMessagePacket.get_Length() in W:\GitLabHQ\WhiteCoreSim\WhiteCore-Dev\Whitecore-LibOMV\OpenMetaverse\_Packets_.cs:regel 23750
   bij WhiteCore.ClientStack.LLClientView.OutPacket(Packet packet, ThrottleOutPacketType throttlePacketType) in W:\GitLabHQ\WhiteCoreSim\WhiteCore-Dev\WhiteCore\ClientStack\LLClientView.cs:regel 12630
   bij WhiteCore.ClientStack.LLClientView.SendAlertMessage(String message) in W:\GitLabHQ\WhiteCoreSim\WhiteCore-Dev\WhiteCore\ClientStack\LLClientView.cs:regel 2386
   bij WhiteCore.Modules.Estate.EstateManagementModule.handleUploadTerrain(IClientAPI remote_client, String clientFileName) in W:\GitLabHQ\WhiteCoreSim\WhiteCore-Dev\WhiteCore\Modules\World\Estate\EstateManagementModule.cs:regel 710
   bij WhiteCore.ClientStack.LLClientView.HandleEstateOwnerMessage(IClientAPI sender, Packet pack) in W:\GitLabHQ\WhiteCoreSim\WhiteCore-Dev\WhiteCore\ClientStack\LLClientView.cs:regel 10054
   bij WhiteCore.ClientStack.LLClientView.ProcessSpecificPacketAsync(Object state) in W:\GitLabHQ\WhiteCoreSim\WhiteCore-Dev\WhiteCore\ClientStack\LLClientView.cs:regel 741

**Comment by greythane** [comment]
This is partially due to recent updates of the OMV libraries and sending alert messages.
Working on it  :)

**Comment by emperorstarfinder** [comment]
Yes and some of those updates are because of recent changes in the viewers to.  I.e. Animesh is now out and there is at least 3 to 4 scripting engine functions as well as a few other things.  (OpenSim should have those updates already).

**Comment by greythane** [comment]
Corrected in commit # bb19123...
