### ISSUE TITLE
How can update the world map inworld, after delete from regions ?

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#302]
Hi there ;D
I have delete 2 regions from my standalone local wcs, but inworld I see the both regions online. Now, how I can update the world map ?
I use the command **remove** to delete both regions

Run the actual rep version from wcs.

Greetings
Bogus

**Comment by emperorstarfinder** [comment]
To update the world map use the command: 

update world map

Also, you need to make sure you delete the backup files for the 2 regions from both the Regions directory and the RegionBak directory.  This will ensure that the regions don't get reprovisioned and you will also need to restart WCS for it to see the regions no longer exist in the directories.

**Comment by BogusCurry** [comment]
Hi there ;D
The correct command is update map, not world map ;D

Ok, so the problem is solved and can close this, but this was more a question, not a problem ;D

Greetings
Bogus

**Comment by emperorstarfinder** [comment]
Yes the correct command for WCS is: update map

I am working on multiple projects plus my team's projects and grids so easy to get the commands mixed up though they are similar.
