### ISSUE TITLE
Question: Where to change the default text in a new script

### ISSUE THREAD

**Issue by Ramius1701** [WhiteCoreSim/WhiteCore-Dev#305]
Change this:

default
{
    state_entry()
    {
        llSay(0, "Script running.");
    } 
    touch_start(integer number)
    { 
        llSay(0,"Touched."); 
    }
}

To this for example:

default
{
    state_entry()
    {
        llSay(0, "LCARS Initialised.");
    } 
    touch_start(integer number)
    { 
        llSay(0,"I'm not programmed to do anything yet!"); 
    }
}

I can change this in the opensim code. Havent been able to locate where in the WhiteCore code

**Comment by emperorstarfinder** [comment]
The Default.lsl script which is what is used when a new script is created can be found at:

WhiteCoreSim/Data/ScriptEngines/Default.lsl

In theory this can be changed and you should be able to change the default message in the new scripts that are created that way.

**Comment by Ramius1701** [comment]
Awesome TY, will test this out :)
