### ISSUE TITLE
another question: Whitecore Sims change to gitlab ? 

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#306]
Hello ;D
Microsoft buy now Github, many devs leave this plattform. What make you with WhiteCoreSims ?

Greetings
Bogus

**Comment by fly-man-** [comment]
@BogusCurry We are already on Gitlab and other places as well. The difference is that we have spread our source over multiple places so when 1 place disappears we can continue at another platform without losing any progress.

**Comment by emperorstarfinder** [comment]
Even though this has been answered in regards to the ability to access the code for WhiteCore-Sim, it is appropriate to point out that Microsoft has not said anything to indicate that Github is going away nor changing.  Microsoft does have its own open source community with its dot net project so it is not likely that too much will change and Github is likely to stick around for a while and will most likely continue providing free public repositories.  So I think at least in the short term it is safe to say that things will be status quo.
