### ISSUE TITLE
Ubit ODE and Bulletsim are not compatible

### ISSUE THREAD

**Issue by Ana-Green** [WhiteCoreSim/WhiteCore-Dev#309]
Ubit ODE and Bulletsim are not compatible I just found out in certain ways and  mesh rez faster with Bullet besides with bullet I can walk up a ramp with ODE I have to jump, If a woman put her shoes on,  on a region where Bullet is activated it looks  ok, however, if that woman HG Teleport or  local Teleport to a region with ODE  activated the shoes do not  fit anymore she has to re-adjust it with the HUD what  comes with the Mesh Body. Ubit things this remark or issue is:: [01:27:02] Ubit Umarov: wrong meshes, [01:27:24] Ubit Umarov: learn how to make them, and about physics shape type convex. However, I tested it with over 12 different shoes myself or "use what you like" so he said and "plz stop bothering me with nonsense" walk up a ramp with ODE I have to jump with BulletSim I can just walk up the  ramp, that is not a mesh issue (wrong Meshes) but  clearly a compatibility problem between the two Physics Engines.

With respect,
Ana  Green

**Comment by emperorstarfinder** [comment]
It is important to remember here that UbODE (UBit's customized version of Open Dynamics Engine) is not in WhiteCoreSim.  WhiteCoreSim developers, therefore, cannot really help you when it comes to issues you may be finding with UbODE and BulletSim in OpenSimulator.  Likewise, WhiteCoreSim does not have HyperGrid.

If you are finding issues with bugs relating to HyperGrid or OpenSimulator then you need to report those issues to the OpenSimulator Mantis.

**Comment by Ana-Green** [comment]
I don't see what a Physics Engine has to do with Hypergrid? I just observed the difference between UbODE and BulletSim, both Physics  engines are not WhiteCoreSim specific thus they are used on a wide range of OpenSimulators, and indeed I should post this issue to the OpenSimulator Mantis.

**Comment by Ana-Green** [comment]
CLOSED Forwarded to OpenSimulator Mantis.

**Comment by emperorstarfinder** [comment]
While this issue is now closed, I am just going to make a quick clarification so there isn't any misunderstanding of the mention of hypergrid.

> If a woman put her shoes on, on a region where Bullet is activated it looks ok, however, if that woman HG Teleport or local Teleport to a region with ODE activated the shoes do not fit anymore she has to re-adjust it with the HUD what comes with the Mesh Body.

Reference to HG Teleport was mentioned.  HG is interpreted to mean Hypergrid.  

I am also going to post the message from the core developer on my team relating to the mention of the physics engine issue in OpenSimulator as it was mentioned here as well.  I am posting her comment from our internal discussions as she is the authority on my team that does have the best knowledge about a physics engine's development

> There will always be differences in physics engines.  The differences can vary by the physics engine, grid customizations, and compatibility by different architectures.  For example, WhiteCoreSim has its own customized version of OpenDynamicsEngine and BulletSim.  While they are compatible and work with the architecture, they may not necessarily be compatible with another architecture, and the behavior when teleporting from a region using ODE to a region using BulletSim causes the properties that are interpreted by the two engines in some cases to be different, thus causing problems that are not necessarily intended.  
> 
> Additionally, some architectures like OpenSimulator might require the use of different meshing systems depending on the physics engine.  Lately on OpenSimulator if you use UbODE you need to use the MeshMerizer customized to work with UbODE.  In the view of this humble developer, this was a mistake and therefore is more likely to be the cause of your issue with rendering a mesh avatar and not necessarily the physics engine.
