### ISSUE TITLE
What make I wrong - first start (Standalone)

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#312]
Hello all ;D
Ok, I am not a new user, so I have after months now install WhiteCoreSim. At first start - where is the question with the user name ? I have this messages in the console ...

BS; LinuxMint 19.2
MonoVersion 5.10.x

What make I wrong ?

![Bildschirmfoto vom 2019-08-16 23-53-10](https://user-images.githubusercontent.com/614576/63200580-17daaf80-c082-11e9-9595-13ac242cec5a.png)

Greetings 
Bogus

**Comment by greythane** [comment]
Hi Bogus,
I have nearly finished some updates that change the start up process and have found a problem with some initial things being skipped, particularly when using Windows.   
I will build and upload some new packages and update as soon as possible.

**Comment by BogusCurry** [comment]
Hi Greythane ;D
Thanks for your answer ;D

Have a nice Day ;D
Bogus

**Comment by greythane** [comment]
Hi Bogus,
I have just pushed through quite a big update that corrects quite a few issues that I have seen whilst testing.  
The main difference is that the structure of the 'Config' folder have been simplified and the startup scripts now will run the configurator at startup to allow a Q & A setup of the Grid, Standalone or Grid region.  
Btw:  An existing 'Config' will still work correctly but the inbuilt configurator will not run as the structure is now different.  

Any feedback is appreciated.

**Comment by BogusCurry** [comment]
Hello ;D
My problem is fix ;D Thanks for you support ;D
