### ISSUE TITLE
i need change strings in spanish for webui

### ISSUE THREAD

**Issue by johnfelipe** [WhiteCoreSim/WhiteCore-Dev#323]
i have this path:

/home/felipe/WhiteCore-Dev/WhiteCoreSim/Data/html/translations/es.po

and i need change:

![SNAG-0548](https://user-images.githubusercontent.com/428820/81688026-f9da8980-941e-11ea-8593-2c185fd11439.png)

for ACCESO AL MUNDO, where can do that and steps for do that?

**Comment by greythane** [comment]
Hi Johnfelipe,
You can modify the translation files using the program 'poedit'  

For Linux (Ubuntu) you can install using ..  
`sudo apt-get install poedit`

For the latest or other systems check out [https://poedit.net](https://poedit.net)  

This will show you the untranslated string together with the required translation which you can correct.  
If you correct any of the details, please create a pull request or email me the new file and I will include it in the main code.

**Comment by johnfelipe** [comment]
Yes I will pull request of course.
But Wich one commands and path for do that?
I can't view .mo files and other things
Sorry if this is dummy but I will share to u cheatsheet Doc, may be other
users will review in future, pls tell me how edit and compile Spanish
strings and check in webui

**Comment by greythane** [comment]
The file you indicated is the correct one to edit.  
`WhiteCoreSim/Data/html/translations/es.po`  

You need to install the 'poedit' program to open and modify the translation strings. Open the 'es.po' file in poedit and then modify the translation details.  

You will get something like this...  
![Screen Shot 2020-05-13 at 10 00 12 am](https://user-images.githubusercontent.com/4934735/81757316-d89e9980-9501-11ea-885e-bf78e330598f.png)  

English text on the left   --   Translated text on the right.  
Change the text on the the right to the correct translation and then save the new 'es.po' file.  
Use  `File  - Save `to save your updates.  These changes will be available when you next restart WhiteCore.

**Comment by johnfelipe** [comment]
Dear I have windows not Mac
And my Linux is Ubuntu 18 server version
But in windows I have poedit, then is only use and save and upload new file?
I do that and edit some strings and that method not working

**Comment by greythane** [comment]
You should be able to copy the 'es.po' to Windows, edit it, save and then upload back to your Ubuntu system.  (I do the same thing on Mac OSX)  
The updated translation details should then be available after you restart the WhiteCore grid server (or standalone system)  

If the translated details are not being correctly updated then please send me the 'es.po' file so I can check and see why it is causing problems. My email is in the ReadMe.txt file in WhiteCoreSim

**Comment by emperorstarfinder** [comment]
On Windows you can also edit the es.po file using notepad++.  Notepad++ is free and can be found at: https://notepad-plus-plus.org/downloads/

The translated files will in fact update and work though you will likely need to restart the services before it will update in the webui via the browser.
