### ISSUE TITLE
Scripts Broken since Specific Commit

### ISSUE THREAD

**Issue by KM198912** [WhiteCoreSim/WhiteCore-Dev#326]
### Steps to reproduce

1.Setup a Regular instance, doesnt matter if standalone or grid
2.create a script that uses a list , for example for menu buttons
3.

### Expected behaviour

List should work as expected

### Actual behaviour

ODE Spits hundreds of error messages that list does not exists, i managed to track this down back to commit : https://github.com/WhiteCoreSim/WhiteCore-Dev/commit/0d29161cd5d1556a4506059566d35eacf80ffdea

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache 2.4

**Database:**Maria DB

**WhiteCore version:** 0.9.5 latest dev

### Logs
unfortunatly no log does exist anymore since wiping the folder and downgrading to the named commit

**Comment by greythane** [comment]
Thanks for the report.
This appears to be when I split th (very) large LSL type file into smaller chunks and also reformatted procedure names to confirm with c# syntax recommendations.  
I'm guessing that something is objecting to the change i case of the LSLType.List  

I will check this out

**Comment by greythane** [comment]
Problem appears to be missed case corrections in the LSL translation and code compilation  
Corrections pushed into master for testing.  

Note: Compilation has not been verified fully due to other work in progress  - Please check and advise of your results

**Comment by KM198912** [comment]
adding a simple list test = []; compiled , i havent tested more so far

**Comment by KM198912** [comment]
Seems this can be closed , i have another issue which i will open a new issue for
