### ISSUE TITLE
How can install 10 days ago repo?

### ISSUE THREAD

**Issue by johnfelipe** [WhiteCoreSim/WhiteCore-Dev#333]
Hi dear, i need to presentation to my students with my oar for university, and really is more easy install and management with your repo, but 10 days ago i install all clean, but now is not possible login into region.
Can u give me instruction cheatsheet style for install in linux grid version of you opensim version?

**Comment by johnfelipe** [comment]
Can u tell me steps for install version of 14 days ago...

**Comment by greythane** [comment]
Apologies,
I thought I had posted this days ago, maybe on another issue  :(  

Anyway...  attached is the rundown that I used to create a new instance on an Ubuntu 20.04 virtual machine to check.  
[whitecore build Ubuntu 20.04.txt](https://github.com/WhiteCoreSim/WhiteCore-Dev/files/6605123/whitecore.build.Ubuntu.20.04.txt)

**Comment by johnfelipe** [comment]
hi dear i put this commands and steps

git clone https://github.com/WhiteCoreSim/WhiteCore-Dev.git


    # change to the code main directory for building
    cd WhiteCore-Dev

# Note msbuild is not included in the focal repos yet so xbuild is needed
... edit 'autobuild.sh' and replace 'msbuild' with 'xbuild' or comment/uncomment the appropriate compile option
    /home/felipe/WhiteCore-Dev/autobuild.sh
    ( Line 104 in the BUILD section at the bottom )
    From this:
      #msbuild WhiteCore.sln /property:Configuration="$CONFIG" /property:Platform="$ARCH"
    To this:
      xbuild WhiteCore.sln /property:Configuration="$CONFIG" /property:Platform="$ARCH"

# make scripts executable if necessary
    chmod +x *.sh

# build WhiteCoreSim  
# Note:  This should be executed as a (normal) user, NOT sudo or the root user

    ./autobuild.sh

... complie output
... probable warnings but there should be no errors

But i have a lot of errors

               3 Warning(s)
               2986 Error(s)
      
      Time Elapsed 00:00:04.7610600
      Finished Building WhiteCore
      Thank you for choosing WhiteCore-Sim
      Please report any errors to our Github Issue Tracker https://github.com/WhiteCoreSim/WhiteCore-Dev/issues


how can solve this?

**Comment by johnfelipe** [comment]
![SNAG-0649](https://user-images.githubusercontent.com/428820/121089971-82a43000-c7ad-11eb-910e-09054e5bfa4a.png)

then wich step need to do?

**Comment by johnfelipe** [comment]
i do this stes and really dont know what happend

https://gist.github.com/petergloor/39ba915d3a66d138448ed57be6fe93ca

can u share me your email, can i send you credentials for my server and you do steps in there, becuase i need your opensim branch in 10 hours, pls help me

**Comment by greythane** [comment]
Hi Felipe,
What sort of errors did you get?    
With the number of errors reported I would assume that some configuration or mono module is missing.  

Also... my email address is in the build scripts    
The gist you referred to is a work-a-round to install an older version of mono that has msbuild.exe included.  Using xbuild to complie will still work correctly

**Comment by johnfelipe** [comment]
I send you email with credentials and instructions, pls pls help me im
counting with u
