### ISSUE TITLE
Bind commands to the specific server

### ISSUE THREAD

**Issue by fly-man-** [WhiteCoreSim/WhiteCore-Dev#57]
* Find a good way to get the Region and Grid commands separated so you can't run a grid command from a region server (example: create user)

**Comment by greythane** [comment]
Updated as of commit #723d954.
Please advise if any commands are out of place.  
The full command list is available on the whitecore-sim.org website

**Comment by fly-man-** [comment]
Looks like all the commands are now stuck on the correct service. Closing this as it was a Enhancement
