### ISSUE TITLE
Adding Estate Managers to This Estate adds to an entire estate not just one region.

### ISSUE THREAD

**Issue by emperorstarfinder** [WhiteCoreSim/WhiteCore-Dev#65]
In secondlife adding an estate manager to one region would be the same as using This Estate as the option and All Estates as the entire estate of the region owner.  Question:  Is this what it was intended to be in WhiteCore-Sim or is it intended to be all the regions on an estate by selecting This Estate.

This is more a question but It probably should be as follows for options when adding Estate Managers to each region and or estate.:

- This Estate = Region
- All Estates = Estate

Otherwise there is not a bug when adding estate managers to the estate.

Also if I wanted to add another static folder to my default inventory all i would have to do is add it to the DefaultInventory.iar and to the DevaultInventoryArchive.cs file correct?  And would that also add it to the default library as well?

**Comment by fly-man-** [comment]
[Issue Checker] Is this still an issue that needs to be active looked at ?

**Comment by emperorstarfinder** [comment]
It is being withdrawn from WhiteCore's issues list due to it not being a persisting bug.  It is however being further reviewed by the Second Galaxy Development Team and our opensource project partners.  If a workaround is found potentially this workaround will be provided to WhiteCore with conditions being required.
