### ISSUE TITLE
Parcel Bugs

### ISSUE THREAD

**Issue by SargeMisfit** [WhiteCoreSim/WhiteCore-Dev#80]
Parcel options do not function as expected.
I can subdivide parcels. 
Naming the parcel or adding a description over-writes ALL of the land, other parcels included.
Can set parcel to Sell but other person cannot buy
Can set parcel to Group but cannot Deed

Stats:
Firestorm 4.6.7 (42398) Aug 12 2014 00:54:42 (Firestorm-Release) with OpenSimulator support
Release Notes

CPU: AMD A8-3820 APU with Radeon(tm) HD Graphics (2495.5 MHz)
Memory: 6101 MB
OS Version: Microsoft Windows 7 64-bit Service Pack 1 (Build 7601)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: GeForce 9500 GT/PCIe/SSE2

Windows Graphics Driver Version: 9.18.0013.4052
OpenGL Version: 3.3.0

RestrainedLove API: (disabled)
libcurl Version: libcurl/7.24.0 OpenSSL/1.0.1h zlib/1.2.5 c-ares/1.10.0
J2C Decoder Version: KDU v7.4
Audio Driver Version: FMOD Ex 4.44.32
Qt Webkit Version: 4.7.1 (version number hard-coded)
Voice Server Version: Not Connected
Settings mode: Firestorm
Viewer Skin: Firestorm (Grey)
Font Used: Deja Vu (96)
Draw distance: 1024
Bandwidth: 1500
LOD factor: 2
Render quality: Medium-High (4/7)
Texture memory: 512 MB (1)
VFS (cache) creation time (UTC): unknown
Built with MSVC version 1600

Instance is Excelsior Station, online, stand-alone, 8,192m x 8,192m
Ethernet connected to fiber-optic ISP
Server is a single-core 64bit running Windows 7 Ultimate 64bit, 3Gb RAM and a 320Gb HardDrive

**Comment by fly-man-** [comment]
[Issue Checker] Is this still an issue that needs to be active looked at ?

**Comment by fly-man-** [comment]
[Issue Checker] Issue has been closed due to no response from initial reporter
