### ISSUE TITLE
[Bug] Deserializing not Waiting on Viewer Request

### ISSUE THREAD

**Issue by WhiteCoreWebUI** [WhiteCoreSim/WhiteCore-Dev#93]
When the Viewer sends a Request to the WhiteCore.exe using any version of Mono it will not wait 500ms before deserializing, a example output is here:

Nov 09 01:41:42 -  [WebUtils]: osd request (URI:http://xx.xx.xx.xx:8012/grid/, METHOD:POST, UPSTACK(4):DoRemoteCallGet) took 14ms overall, 6ms writing, 8ms deserializing

**Comment by fly-man-** [comment]
Is this still an actual bug that you are experiencing ?
